Attribute VB_Name = "modLangData4"
'==============================================================================
' modLangData4  -  Retail Store Management System: part 4 of the Arabic ->
' English dictionary of the interface (modLang). GENERATED FILE - do not edit.
' Source: tools/i18n_en.py  ->  python3 tools/generate.py
'==============================================================================
Option Compare Database
Option Explicit

Public Sub LangData4()
    D4_1
    D4_2
    D4_3
    D4_4
    D4_5
    D4_6
End Sub

Private Sub D4_1()
    LangAdd "كل الصناديق", "All boxes"
    LangAdd "كل العمليات", "All transactions"
    LangAdd "كل المنتجات", "All products"
    LangAdd "كلمة المرور", "Password"
    LangAdd "كود التفعيل", "Activation code"
    LangAdd "كود المندوب", "Sales rep code"
    LangAdd "لوحة التحكم", "Dashboard"
    LangAdd "مبلغ الأساس", "Base amount"
    LangAdd "مبلغ الحركة", "Move amount"
    LangAdd "مثال: 25 أو", "Example: 25 or"
    LangAdd "مدة التكرار", "Repeats"
    LangAdd "مدى / بطاقة", "Mada / card"
    LangAdd "مدين الفترة", "Period debit"
    LangAdd "مسار الشعار", "Logo path"
    LangAdd "مسح القائمة", "Clear the list"
    LangAdd "مصدر الشراء", "Purchase source"
    LangAdd "مكان المنتج", "Product location"
    LangAdd "منخفض: الحد", "Low: level"
    LangAdd "نتيجة الطلب", "Request result"
    LangAdd "نوع العملية", "Transaction type"
    LangAdd "نوع المستند", "Document type"
    LangAdd "نوع المصروف", "Expense type"
    LangAdd "وضع المطوّر", "Developer mode"
    LangAdd "يُحتفظ بآخر", "Keeps the last"
    LangAdd "آخر فاتورة", "Last invoice"
    LangAdd "أسطر الجرد", "Count lines"
    LangAdd "أسطر الطلب", "Order lines"
    LangAdd "أقصى تأخير", "Longest delay"
    LangAdd "أقفل السنة", "Close the year"
    LangAdd "إرجاع الكل", "Return all"
    LangAdd "إشعار دائن", "Credit note"
    LangAdd "إقفال فترة", "Close a period"
    LangAdd "إلغاء الكل", "Clear all"
    LangAdd "إهلاك سابق", "Previous depreciation"
    LangAdd "اختر البنك", "Choose the bank"
    LangAdd "اختر الدور", "Choose the role"
    LangAdd "اختر السند", "Choose the voucher"
    LangAdd "اختر الشهر", "Choose the month"
    LangAdd "اختر الشيك", "Choose the cheque"
    LangAdd "استلمنا من", "Received from"
    LangAdd "اسم الحساب", "Account name"
    LangAdd "اسم العملة", "Currency name"
    LangAdd "اسم العميل", "Customer name"
    LangAdd "اسم المركز", "Center name"
    LangAdd "اسم المنتج", "Product name"
    LangAdd "اسم المورد", "Supplier name"
    LangAdd "اسم الموظف", "Employee name"
    LangAdd "اسم الوحدة", "Unit name"
    LangAdd "اكتب السنة", "Type the year"
    LangAdd "اكتب تاريخ", "Type the date"
    LangAdd "العمر (شهر", "Life (months"
    LangAdd "الفترة: من", "Period: from"
    LangAdd "الفرق (صفر", "Difference (zero"
    LangAdd "المستخدمون", "Users"
    LangAdd "بحث بالاسم", "Search by name"
    LangAdd "بدلات أخرى", "Other allowances"
    LangAdd "بدون ضريبة", "Without VAT"
    LangAdd "بدون طباعة", "No printing"
    LangAdd "بيان السطر", "Line description"
    LangAdd "تحديد الكل", "Select all"
    LangAdd "تحويل صادر", "Outgoing transfer"
    LangAdd "تحويل وارد", "Incoming transfer"
    LangAdd "تعذر الحفظ", "Could not save"
    LangAdd "تم الإرسال", "Sent"
    LangAdd "تم الإلغاء", "Cancelled"
    LangAdd "ثمانية عشر", "eighteen"
    LangAdd "حدد الفترة", "Set the period"
    LangAdd "حذف الحركة", "Delete the move"
    LangAdd "حفظ الحركة", "Save the move"
    LangAdd "حفظ وطباعة", "Save and print"
    LangAdd "حقوق ملكية", "Equity"
    LangAdd "حُوِّل إلى", "Transferred to"
    LangAdd "ربط السداد", "Payment matching"
    LangAdd "رصيد الكشف", "Statement balance"
    LangAdd "رقم الجهاز", "Computer number"
    LangAdd "رقم الجوال", "Mobile number"
    LangAdd "رقم الحساب", "Account number"
    LangAdd "رقم المبنى", "Building number"
    LangAdd "رمز العملة", "Currency code"
    LangAdd "رمز المركز", "Center code"
    LangAdd "رمز الوحدة", "Unit code"
    LangAdd "ريال سعودي", "Saudi riyal"
    LangAdd "شاشة البيع", "Sales screen"
    LangAdd "صافي الربح", "Net profit"
    LangAdd "صرفه البنك", "Cashed by the bank"
    LangAdd "طريقة الرد", "Refund method"
    LangAdd "عدد القيود", "Number of entries"
    LangAdd "على الحساب", "On account"
    LangAdd "على العميل", "The customer"
    LangAdd "غير متوازن", "Not balanced"
    LangAdd "فئة إضافات", "Extras category"
    LangAdd "فاتورة بيع", "Sales invoice"
    LangAdd "فتح المجلد", "Open the folder"
    LangAdd "فرق العملة", "Exchange difference"
    LangAdd "قيمة الفرق", "Difference value"
    LangAdd "كل الجداول", "All tables"
    LangAdd "كل الشاشات", "All screens"
    LangAdd "كل المراكز", "All centers"
    LangAdd "كمية الصنف", "Item quantity"
    LangAdd "كود المنتج", "Product code"
    LangAdd "مبلغ السند", "Voucher amount"
    LangAdd "مبلغ الشيك", "Cheque amount"
    LangAdd "مجمل الربح", "Gross profit"
    LangAdd "مرتجع شراء", "Purchase return"
    LangAdd "مرجع البنك", "Bank reference"
    LangAdd "مرحَّلة في", "posted on"
    LangAdd "مسودة مسير", "Run draft"
    LangAdd "من القائمة", "from the list"
    LangAdd "منها ضريبة", "of which VAT"
    LangAdd "نسبة صفرية", "Zero rate"
    LangAdd "نقطة البيع", "Point of sale"
    LangAdd "نوع الحركة", "Move type"
    LangAdd "نوع الحساب", "Account type"
    LangAdd "نوع الشراء", "Purchase type"
    LangAdd "ورقة الجرد", "Count sheet"
    LangAdd "آخر تحديث", "Last update"
    LangAdd "آخر تصفية", "Last closing"
    LangAdd "آخر معامل", "Last rate"
    LangAdd "أربعة عشر", "fourteen"
    LangAdd "أُنشئ منه", "Created from it"
End Sub

Private Sub D4_2()
    LangAdd "إعادة فتح", "Reopen"
    LangAdd "إقفال سنة", "Close a year"
    LangAdd "إلى تاريخ", "To date"
    LangAdd "إلى صندوق", "To box"
    LangAdd "إيصال بيع", "Sales receipt"
    LangAdd "اسم الأصل", "Asset name"
    LangAdd "اسم المحل", "Store name"
    LangAdd "اعتُمد في", "Approved on"
    LangAdd "الإعدادات", "Settings"
    LangAdd "الإيرادات", "Revenue"
    LangAdd "الاستحقاق", "Due date"
    LangAdd "التأمينات", "Social insurance"
    LangAdd "التصنيفات", "Categories"
    LangAdd "التعديلات", "Changes"
    LangAdd "المدفوعات", "Payments"
    LangAdd "المرتجعات", "Returns"
    LangAdd "المستندات", "Documents"
    LangAdd "المشتريات", "Purchases"
    LangAdd "المصروفات", "Expenses"
    LangAdd "المقبوضات", "Receipts"
    LangAdd "المندوبين", "Sales reps"
    LangAdd "بدل السكن", "Housing allowance"
    LangAdd "بدل النقل", "Transport allowance"
    LangAdd "بعد اليوم", "after today"
    LangAdd "بلا نهاية", "No end"
    LangAdd "تحصيل شيك", "Cheque collection"
    LangAdd "تسوية مدى", "Mada settlement"
    LangAdd "تمت إضافة", "Added"
    LangAdd "ثلاثة عشر", "thirteen"
    LangAdd "ثمن البيع", "Sale price"
    LangAdd "جنيه مصري", "Egyptian pound"
    LangAdd "حذف القيد", "Delete the entry"
    LangAdd "حركة منتج", "Product moves"
    LangAdd "حفظ الأصل", "Save the asset"
    LangAdd "حفظ السند", "Save the voucher"
    LangAdd "حفظ القيد", "Save the entry"
    LangAdd "حفظ تصفية", "Save closing"
    LangAdd "حفظ مسودة", "Save draft"
    LangAdd "حُدِّث في", "Updated on"
    LangAdd "خصم السطر", "Line discount"
    LangAdd "خصم السلف", "Advance deductions"
    LangAdd "دخول خاطئ", "Wrong login"
    LangAdd "رصيد دائن", "Credit balance"
    LangAdd "رصيد سابق", "Previous balance"
    LangAdd "رقم الجرد", "Count number"
    LangAdd "رقم السند", "Voucher number"
    LangAdd "رقم الشيك", "Cheque number"
    LangAdd "رقم القيد", "Entry number"
    LangAdd "ساخن جدًا", "Extra hot"
    LangAdd "سحب نقدية", "Cash withdrawal"
    LangAdd "سعر البيع", "Sale price"
    LangAdd "سلفة موظف", "Employee advance"
    LangAdd "سنة جديدة", "New year"
    LangAdd "سند نقدية", "Cash voucher"
    LangAdd "سُجِّل في", "Recorded on"
    LangAdd "شراء نقدي", "Cash purchase"
    LangAdd "صرفنا إلى", "Paid to"
    LangAdd "طرق الدفع", "Payment methods"
    LangAdd "طلب توصيل", "Delivery order"
    LangAdd "طلب داخلي", "Dine-in order"
    LangAdd "عجز تصفية", "Closing shortage"
    LangAdd "عكس القيد", "Reverse the entry"
    LangAdd "عمولة مدى", "Mada fee"
    LangAdd "غير مربوط", "Unlinked"
    LangAdd "غير مستحق", "Not due"
    LangAdd "غير مقفلة", "Not closed"
    LangAdd "غير ملائم", "Unsuitable"
    LangAdd "فتح القيد", "Open the entry"
    LangAdd "في المسير", "in the run"
    LangAdd "قيد محذوف", "Deleted entry"
    LangAdd "قيد يومية", "Journal entry"
    LangAdd "كل 3 أشهر", "Every 3 months"
    LangAdd "ليس بصيغة", "is not in the format of"
    LangAdd "مبلغ سنوي", "Yearly amount"
    LangAdd "مرتجع بيع", "Sales return"
    LangAdd "مستبعد في", "Disposed on"
    LangAdd "مقارنة من", "Comparison from"
    LangAdd "مقفلة حتى", "Closed up to"
    LangAdd "منتج جديد", "New product"
    LangAdd "نسخ الرقم", "Copy the number"
    LangAdd "نوع البيع", "Sale type"
    LangAdd "نوع السند", "Voucher type"
    LangAdd "هذا الشهر", "This month"
    LangAdd "هذه السنة", "This year"
    LangAdd "ولم يُرسل", "and not sent"
    LangAdd "ومصروف في", "and paid on"
    LangAdd "يمكن ربطه", "Can be linked"
    LangAdd "يُصرف إلى", "Paid to"
    LangAdd "آخر حركة", "Last move"
    LangAdd "آخر دخول", "Last login"
    LangAdd "آخر نسخة", "Last backup"
    LangAdd "أربعمائة", "four hundred"
    LangAdd "أصل جديد", "New asset"
    LangAdd "اثنا عشر", "twelve"
    LangAdd "الإجمالي", "Total"
    LangAdd "الإضافات", "Extras"
    LangAdd "الارتداد", "Bounce"
    LangAdd "الاستلام", "Receipt"
    LangAdd "الانحراف", "Variance"
    LangAdd "الباركود", "Barcode"
    LangAdd "التقارير", "Reports"
    LangAdd "السعودية", "Saudi Arabia"
    LangAdd "الصادرات", "Exports"
    LangAdd "الصلاحية", "Permission"
    LangAdd "الصناديق", "Boxes"
    LangAdd "العمولات", "Commissions"
    LangAdd "الفاتورة", "Invoice"
    LangAdd "الفواتير", "Invoices"
    LangAdd "المبيعات", "Sales"
    LangAdd "المجموعة", "Group"
    LangAdd "المرحَّل", "Posted"
    LangAdd "المستخدم", "User"
    LangAdd "المسيرات", "Runs"
    LangAdd "المنتجات", "Products"
    LangAdd "الموازنة", "Budget"
    LangAdd "الموردون", "Suppliers"
    LangAdd "بدون سكر", "No sugar"
    LangAdd "بيع نقدي", "Cash sale"
    LangAdd "تسعة عشر", "nineteen"
    LangAdd "تم إنشاء", "Created"
End Sub

Private Sub D4_3()
    LangAdd "تم الحذف", "Deleted"
    LangAdd "تم الحفظ", "Saved"
    LangAdd "تم الربط", "Linked"
    LangAdd "ثلاثمائة", "three hundred"
    LangAdd "ثلج قليل", "Little ice"
    LangAdd "ثمانمائة", "eight hundred"
    LangAdd "جرد جديد", "New count"
    LangAdd "حتى الآن", "So far"
    LangAdd "حجم الخط", "Font size"
    LangAdd "خمسة عشر", "fifteen"
    LangAdd "ربع سنوي", "Quarterly"
    LangAdd "رمز الرد", "Reply code"
    LangAdd "سبعة عشر", "seventeen"
    LangAdd "سكر قليل", "Little sugar"
    LangAdd "شراء آجل", "Credit purchase"
    LangAdd "شهر جديد", "New month"
    LangAdd "شيك صادر", "Issued cheque"
    LangAdd "شيك مرتد", "Bounced cheque"
    LangAdd "شيك وارد", "Received cheque"
    LangAdd "صفر جنيه", "zero pounds"
    LangAdd "صفر ريال", "zero riyals"
    LangAdd "طلب سفري", "Takeaway order"
    LangAdd "غير صالح", "Invalid"
    LangAdd "غير مسدد", "Unpaid"
    LangAdd "غير موزع", "Not allocated"
    LangAdd "فعلي سنة", "Actuals of year"
    LangAdd "فك القفل", "Unlock"
    LangAdd "قيد جديد", "New entry"
    LangAdd "قيد عكسي", "Reversing entry"
    LangAdd "قيد يدوي", "Manual entry"
    LangAdd "كشف حساب", "Account statement"
    LangAdd "لا يُرسل", "Not sent"
    LangAdd "لم يُنشأ", "Not created"
    LangAdd "لون الزر", "Button color"
    LangAdd "معتمد في", "Approved on"
    LangAdd "مقفل حتى", "Closed up to"
    LangAdd "من البنك", "From the bank"
    LangAdd "من تاريخ", "From date"
    LangAdd "من صندوق", "From a box"
    LangAdd "نوع جديد", "New type"
    LangAdd "والمتوفر", "and available"
    LangAdd "ورقة جرد", "Count sheet"
    LangAdd "ينتهي في", "Ends on"
    LangAdd "يوجد فرق", "There is a difference"
    LangAdd "آخر بيع", "Last sale"
    LangAdd "آخر خطأ", "Last error"
    LangAdd "أحد عشر", "eleven"
    LangAdd "أكثر من", "More than"
    LangAdd "إيرادات", "Revenue"
    LangAdd "ابحث في", "Search in"
    LangAdd "استحقاق", "Due"
    LangAdd "استعراض", "Browse"
    LangAdd "افتراضي", "Default"
    LangAdd "الآيبان", "IBAN"
    LangAdd "الأدوار", "Roles"
    LangAdd "الأرباح", "Profit"
    LangAdd "الأساسي", "Basic"
    LangAdd "الأصناف", "Items"
    LangAdd "الأهداف", "Targets"
    LangAdd "الإصدار", "Version"
    LangAdd "الإضافي", "Overtime"
    LangAdd "الإقرار", "Return"
    LangAdd "الإنجاز", "Achievement"
    LangAdd "الإهلاك", "Depreciation"
    LangAdd "البدلات", "Allowances"
    LangAdd "التاريخ", "Date"
    LangAdd "التالية", "Next"
    LangAdd "التحصيل", "Collections"
    LangAdd "الترتيب", "Order"
    LangAdd "الترحيل", "Posting"
    LangAdd "التسوية", "Reconciliation"
    LangAdd "التصنيف", "Category"
    LangAdd "التعديل", "Adjustment"
    LangAdd "التقييم", "Valuation"
    LangAdd "التكرار", "Frequency"
    LangAdd "التكلفة", "Cost"
    LangAdd "الحركات", "Moves"
    LangAdd "الخزينة", "Treasury"
    LangAdd "الدفتري", "Book value"
    LangAdd "الرواتب", "Payroll"
    LangAdd "الزيادة", "Overage"
    LangAdd "السابقة", "Previous"
    LangAdd "السندات", "Vouchers"
    LangAdd "الشيكات", "Cheques"
    LangAdd "الصندوق", "Box"
    LangAdd "الضريبة", "VAT"
    LangAdd "الطابعة", "Printer"
    LangAdd "الطريقة", "Method"
    LangAdd "العملاء", "Customers"
    LangAdd "العملات", "Currencies"
    LangAdd "العملية", "Transaction"
    LangAdd "العمولة", "Commission"
    LangAdd "العنوان", "Address"
    LangAdd "القائمة", "List"
    LangAdd "الكاشير", "Cashier"
    LangAdd "المتبقي", "Remaining"
    LangAdd "المتوفر", "Available"
    LangAdd "المتوقع", "Expected"
    LangAdd "المجموع", "Total"
    LangAdd "المحاسب", "Accountant"
    LangAdd "المحصّل", "Collector"
    LangAdd "المخزون", "Stock"
    LangAdd "المدفوع", "Paid"
    LangAdd "المدينة", "City"
    LangAdd "المراجع", "Reviewer"
    LangAdd "المرتجع", "Return"
    LangAdd "المرتدة", "Bounced"
    LangAdd "المسؤول", "Manager"
    LangAdd "المستحق", "Due"
    LangAdd "المستلم", "Recipient"
    LangAdd "المستند", "Document"
    LangAdd "المستوى", "Level"
    LangAdd "المشروب", "Drink"
    LangAdd "المشكلة", "Problem"
    LangAdd "المصروف", "Expense"
    LangAdd "المطلوب", "required"
    LangAdd "المعامل", "Rate"
    LangAdd "المندوب", "Sales rep"
    LangAdd "المنطقة", "Region"
    LangAdd "الوحدات", "Units"
End Sub

Private Sub D4_4()
    LangAdd "بدون حد", "No limit"
    LangAdd "برتقالي", "Orange"
    LangAdd "تجريبية", "Test"
    LangAdd "تسعمائة", "nine hundred"
    LangAdd "خمسمائة", "five hundred"
    LangAdd "رد نقدي", "Cash refund"
    LangAdd "سبعمائة", "seven hundred"
    LangAdd "ستة عشر", "sixteen"
    LangAdd "سطر قيد", "Entry line"
    LangAdd "سند صرف", "Payment voucher"
    LangAdd "سند قبض", "Receipt voucher"
    LangAdd "صرف آخر", "Other payment"
    LangAdd "صرف شيك", "Cheque payment"
    LangAdd "طُبع في", "Printed on"
    LangAdd "غير نشط", "is not active"
    LangAdd "في شاشة", "in the screen"
    LangAdd "لا توجد", "None"
    LangAdd "للإضافة", "to add"
    LangAdd "متوازنة", "Balanced"
    LangAdd "مرة/سنة", "times/year"
    LangAdd "مستويات", "levels"
    LangAdd "مصروفات", "Expenses"
    LangAdd "ملاحظات", "Notes"
    LangAdd "مليونان", "two million"
    LangAdd "مُبلَّغ", "Reported"
    LangAdd "والدائن", "and credit"
    LangAdd "يبدأ من", "Starts from"
    LangAdd "أجراها", "Done by"
    LangAdd "أربعون", "forty"
    LangAdd "أكتوبر", "October"
    LangAdd "أُرسلت", "Sent"
    LangAdd "إجمالي", "Total"
    LangAdd "ارتداد", "Bounced"
    LangAdd "اعتمده", "Approved by"
    LangAdd "الأساس", "Base"
    LangAdd "الأصول", "Assets"
    LangAdd "البنوك", "Banks"
    LangAdd "البيئة", "Environment"
    LangAdd "البيان", "Description"
    LangAdd "التالي", "Next"
    LangAdd "الجدول", "Table"
    LangAdd "الجهاز", "Computer"
    LangAdd "الجوال", "Mobile"
    LangAdd "الحالة", "Status"
    LangAdd "الحركة", "Move"
    LangAdd "الحساب", "Account"
    LangAdd "الدائن", "Credit"
    LangAdd "الرصيد", "Balance"
    LangAdd "السابق", "Previous"
    LangAdd "الشارع", "Street"
    LangAdd "الشاشة", "Screen"
    LangAdd "الشراء", "Purchase"
    LangAdd "الصافي", "Net"
    LangAdd "العملة", "Currency"
    LangAdd "العميل", "Customer"
    LangAdd "الفئات", "Categories"
    LangAdd "الفترة", "Period"
    LangAdd "الفعلي", "Actual"
    LangAdd "القيمة", "Value"
    LangAdd "الكمية", "Quantity"
    LangAdd "المالك", "Owner"
    LangAdd "المباع", "Sold"
    LangAdd "المبلغ", "Amount"
    LangAdd "المتجر", "Store"
    LangAdd "المجلد", "Folder"
    LangAdd "المدير", "Manager"
    LangAdd "المدين", "Debit"
    LangAdd "المركز", "Center"
    LangAdd "المسجل", "Recorded"
    LangAdd "المسدد", "Paid"
    LangAdd "المنتج", "Product"
    LangAdd "المورد", "Supplier"
    LangAdd "الموظف", "Employee"
    LangAdd "النسبة", "Rate"
    LangAdd "الهاتف", "Phone"
    LangAdd "الوحدة", "Unit"
    LangAdd "بالضبط", "exactly"
    LangAdd "بالفعل", "already exists"
    LangAdd "بزيادة", "over by"
    LangAdd "بلا حد", "No limit"
    LangAdd "بنفسجي", "Purple"
    LangAdd "بواسطة", "by"
    LangAdd "تغيّرت", "changed"
    LangAdd "تم حفظ", "Saved"
    LangAdd "تم عدّ", "Counted"
    LangAdd "ثلاثون", "thirty"
    LangAdd "ثمانون", "eighty"
    LangAdd "ثمانية", "eight"
    LangAdd "جزاءات", "Penalties"
    LangAdd "ديسمبر", "December"
    LangAdd "سبتمبر", "September"
    LangAdd "ستمائة", "six hundred"
    LangAdd "عمولات", "Commissions"
    LangAdd "عميلًا", "customers"
    LangAdd "فاتورة", "Invoice"
    LangAdd "فبراير", "February"
    LangAdd "في حقل", "in the field"
    LangAdd "في يوم", "on day"
    LangAdd "فيروزي", "Teal"
    LangAdd "لا غير", "only"
    LangAdd "لتصنيف", "for category"
    LangAdd "مائتان", "two hundred"
    LangAdd "متوازن", "Balanced"
    LangAdd "محصَّل", "Collected"
    LangAdd "مرحَّل", "Posted"
    LangAdd "مستبعد", "Disposed"
    LangAdd "مستخدم", "User"
    LangAdd "مستردة", "Refunded"
    LangAdd "معاينة", "Preview"
    LangAdd "معتمدة", "Approved"
    LangAdd "مكافآت", "Bonuses"
    LangAdd "ملايين", "million"
    LangAdd "ممنوحة", "Granted"
    LangAdd "من بنك", "From a bank"
    LangAdd "موازنة", "Budget"
    LangAdd "موردًا", "suppliers"
    LangAdd "مُرحّل", "Posted"
    LangAdd "نوفمبر", "November"
    LangAdd "أبريل", "April"
    LangAdd "أربعة", "four"
End Sub

Private Sub D4_5()
    LangAdd "أعدّه", "Prepared by"
    LangAdd "أغسطس", "August"
    LangAdd "ألفان", "two thousand"
    LangAdd "أُرسل", "Sent"
    LangAdd "أُضيف", "Added"
    LangAdd "إضافة", "Add"
    LangAdd "إغلاق", "Close"
    LangAdd "إلغاء", "Cancel"
    LangAdd "إيداع", "Deposit"
    LangAdd "اثنان", "two"
    LangAdd "الأصل", "Asset"
    LangAdd "الاسم", "Name"
    LangAdd "البحث", "Search"
    LangAdd "البند", "Item"
    LangAdd "البنك", "Bank"
    LangAdd "البيع", "Sale"
    LangAdd "الجرد", "Stock count"
    LangAdd "الجهة", "Party"
    LangAdd "الحجم", "Size"
    LangAdd "الحذف", "Delete"
    LangAdd "الحقل", "Field"
    LangAdd "الخصم", "Discount"
    LangAdd "الدفع", "Payment"
    LangAdd "الدور", "Role"
    LangAdd "الربح", "Profit"
    LangAdd "الرقم", "Number"
    LangAdd "الرمز", "Code"
    LangAdd "السبب", "Reason"
    LangAdd "السجل", "Record"
    LangAdd "السعر", "Price"
    LangAdd "السكن", "Housing"
    LangAdd "السنة", "Year"
    LangAdd "السند", "Voucher"
    LangAdd "الشهر", "Month"
    LangAdd "الصرف", "Payment"
    LangAdd "الصنف", "Item"
    LangAdd "الصور", "Pictures"
    LangAdd "العجز", "Shortage"
    LangAdd "العدد", "Count"
    LangAdd "الفرق", "Difference"
    LangAdd "القسم", "Department"
    LangAdd "القيد", "Entry"
    LangAdd "الكود", "Code"
    LangAdd "الملف", "File"
    LangAdd "النقص", "Shortage"
    LangAdd "النوع", "Type"
    LangAdd "الهدف", "Target"
    LangAdd "الوصف", "Description"
    LangAdd "الوقت", "Time"
    LangAdd "اليوم", "Today"
    LangAdd "بقيمة", "worth"
    LangAdd "تاريخ", "Date"
    LangAdd "تحديث", "Refresh"
    LangAdd "تحويل", "Transfer"
    LangAdd "تراجع", "Undo"
    LangAdd "تسعون", "ninety"
    LangAdd "تصدير", "Export"
    LangAdd "تعديل", "Edit"
    LangAdd "تقرير", "Report"
    LangAdd "توصيل", "Delivery"
    LangAdd "ثلاثة", "three"
    LangAdd "جارية", "Open"
    LangAdd "حرفًا", "characters"
    LangAdd "خزينة", "Treasury"
    LangAdd "خمسون", "fifty"
    LangAdd "داخلي", "Internal"
    LangAdd "دقيقة", "minutes"
    LangAdd "رئيسي", "Main"
    LangAdd "راجعه", "Reviewed by"
    LangAdd "رمادي", "Grey"
    LangAdd "زيادة", "Overage"
    LangAdd "سبعون", "seventy"
    LangAdd "طاولة", "Table"
    LangAdd "طباعة", "Print"
    LangAdd "عشرون", "twenty"
    LangAdd "عملية", "Transaction"
    LangAdd "فعلية", "Production"
    LangAdd "كاشير", "Cashier"
    LangAdd "متوقف", "Stopped"
    LangAdd "مدفوع", "Paid"
    LangAdd "مربوط", "Linked"
    LangAdd "مرتجع", "Return"
    LangAdd "مرفوض", "Rejected"
    LangAdd "مستند", "documents"
    LangAdd "مسودة", "Draft"
    LangAdd "مصروف", "Expense"
    LangAdd "مطابق", "Matched"
    LangAdd "مطلوب", "is required"
    LangAdd "معتمد", "Approved"
    LangAdd "مفتوح", "Open"
    LangAdd "مقبوض", "Received"
    LangAdd "ملائم", "Suitable"
    LangAdd "مليون", "million"
    LangAdd "منخفض", "Low"
    LangAdd "مُرسل", "Submitted"
    LangAdd "نتيجة", "Result"
    LangAdd "يساوي", "equals"
    LangAdd "يناير", "January"
    LangAdd "يوليو", "July"
    LangAdd "يومًا", "days"
    LangAdd "يونيو", "June"
    LangAdd "آلاف", "thousand"
    LangAdd "أحرف", "characters"
    LangAdd "أحمر", "Red"
    LangAdd "أخرى", "Other"
    LangAdd "أخضر", "Green"
    LangAdd "أزرق", "Blue"
    LangAdd "أصول", "Assets"
    LangAdd "أيام", "Days"
    LangAdd "احسب", "Calculate"
    LangAdd "اختر", "Choose"
    LangAdd "الحد", "limit"
    LangAdd "الحي", "District"
    LangAdd "الكل", "All"
    LangAdd "بثمن", "for a price"
    LangAdd "بدون", "None"
    LangAdd "تسعة", "nine"
    LangAdd "جديد", "New"
    LangAdd "جنيه", "EGP"
    LangAdd "حساب", "Account"
End Sub

Private Sub D4_6()
    LangAdd "خروج", "Exit"
    LangAdd "خصوم", "Liabilities"
    LangAdd "خمسة", "five"
    LangAdd "دائن", "Credit"
    LangAdd "دخول", "Login"
    LangAdd "رجوع", "Back"
    LangAdd "رصيد", "Balance"
    LangAdd "ريال", "SAR"
    LangAdd "سبعة", "seven"
    LangAdd "ستون", "sixty"
    LangAdd "سفري", "Takeaway"
    LangAdd "سلفة", "Advance"
    LangAdd "سنوي", "Yearly"
    LangAdd "شغّل", "Run"
    LangAdd "شهري", "Monthly"
    LangAdd "صادر", "Issued"
    LangAdd "صالح", "Valid"
    LangAdd "صغير", "Small"
    LangAdd "صفحة", "Page"
    LangAdd "عشرة", "ten"
    LangAdd "غياب", "Absence"
    LangAdd "فارغ", "Empty"
    LangAdd "فرعي", "Sub"
    LangAdd "قائم", "Open"
    LangAdd "كبير", "Large"
    LangAdd "مائة", "one hundred"
    LangAdd "مارس", "March"
    LangAdd "مايو", "May"
    LangAdd "محلي", "Local"
    LangAdd "مدين", "Debit"
    LangAdd "مرتد", "Bounced"
    LangAdd "مسدد", "Paid"
    LangAdd "مسير", "Run"
    LangAdd "ملغى", "Cancelled"
    LangAdd "ناقص", "Missing"
    LangAdd "نسخة", "Backup"
    LangAdd "نقدي", "Cash"
    LangAdd "نيلي", "Indigo"
    LangAdd "هاتف", "Phone"
    LangAdd "هللة", "halalas"
    LangAdd "واحد", "one"
    LangAdd "وارد", "Received"
    LangAdd "وردي", "Pink"
    LangAdd "يوجد", "There are"
    LangAdd "آجل", "Credit"
    LangAdd "ألف", "thousand"
    LangAdd "إلى", "To"
    LangAdd "بحث", "Search"
    LangAdd "بعد", "After"
    LangAdd "بني", "Brown"
    LangAdd "حتى", "Until"
    LangAdd "حذف", "Delete"
    LangAdd "حفظ", "Save"
    LangAdd "ر.س", "SAR"
    LangAdd "ربط", "The connection to"
    LangAdd "رقم", "Number"
    LangAdd "ستة", "six"
    LangAdd "سجل", "Record"
    LangAdd "سحب", "Withdrawal"
    LangAdd "شهر", "Month"
    LangAdd "صفر", "zero"
    LangAdd "صنف", "Item"
    LangAdd "عجز", "Shortage"
    LangAdd "عرض", "View"
    LangAdd "فتح", "Open"
    LangAdd "فرق", "Difference"
    LangAdd "فقط", "Only"
    LangAdd "قبل", "Before"
    LangAdd "قرش", "piasters"
    LangAdd "مسح", "Clear"
    LangAdd "مصر", "Egypt"
    LangAdd "نشط", "Active"
    LangAdd "نعم", "Yes"
    LangAdd "وسط", "Medium"
    LangAdd "في", "in"
    LangAdd "لا", "No"
    LangAdd "من", "From"
    LangAdd "هي", "is"
    LangAdd "و", "and"
End Sub
