Attribute VB_Name = "modLangData1"
'==============================================================================
' modLangData1  -  Retail Store Management System: part 1 of the Arabic ->
' English dictionary of the interface (modLang). GENERATED FILE - do not edit.
' Source: tools/i18n_en.py  ->  python3 tools/generate.py
'==============================================================================
Option Compare Database
Option Explicit

Public Sub LangData1()
    D1_1
    D1_2
    D1_3
End Sub

Private Sub D1_1()
    LangAdd "الحسابات الأساسية (المعلَّمة) تستخدمها القيود الآلية: لا تُحذف ولا يتغير نوعها. القيود اليدوية من زر «قيد يدوي", "The system accounts (marked) are used by the automatic entries: they are not deleted and their type does not change. Manual entries from the button Manual entry"
    LangAdd "يُعرض التقرير للمعاينة ومنها الطباعة. «حفظ PDF» و«تصدير Excel» يحفظان الملف في مجلد Reports بجانب ملف البرنامج", "The report is shown in preview and printed from it. Save PDF and Export Excel save the file in the Reports folder next to the program file"
    LangAdd "تم النسخ لكن تعذر فتح النسخة للتحقق منها. أعد المحاولة بعد إغلاق البرنامج على الأجهزة الأخرى", "Copied, but the copy could not be opened to check it. Try again after closing the program on the other computers"
    LangAdd "طابق العمليات الظاهرة في الكشف، وسجّل ما في الكشف ولم يُسجَّل (عمولات، فوائد...) كحركة بنكية", "Match the transactions shown on the statement, and record what is on the statement but not in the books (fees, interest...) as a bank transaction"
    LangAdd "لا يوجد موظفون في مسير الرواتب: حدّد «في مسير الرواتب» والراتب الأساسي في شاشة المستخدمين", "No employees on payroll: set On payroll and the basic salary in the Users screen"
    LangAdd "خانات نموذج هيئة الزكاة والضريبة والجمارك من المستندات، ثم الاعتماد وقيد التسوية والسداد", "The boxes of the ZATCA form from the documents, then the approval, the settlement entry and the payment"
    LangAdd "المستخدم يتبع صلاحيات دوره كما في القائمة. فعّل «صلاحيات شاشات خاصة» لتحديد شاشاته وحده", "The user follows the permissions of his role as in the list. Turn on Custom screen permissions to set his own screens"
    LangAdd "عدّل النسبة أو التعديل ثم «ترحيل المسير». الصرف بسند صرف نقدية من بند «صرف عمولة مندوب", "Edit the rate or the adjustment, then Post the run. The payment is a cash payment voucher with the item Sales rep commission payment"
    LangAdd "الحساب المقابل حساب فرعي نشط، وليس صندوقًا ولا بنكًا ولا مدى ولا العملاء أو الموردين", "The contra account is an active sub-account, not a box, a bank, Mada, customers or suppliers"
    LangAdd "حركة أي حساب برصيد أول المدة والرصيد بعد كل قيد؛ الحساب الرئيسي يشمل حساباته التابعة", "Moves of any account with the opening balance and the balance after each entry, a main account includes its sub-accounts"
    LangAdd "كل ما سُجّل بعد تاريخ هذه النسخة سيُفقد (تُحفظ نسخة وقائية من البيانات الحالية أولًا", "Everything recorded after the date of this backup will be lost (a safety copy of the current data is saved first"
    LangAdd "حدد الشاشات والإجراءات ثم اضغط «حفظ». الصلاحيات الخاصة (تقارير الأرباح، تعديل السعر", "Select the screens and actions, then click Save. The special permissions (profit reports, price change"
    LangAdd "فاتورة المشتريات الحالية لم تُحفظ (ستبقى محفوظة مؤقتًا لهذا الجهاز). هل تريد الخروج", "The current purchase invoice is not saved (it will stay held for this computer). Do you want to exit"
    LangAdd "البرنامج غير مفعّل على هذا الجهاز: أرسل رقم الجهاز للمبرمج واكتب الكود الذي يرسله", "The program is not activated on this computer: send the computer number to the developer and type the code he sends"
    LangAdd "الموجب مستحق للهيئة، والسالب رصيد مسترد. راجع الأرقام مع محاسبك قبل تقديم الإقرار", "A positive amount is due to the Authority, a negative one is a refundable balance. Review the figures with your accountant before filing the return"
    LangAdd "عمليات في فترة مقفلة تغيرت ولم يتغير قيدها (أعد فتح الفترة إن كان التغيير مقصودًا", "Transactions in a closed period that changed while their entry did not (reopen the period if the change is intended"
    LangAdd "مسير كل شهر من مبيعات المندوبين أو تحصيلاتهم، ثم ترحيل قيده؛ الصرف بسند صرف نقدية", "A run each month from the sales or collections of the sales reps, then posting its entry, payment with a cash payment voucher"
    LangAdd "التأمينات على الأساسي + السكن: السعودي بحصتي الموظف والمنشأة، وغيره بحصة المنشأة", "Social insurance on basic + housing: Saudis with the employee and employer shares, others with the employer share"
    LangAdd "لا توجد ضريبة مستحقة للسداد في هذا الإقرار (الرصيد الدائن يُرحَّل للإقرار التالي", "There is no VAT due for payment in this return (the credit balance is carried to the next return"
    LangAdd "لا يمكن الحفظ: توجد قيمة مكررة في حقل يجب أن يكون فريدًا (مثل الكود أو الباركود", "Cannot save: a value is repeated in a field that must be unique (such as the code or the barcode"
    LangAdd "مسير كل شهر: الرواتب والبدلات والإضافي والخصومات والتأمينات، ثم الترحيل والصرف", "A run each month: salaries, allowances, overtime, deductions and social insurance, then posting and payment"
    LangAdd "هذا حساب أساسي تستخدمه القيود الآلية: لا يتغير نوعه، ولا يتحول بين رئيسي وفرعي", "This is a system account used by the automatic entries: its type does not change, and it does not switch between main and sub"
    LangAdd "إعادة إنشاء أسطر المسير من مبيعات وتحصيلات الشهر؟ تضيع التعديلات المكتوبة فيه", "Rebuild the run lines from the sales and collections of the month? The changes typed in it are lost"
    LangAdd "لم يُنشأ قيد اليومية لهذا القيد بعد. اضغط «تحديث القيود» في شاشة قيود اليومية", "The journal entry of this entry is not created yet. Click Refresh entries in the Journal entries screen"
    LangAdd "اختر السند ثم الفاتورة التي يسددها. ما لا يُربط يسدد أقدم الفواتير استحقاقًا", "Choose the voucher, then the invoice it pays. What is not linked pays the oldest due invoices"
    LangAdd "الملصق والورق (بالمليمتر). مقاس ورق الطابعة نفسه يُضبط من إعدادات الطابعة في", "The label and the paper (in millimetres). The paper size of the printer itself is set in the printer settings of"
    LangAdd "إيداع وسحب، تسوية تحصيلات مدى بعمولتها، التحويل بين البنوك، والحركات الأخرى", "Deposit and withdrawal, settlement of Mada collections with their fee, transfer between banks, and other moves"
    LangAdd "الفاتورة الحالية لم تُحفظ (ستبقى محفوظة مؤقتًا لهذا الجهاز). هل تريد الخروج", "The current invoice is not saved (it will stay held for this computer). Do you want to exit"
    LangAdd "مبلغ شهري لكل حساب إيرادات أو مصروفات (ويمكن لكل مركز)، ثم المقارنة بالفعلي", "A monthly amount for each revenue or expense account (and for each center), then the comparison with the actual"
    LangAdd "اختر مجلد النسخ الاحتياطي (يفضل قرص آخر أو فلاشة أو مجلد متزامن مع السحابة", "Choose the backup folder (preferably another disk, a USB drive or a folder synced with the cloud"
    LangAdd "الإهلاك السابق للأصول الموجودة قبل البرنامج فقط (مصدر الشراء: رصيد افتتاحي", "Previous depreciation, only for assets owned before the program (purchase source: opening balance"
    LangAdd "ترحيل الجرد يحوّل الفروقات إلى حركات تسوية في المخزون ولا يمكن التراجع عنه", "Posting the count turns the differences into stock adjustment moves and cannot be undone"
    LangAdd "مجمل الربح ± فروقات المخزون - المصروفات. الرصيد الافتتاحي لا يدخل في الربح", "Gross profit +/- stock differences - expenses. The opening balance is not part of the profit"
    LangAdd "هذا الصنف لا يتابع المخزون (يُحضَّر عند الطلب)، فلا تُسجَّل له حركات مخزون", "This item does not track stock (prepared on order), so no stock moves are recorded for it"
    LangAdd "يناير,فبراير,مارس,أبريل,مايو,يونيو,يوليو,أغسطس,سبتمبر,أكتوبر,نوفمبر,ديسمبر", "January,February,March,April,May,June,July,August,September,October,November,December"
    LangAdd "سيُعاد إظهار أدوات Access ويُسمح بمفتاح Shift عند الفتح. هل تريد المتابعة", "The Access tools will be shown again and the Shift key allowed on opening. Do you want to continue"
    LangAdd "الإقرار معتمد: لا تتغير قيمه. ألغِ الاعتماد أولًا إن كان التغيير مقصودًا", "The return is approved: its values do not change. Cancel the approval first if the change is intended"
    LangAdd "هذا التقرير يعرض التكلفة والأرباح ويحتاج صلاحية «تقارير الأرباح والضريبة", "This report shows costs and profits and needs the permission Profit and VAT reports"
    LangAdd "إعادة إنشاء أسطر المسير من بيانات الموظفين؟ تضيع التعديلات المكتوبة فيه", "Rebuild the run lines from the employee data? The changes typed in it are lost"
    LangAdd "الإيجار والكهرباء والاشتراكات: يُنشأ المصروف تلقائيًا في تاريخ استحقاقه", "Rent, electricity and subscriptions: the expense is created automatically on its due date"
    LangAdd "المبيعات للمواطنين (الخدمات الصحية الخاصة والتعليم الأهلي والمسكن الأول", "Sales to citizens (private health care, private education and first home"
    LangAdd "لكل مندوب هدف واحد في الشهر؛ تقرير «أداء المندوبين» يقارن الفعلي بالهدف", "Each sales rep has one target a month, the report Sales rep performance compares the actual with the target"
    LangAdd "ألغِ العلامة للوجبات والمشروبات التي تُحضَّر عند الطلب: تُباع بلا رصيد", "Clear the mark for meals and drinks prepared on order: they are sold without stock"
    LangAdd "إلغاء تفعيل الجهاز المحدد؟ لن يعمل عليه البرنامج حتى يُفعَّل بكود جديد", "Deactivate the selected computer? The program will not run on it until it is activated with a new code"
    LangAdd "اكتب التاريخ والبيان، ثم سطرًا لكل حساب: المبلغ في المدين أو في الدائن", "Type the date and the description, then a line for each account: the amount in debit or in credit"
    LangAdd "البيانات داخل هذا الملف نفسه (غير مقسمة)، فلا يمكن استعادتها وهو مفتوح", "The data is inside this same file (not split), so it cannot be restored while it is open"
    LangAdd "قيمة وحدة واحدة من العملة بالريال؛ يُسجَّل لكل تاريخ في «أسعار العملات", "Value of one unit of the currency in SAR, recorded for each date in Exchange rates"
    LangAdd "الدخول الأول: اسم المستخدم admin بدون كلمة مرور، وسيُطلب منك تعيينها", "First login: user name admin with no password, and you will be asked to set one"
    LangAdd "تم تغيير كلمة مرور المبرمج. ادخل باسم developer وكلمة المرور الجديدة", "The developer password was changed. Log in as developer with the new password"
    LangAdd "تسجيل الشيك يسدد رصيد العميل أو المورد، ثم يُحصَّل في البنك أو يرتد", "Recording the cheque pays the balance of the customer or supplier, then it is collected in the bank or bounces"
    LangAdd "حساب الأصل حساب فرعي من الأصول غير المتداولة (12)، غير مجمع الإهلاك", "The asset account is a sub-account of the non-current assets (12), not the accumulated depreciation"
    LangAdd "سجل الأصول وقيد شرائها، والإهلاك بالقسط الثابت، والبيع أو الاستبعاد", "Asset register and purchase entry, straight-line depreciation, and sale or disposal"
    LangAdd "لم تُعيَّن كلمة مرور لهذا المستخدم بعد. اطلب من مدير النظام تعيينها", "No password is set for this user yet. Ask the system administrator to set one"
    LangAdd "يجب أن يكون البرنامج مغلقًا على كل الأجهزة الأخرى. هل تريد المتابعة", "The program must be closed on all other computers. Do you want to continue"
    LangAdd "ابدأ جردًا، أدخل الكمية الفعلية أو امسح الباركود، ثم رحّل الفروقات", "Start a count, enter the actual quantity or scan the barcode, then post the differences"
    LangAdd "الشاشات التي يفتحها كل مستخدم، والإضافة والتعديل والحذف في كل شاشة", "The screens each user opens, and add, edit and delete in each screen"
    LangAdd "بعدها لا يُضاف ولا يُعدَّل ولا يُحذف أي مستند بتاريخ حتى هذا اليوم", "After that, no document dated up to this day is added, edited or deleted"
    LangAdd "أرصدة المنتجات وحركاتها، والرصيد الافتتاحي والإضافة والخصم اليدوي", "Product balances and moves, opening balance and manual additions and deductions"
    LangAdd "إقرار غير محفوظ: الأرقام من المستندات الآن. احفظه مسودة أو اعتمده", "Unsaved return: the figures come from the documents now. Save it as a draft or approve it"
    LangAdd "تم حفظ نسب التأمينات. تُطبَّق على المسودات عند تعديلها أو ترحيلها", "The social insurance rates were saved. They apply to the drafts when they are edited or posted"
    LangAdd "يُنشأ المصروف في يوم الاستحقاق من كل فترة، بدءًا من تاريخ البداية", "The expense is created on the due day of each period, starting from the start date"
    LangAdd "الاستيرادات الخاضعة للنسبة الأساسية والمدفوعة ضريبتها في الجمارك", "Imports subject to the standard rate with VAT paid at customs"
    LangAdd "لا يوجد حساب مبرمج بعد. شغّل BuildSchema: يطلب كلمة مروره وينشئه", "There is no developer account yet. Run BuildSchema: it asks for its password and creates it"
    LangAdd "لا يُضاف ولا يُعدَّل ولا يُحذف فيها شيء إلا بعد إعادة فتح الفترة", "Nothing is added, edited or deleted in it until the period is reopened"
    LangAdd "للعودة لوضع التطوير: افتح الملف مع الضغط على مفتاح SHIFT ثم شغّل", "To go back to developer mode: open the file while holding the SHIFT key, then run"
    LangAdd "مركز الموظف من شاشة رواتب الموظفين؛ المستندات القديمة «غير موزعة", "The center of the employee from the Employee salaries screen, old documents are Not allocated"
    LangAdd "مقاس الملصق والورق والهوامش، وحجم الباركود، والنصوص أعلاه وأسفله", "Label and paper size, margins, barcode size, and the texts above and below it"
    LangAdd "هل تريد تعطيله بدلًا من ذلك؟ (يختفي من القوائم ويبقى في التقارير", "Do you want to deactivate it instead? (It disappears from the lists and stays in the reports"
    LangAdd "بعد الإقفال لا يُضاف ولا يُعدَّل ولا يُحذف أي مستند بتاريخ مقفل", "After closing, no document dated in a closed period is added, edited or deleted"
    LangAdd "توجد فاتورة مشتريات غير مكتملة من جلسة سابقة. هل تريد استكمالها", "There is an unfinished purchase invoice from a previous session. Do you want to continue it"
    LangAdd "هذا المصروف مسجل من سند صرف نقدية في الخزينة ولا يُعدَّل من هنا", "This expense is recorded from a cash payment voucher in the treasury and is not edited from here"
    LangAdd "إقفال السنة المالية (الإيرادات والمصروفات إلى الأرباح المحتجزة", "Fiscal year closing (revenue and expenses to retained earnings"
    LangAdd "الأصل الموجود قبل البرنامج بلا ضريبة مدخلات (سُجِّلت وقت شرائه", "An asset owned before the program has no input VAT (it was recorded when bought"
    LangAdd "الكافيه: أصناف هذه الفئة تظهر كإضافات للمشروب (حليب، شوت إضافي", "Cafe: the items of this category appear as extras of the drink (milk, extra shot"
    LangAdd "المشتريات الخاضعة للنسبة الأساسية (مع المصروفات بفاتورة ضريبية", "Purchases at the standard rate (with expenses with a tax invoice"
    LangAdd "قيد إهلاك كل شهر بالترتيب: مصروف الإهلاك ومجمع الإهلاك لكل أصل", "A depreciation entry for each month in order: depreciation expense and accumulated depreciation of each asset"
    LangAdd "لم يُدخل الرقم الضريبي، ولن تكون الفواتير فواتير ضريبية نظامية", "The VAT number is not entered, and the invoices will not be valid tax invoices"
    LangAdd "معامل كل عملة في تاريخ؛ المستند يأخذ آخر سعر في تاريخه أو قبله", "The rate of each currency on a date, a document takes the last rate on or before its date"
    LangAdd "يُفضَّل الجرد والمحل مغلق أو بعد آخر فاتورة، ثم الترحيل مباشرة", "Count preferably while the store is closed or after the last invoice, then post at once"
    LangAdd "الرصيد لا يُكتب يدويًا: يُحسب من المبيعات والسندات والمصروفات", "The balance is not typed by hand: it is calculated from sales, vouchers and expenses"
    LangAdd "تُحذف المسودة فقط. لإقرار معتمد استخدم «إلغاء الاعتماد» أولًا", "Only the draft is deleted. For an approved return use Cancel approval first"
    LangAdd "غير موجودة على هذا الجهاز. اخترها من جديد في إعدادات الملصقات", "does not exist on this computer. Choose it again in the label settings"
    LangAdd "لا تملك صلاحية تعديل أسعار البيع. امسح عمود «سعر البيع الجديد", "You do not have the permission to change sale prices. Clear the column New sale price"
    LangAdd "ضريبة القيمة المضافة المرحَّلة من الفترات السابقة (رصيد دائن", "VAT carried from previous periods (credit balance"
    LangAdd "قيد في فترة مقفلة: للعرض فقط. يمكن عمل قيد عكسي بتاريخ مفتوح", "An entry in a closed period: view only. A reversing entry can be made on an open date"
    LangAdd "للإيداع والسحب والتحويل وتسوية مدى اختر نوع الحركة الخاص بها", "For deposit, withdrawal, transfer and Mada settlement choose their own move type"
    LangAdd "مطابقة كشف البنك مع الدفاتر: علِّم العمليات الظاهرة في الكشف", "Match the bank statement with the books: mark the transactions shown on the statement"
    LangAdd "يوجد مسير مرحَّل بعده: خصومات السلف فيه تعتمد على هذا المسير", "There is a posted run after it: its advance deductions depend on this run"
    LangAdd "إلغاء اعتماد الإقرار؟ يُحذف قيد التسوية ويعود الإقرار مسودة", "Cancel the approval of the return? The settlement entry is deleted and the return becomes a draft"
    LangAdd "التحويل البنكي يُخصم من هذا البنك (البنك الافتراضي تلقائيًا", "A bank transfer is taken from this bank (the default bank automatically"
    LangAdd "المصروف النقدي يُخصم من هذا الصندوق (يُختار صندوقك تلقائيًا", "A cash expense is taken from this box (your box is chosen automatically"
    LangAdd "تأكد أن البرنامج مغلق على كل الأجهزة الأخرى ثم أعد المحاولة", "Make sure the program is closed on all other computers, then try again"
    LangAdd "حساب رئيسي أو معطّل: القيود على الحسابات الفرعية النشطة فقط", "A main or inactive account: entries go to active sub-accounts only"
    LangAdd "صورة الزر في شاشة اللمس: مسار كامل أو اسم ملف في مجلد الصور", "Button picture on the touch screen: a full path or a file name in the pictures folder"
    LangAdd "قائمة الدخل والميزانية العمومية من القيود، مع فترة المقارنة", "Income statement and balance sheet from the entries, with a comparison period"
    LangAdd "لا يوجد جرد. اختر التصنيف (أو اتركه للكل) ثم اضغط «جرد جديد", "No count. Choose the category (or leave it for all), then click New count"
    LangAdd "نسخة من ملف البيانات بالتاريخ والوقت، والاستعادة عند الحاجة", "A copy of the data file with the date and time, and restoring it when needed"
    LangAdd "ابحث بالاسم أو الكود أو الباركود أو رقم الفاتورة أو الجوال", "Search by name, code, barcode, invoice number or mobile"
    LangAdd "الحساب الرئيسي يجب أن يكون حسابًا تجميعيًا (لا يقبل القيود", "The main account must be a summary account (it takes no entries"
    LangAdd "عدّ النقدية وترحيلها للخزينة الرئيسية أو تسويتها مع المالك", "Count the cash and transfer it to the main treasury or settle it with the owner"
    LangAdd "من أضاف أو عدّل أو حذف، ومتى، ومن أي جهاز، والقيم قبل وبعد", "Who added, edited or deleted, when, from which computer, and the values before and after"
    LangAdd "أحد الأصناف في الفاتورة لم يعد موجودًا. احذفه من الفاتورة", "An item of the invoice no longer exists. Remove it from the invoice"
    LangAdd "أضف أصناف الفاتورة أو احفظ فاتورة أولًا، ثم اطبع الباركود", "Add the invoice items or save an invoice first, then print the barcodes"
    LangAdd "اختر البنك، واكتب تاريخ كشف البنك ورصيده، ثم «بدء التسوية", "Choose the bank, type the date and balance of the bank statement, then Start reconciliation"
    LangAdd "الرصيد الافتتاحي يُسجَّل مرة واحدة قبل أي حركة على المنتج", "The opening balance is recorded once, before any move on the product"
    LangAdd "المنتج موجود لكنه ليس ضمن هذا الجرد (تصنيف آخر أو غير نشط", "The product exists but is not part of this count (another category or inactive"
    LangAdd "عملية مطابقة تغيّر مبلغها في الدفاتر بعد المطابقة: راجعها", "A matched transaction whose amount changed in the books after matching: review it"
    LangAdd "قيد محفوظ: عدّل ثم احفظ، فيتحدث قيده في اليومية بنفس رقمه", "Saved entry: edit and save, and its journal entry is updated with the same number"
    LangAdd "يُحذف الشيك تحت التحصيل فقط: ألغِ تحصيله أو ارتداده أولًا", "Only a cheque under collection is deleted: cancel its collection or bounce first"
    LangAdd "إرجاع الشيك إلى «تحت التحصيل» وحذف قيد تحصيله أو ارتداده", "Return the cheque to Under collection and delete the entry of its collection or bounce"
    LangAdd "اكتب سبب الحركة في الملاحظات (مثال: تالف، هدية من المورد", "Type the reason for the move in the notes (example: damaged, gift from the supplier"
    LangAdd "المبلغ المدفوع (F8) - اتركه فارغًا إذا دفع المبلغ بالضبط", "Amount paid (F8) - leave it empty if the exact amount is paid"
    LangAdd "المتبقي من كل فاتورة آجلة حسب تأخيرها عن تاريخ الاستحقاق", "The remainder of each credit invoice by its delay after the due date"
    LangAdd "دور مدير النظام يملك كل الصلاحيات دائمًا ولا يمكن تقييده", "The system administrator role always has all the permissions and cannot be restricted"
    LangAdd "على الأصل قيود إهلاك: لا تتغير بياناته المالية ولا يُحذف", "The asset has depreciation entries: its financial data do not change and it is not deleted"
    LangAdd "عملات التعامل؛ عملة البرنامج الريال وكل المبالغ تُحفظ به", "Trading currencies, the program currency is the riyal and every amount is kept in it"
    LangAdd "لا يتغير رقم حساب محفوظ. أنشئ حسابًا جديدًا وعطّل القديم", "A saved account number does not change. Create a new account and deactivate the old one"
    LangAdd "لكل عملة سعر واحد في اليوم؛ عملة البرنامج لا تحتاج سعرًا", "Each currency has one rate a day, the program currency needs no rate"
    LangAdd "لم تُعيَّن كلمة مرور بعد، ولا يستطيع هذا المستخدم الدخول", "No password is set yet, and this user cannot log in"
    LangAdd "تأكد من الطابعة الافتراضية، ويمكنك إعادة الطباعة لاحقًا", "Check the default printer, you can reprint later"
End Sub

Private Sub D1_2()
    LangAdd "توجد فاتورة غير مكتملة من جلسة سابقة. هل تريد استكمالها", "There is an unfinished invoice from a previous session. Do you want to continue it"
    LangAdd "لا توجد بيانات لعرضها في هذا التقرير للاختيارات المحددة", "There is no data to show in this report for the choices made"
    LangAdd "لا يمكن الحذف أو التعديل لوجود عمليات مرتبطة بهذا السجل", "Cannot delete or edit because there are transactions linked to this record"
    LangAdd "أغلق البرنامج وانسخ ملف النسخة الاحتياطية مكانه يدويًا", "Close the program and copy the backup file in its place by hand"
    LangAdd "إجمالي ضريبة القيمة المضافة المستحقة عن الفترة الحالية", "Total VAT due for the current period"
    LangAdd "اختر شاشة واحدة على الأقل، أو ألغِ «صلاحيات شاشات خاصة", "Choose at least one screen, or clear Custom screen permissions"
    LangAdd "الضريبة والقيمة المتبقية والإهلاك السابق لا تكون سالبة", "VAT, residual value and previous depreciation are never negative"
    LangAdd "تعذرت النسخة الوقائية قبل الاستعادة، فلم تتم الاستعادة", "The safety copy before restoring failed, so nothing was restored"
    LangAdd "تم حفظ صلاحيات الشاشات. تسري من الدخول التالي للمستخدم", "The screen permissions were saved. They apply from the next login of the user"
    LangAdd "يعمل البرنامج على الأجهزة المفعّلة فقط بكود من المبرمج", "The program runs only on computers activated with a code from the developer"
    LangAdd "اختر سطر قيد من القائمة (سطر رصيد أول المدة ليس قيدًا", "Choose an entry line from the list (the opening balance line is not an entry"
    LangAdd "الحساب مقفل مؤقتًا بسبب محاولات دخول خاطئة حتى الساعة", "The account is locked for a while after wrong login attempts, until"
    LangAdd "امسح الباركود أو اختر الصنف بالاسم، وحدد عدد الملصقات", "Scan the barcode or choose the item by name, and set the number of labels"
    LangAdd "حركة الشيك مطابقة في تسوية بنكية: ألغِ مطابقتها أولًا", "The cheque move is matched in a bank reconciliation: unmatch it first"
    LangAdd "قيد لكل عملية مربوط بأصلها: افتح القيد أو أصل العملية", "One entry for each transaction, linked to its source: open the entry or the source transaction"
    LangAdd "الحساب الرئيسي الذي يتبعه (نوع الحساب يتبعه تلقائيًا", "The main account it belongs to (the account type follows it automatically"
    LangAdd "المبلغ المرحَّل يجب أن يكون بين صفر والنقدية الفعلية", "The transferred amount must be between zero and the actual cash"
    LangAdd "النقدية الموجودة في الصندوق عند بدء استخدام البرنامج", "The cash in the box when the program is first used"
    LangAdd "تم حفظ صلاحيات الدور. تسري عند الفتح التالي لكل شاشة", "The permissions of the role were saved. They apply the next time each screen opens"
    LangAdd "توجد تسوية جارية لهذا البنك: اعتمدها أو احذفها أولًا", "There is an open reconciliation for this bank: approve it or delete it first"
    LangAdd "ربط كل المبالغ غير المربوطة بأقدم الفواتير استحقاقًا", "Link all unlinked amounts to the oldest due invoices"
    LangAdd "قبض نقدية في صندوق، أو صرف منه، أو تحويل بين صندوقين", "Cash received in a box, paid from it, or transferred between two boxes"
    LangAdd "مناسب لطابعات 203 نقطة/بوصة، وكبّره إذا صعبت القراءة", "Suitable for 203 dpi printers, make it larger if it is hard to read"
    LangAdd "مندوبو المبيعات: عملاؤهم ونسبة عمولتهم ومركز تكلفتهم", "Sales reps: their customers, commission rate and cost center"
    LangAdd "نقدية مبيعات المستخدم وسنداته تدخل هذا الصندوق؛ فارغ", "The cash of the sales and vouchers of the user goes into this box, empty"
    LangAdd "أرصدة الخزينة الرئيسية وصناديق الكاشير وحركة كل يوم", "Balances of the main treasury and cashier boxes and the moves of each day"
    LangAdd "الفروع والأقسام: تُوزَّع عليها الإيرادات والمصروفات", "Branches and departments: revenue and expenses are allocated to them"
    LangAdd "القيمة المتبقية والإهلاك السابق لا يتجاوزان التكلفة", "The residual value and the previous depreciation do not exceed the cost"
    LangAdd "المدير المسؤول عن الخزينة: اختر له الخزينة الرئيسية", "The manager in charge of the treasury: choose the main treasury for him"
    LangAdd "تاريخ المصروف في المستقبل. هل تريد الحفظ على أي حال", "The expense date is in the future. Do you want to save anyway"
    LangAdd "لا تملك صلاحية الإضافة في شاشة ربط السداد بالفواتير", "You do not have the permission to add in the payment matching screen"
    LangAdd "لم تُعمل نسخة احتياطية اليوم. هل تريد عمل نسخة الآن", "No backup was made today. Do you want to make a backup now"
    LangAdd "هل تريد إلغاء الفاتورة الحالية والبدء بفاتورة جديدة", "Do you want to cancel the current invoice and start a new one"
    LangAdd "اختر فاتورة الشراء ثم حدد الكميات التي تعود للمورد", "Choose the purchase invoice, then set the quantities going back to the supplier"
    LangAdd "البيع الآجل يحتاج عميلًا مسجلًا. اختر العميل أولًا", "A credit sale needs a registered customer. Choose the customer first"
    LangAdd "التحويلات البنكية في الفواتير والسندات تُقيَّد فيه", "Bank transfers in invoices and vouchers are recorded in it"
    LangAdd "المبالغ لا تكون سالبة: اكتب المبلغ في الجانب الآخر", "Amounts are never negative: type the amount on the other side"
    LangAdd "تأكد أن المبرمج أصدره لرقم الجهاز الظاهر في الشاشة", "Make sure the developer issued it for the computer number shown on the screen"
    LangAdd "تمت الاستعادة. سيُغلق البرنامج الآن، افتحه من جديد", "Restored. The program will close now, open it again"
    LangAdd "توجد تعديلات غير محفوظة. هل تريد حفظها قبل الإغلاق", "There are unsaved changes. Do you want to save them before closing"
    LangAdd "صلاحيات شاشات خاصة بهذا المستخدم (بدل صلاحيات دوره", "Custom screen permissions for this user (instead of the permissions of his role"
    LangAdd "للتصحيح سجّل سند قبض نقدية بالمبلغ ثم سند صرف جديد", "To correct, record a cash receipt voucher with the amount, then a new payment voucher"
    LangAdd "يوجد طلب غير مكتمل من جلسة سابقة. هل تريد استكماله", "There is an unfinished order from a previous session. Do you want to continue it"
    LangAdd "أداء المندوبين: المبيعات والتحصيل والهدف والعمولة", "Sales rep performance: sales, collections, target and commission"
    LangAdd "أغلق الملف وافتحه من جديد ليظهر النظام بدون أدوات", "Close the file and open it again to start the system without the tools of"
    LangAdd "الاستيرادات الخاضعة للضريبة بآلية الاحتساب العكسي", "Imports subject to VAT under the reverse charge"
    LangAdd "الحركة مطابقة في تسوية بنكية: ألغِ مطابقتها أولًا", "The move is matched in a bank reconciliation: unmatch it first"
    LangAdd "القيد غير موجود (ربما حُذفت العملية). حدّث القيود", "The entry does not exist (the transaction may have been deleted). Refresh the entries"
    LangAdd "تُحذف التسوية الجارية فقط (أعد فتح المعتمدة أولًا", "Only the open reconciliation is deleted (reopen the approved one first"
    LangAdd "تُحفظ قيمه كما هي الآن، ويُنشأ قيد التسوية بتاريخ", "Its values are kept as they are now, and the settlement entry is created on"
    LangAdd "صُرف له جزء من هذه العمولات. ألغِ سند الصرف أولًا", "Part of these commissions was paid to him. Cancel the payment voucher first"
    LangAdd "لا تملك صلاحية الحذف في شاشة ربط السداد بالفواتير", "You do not have the permission to delete in the payment matching screen"
    LangAdd "لا يمكن حذف هذا السجل لأنه مستخدم في عمليات سابقة", "This record cannot be deleted because it is used in earlier transactions"
    LangAdd "مبيعات هذا المستخدم لعميل بلا مندوب تُنسب للمندوب", "The sales of this user to a customer without a sales rep go to the sales rep"
    LangAdd "يُعتمد الإقرار بعد انتهاء فترته: اختر تاريخًا بعد", "The return is approved after its period ends: choose a date after"
    LangAdd "الصغير؛ سعر الوسط أو الكبير يجعل للمشروب أحجامًا", "small, a medium or large price gives the drink sizes"
    LangAdd "الهدف الشهري لصافي مبيعات كل مندوب (بدون الضريبة", "The monthly target for the net sales of each sales rep (without VAT"
    LangAdd "غير متاح في ملف ACCDE. غيّر كلمة المرور من نسختك", "Not available in an ACCDE file. Change the password from your copy"
    LangAdd "لتصحيح الكمية الآن استخدم الجرد أو الإضافة/الخصم", "To correct the quantity now use the stock count or the addition/deduction"
    LangAdd "لهذا الحساب حسابات تابعة. احذفها أو انقلها أولًا", "This account has sub-accounts. Delete them or move them first"
    LangAdd "مدير النظام يفتح كل الشاشات بكل الصلاحيات دائمًا", "The system administrator always opens every screen with every permission"
    LangAdd "إذا لم تكن عليه قيود ألغِ «حساب فرعي» فيه أولًا", "If it has no entries, clear Sub-account on it first"
    LangAdd "إلغاء الجرد الحالي؟ لن تتغير أي كمية في المخزون", "Cancel the current count? No stock quantity will change"
    LangAdd "اكتب المبلغ مدينًا أو دائنًا في كل سطر فيه حساب", "Type the amount as debit or credit in every line with an account"
    LangAdd "الراتب والبدلات والتأمينات وقسط السلفة لكل موظف", "Salary, allowances, social insurance and advance installment of each employee"
    LangAdd "الملف المختار ليس نسخة صالحة من بيانات البرنامج", "The chosen file is not a valid backup of the program data"
    LangAdd "تُحسب الفروقات على الكميات الحالية لحظة الترحيل", "The differences are calculated on the current quantities at the time of posting"
    LangAdd "حسابات لا يمكن وضعها في الشجرة (حلقة أو أكثر من", "Accounts that cannot be placed in the tree (a loop or more than"
    LangAdd "لطابعة الملصقات، وأكثر لورق A4 فيه أعمدة ملصقات", "for a label printer, and more for A4 paper with columns of labels"
    LangAdd "أولًا: رصيده المرحَّل قد يعتمد على هذا الإقرار", "first: its carried balance may depend on this return"
    LangAdd "أُنشئت الموازنة بسطر لكل حساب إيرادات ومصروفات", "The budget was created with a line for each revenue and expense account"
    LangAdd "إنشاء كل المصروفات المتكررة المستحقة حتى اليوم", "Create all recurring expenses due up to today"
    LangAdd "اختر التقرير ثم حدد الفترة أو العميل أو المنتج", "Choose the report, then set the period, the customer or the product"
    LangAdd "اكتب الرصيد الظاهر في كشف البنك في هذا التاريخ", "Type the balance shown on the bank statement on this date"
    LangAdd "الخصم...) تبقى من دور المستخدم في شاشة الأدوار", "discount...) come from the role of the user in the Roles screen"
    LangAdd "الصرف مطابق في تسوية بنكية: ألغِ مطابقته أولًا", "The payment is matched in a bank reconciliation: unmatch it first"
    LangAdd "الكمية المرتجعة للمورد أكبر من الكمية المشتراة", "The quantity returned to the supplier is more than the quantity bought"
    LangAdd "الكمية تتغير فقط من المشتريات والمبيعات والجرد", "The quantity changes only through purchases, sales and stock counts"
    LangAdd "تأكيد كلمة المرور لا يطابق كلمة المرور الجديدة", "The password confirmation does not match the new password"
    LangAdd "تغيرت ضريبة مستندات الفترة بعد الاعتماد بمقدار", "The VAT of the documents of the period changed after approval by"
    LangAdd "في القيد أصل مستبعد بعده: ألغِ الاستبعاد أولًا", "The entry has an asset disposed after it: cancel the disposal first"
    LangAdd "لا تملك صلاحية الإضافة في شاشة التسوية البنكية", "You do not have the permission to add in the bank reconciliation screen"
    LangAdd "لا تملك صلاحية الإضافة في شاشة الحركات البنكية", "You do not have the permission to add in the bank transactions screen"
    LangAdd "لهذا الحساب حسابات تابعة، فيبقى حسابًا رئيسيًا", "This account has sub-accounts, so it stays a main account"
    LangAdd "نقر مزدوج على حساب يفتح كشف حسابه للفترة نفسها", "Double-click an account to open its statement for the same period"
    LangAdd "اختر العمليات الظاهرة في كشف البنك ثم «مطابقة", "Choose the transactions shown on the bank statement, then Match"
    LangAdd "اختر الفاتورة الأصلية ثم حدد الكميات المرتجعة", "Choose the original invoice, then set the returned quantities"
    LangAdd "الباقي من الفاتورة بعد ما رُبط بها ومرتجعاتها", "What remains of the invoice after what was linked to it and its returns"
    LangAdd "التقارير المحاسبية تحتاج صلاحية «قيود اليومية", "The accounting reports need the permission Journal entries"
    LangAdd "المرتجعات على هذه الفاتورة (نقر مزدوج للطباعة", "Returns on this invoice (double-click to print"
    LangAdd "بعد الحفظ عيّن كلمة المرور من زر «كلمة المرور", "After saving, set the password with the button Password"
    LangAdd "رصيد الحساب في البنك عند بدء استخدام البرنامج", "The account balance in the bank when the program is first used"
    LangAdd "غير مقفلة: صافي الربح (الخسارة) حتى 31 ديسمبر", "Not closed: net profit (loss) up to 31 December"
    LangAdd "لا تملك هذه الصلاحية في شاشة عمولات المندوبين", "You do not have this permission in the sales rep commissions screen"
    LangAdd "أدخل تاريخ اعتماد الإقرار (يوم تقديمه للهيئة", "Enter the approval date of the return (the day it is filed with the Authority"
    LangAdd "أضف صنفًا واحدًا على الأقل إلى قائمة الطباعة", "Add at least one item to the print list"
    LangAdd "عمليات الدفاتر غير المطابقة (حتى تاريخ الكشف", "Book transactions not matched (up to the statement date"
    LangAdd "كلمة المرور لا يجوز أن تكون نفس اسم المستخدم", "The password may not be the same as the user name"
    LangAdd "لا مبيعات ولا تحصيلات للمندوبين في هذا الشهر", "No sales and no collections by the sales reps in this month"
    LangAdd "لا يتبع الحساب حسابًا من الحسابات التابعة له", "An account cannot belong to one of its own sub-accounts"
    LangAdd "لتصفير صنف غير موجود اكتب 0 في كميته الفعلية", "To set a missing item to zero type 0 as its actual quantity"
    LangAdd "اتركه فارغًا للطباعة على الطابعة الافتراضية", "Leave it empty to print on the default printer"
    LangAdd "اختر المشروب: الحجم والإضافات تظهر تلقائيًا", "Choose the drink: the size and extras appear automatically"
    LangAdd "السعر والخصم لا يمكن أن يكونا سالبين (السطر", "The price and the discount cannot be negative (line"
    LangAdd "تاريخ النهاية يجب أن يكون بعد تاريخ البداية", "The end date must be after the start date"
    LangAdd "تمت النسخة الاحتياطية بنجاح وتم التحقق منها", "The backup was made successfully and checked"
    LangAdd "تنبيه: سعر البيع الجديد أقل من تكلفة الشراء", "Warning: the new sale price is below the purchase cost"
    LangAdd "سبب الإرجاع مطلوب (إلزامي في الإشعار الدائن", "The return reason is required (mandatory on the credit note"
    LangAdd "عمليات غير متوازنة لم يُنشأ لها قيد (راجعها", "Unbalanced transactions with no entry created (review them"
    LangAdd "عميل المرتجع يختلف عن عميل الفاتورة الأصلية", "The customer of the return differs from the customer of the original invoice"
    LangAdd "مقفلة: صافي الربح المرحَّل للأرباح المحتجزة", "Closed: net profit carried to retained earnings"
    LangAdd "منتج سطر المرتجع يختلف عن منتج السطر الأصلي", "The product of the return line differs from the product of the original line"
    LangAdd "إجمالي فاتورة الشراء لا يساوي مجموع أسطرها", "The purchase invoice total does not equal the sum of its lines"
    LangAdd "إيقاف البيع الآجل لعميل متأخر أكثر من (يوم", "Stop credit sales to a customer late more than (days"
    LangAdd "اسم المستخدم 3 أحرف على الأقل وبدون مسافات", "The user name has at least 3 characters and no spaces"
    LangAdd "الرصيد المرحَّل (الخانة 15) لا يكون سالبًا", "The carried balance (box 15) is never negative"
    LangAdd "بياناتك الحالية لم تتغير، ونسختها الوقائية", "Your current data did not change, and its safety copy"
    LangAdd "تاريخ الفاتورة لا يمكن أن يكون في المستقبل", "The invoice date cannot be in the future"
    LangAdd "كلمة مرور مؤقتة: سيُطلب تغييرها عند الدخول", "Temporary password: the user is asked to change it at login"
    LangAdd "مشكلة في البيانات - راجع تقرير فحص السلامة", "A data problem - check the integrity report"
End Sub

Private Sub D1_3()
    LangAdd "يوجد حقل مطلوب فارغ. أكمل البيانات ثم احفظ", "A required field is empty. Complete the data, then save"
    LangAdd "يُسجَّل إهلاك الشهر في آخر يوم منه أو بعده", "The depreciation of a month is recorded on its last day or later"
    LangAdd "إجمالي فاتورة البيع لا يساوي مجموع أسطرها", "The sales invoice total does not equal the sum of its lines"
    LangAdd "اختر الحساب الرئيسي الذي يتبعه هذا الحساب", "Choose the main account this account belongs to"
    LangAdd "اكتب المبالغ، أو انسخها من فعلي سنة سابقة", "Type the amounts, or copy them from the actuals of a previous year"
    LangAdd "اكتب المبلغ المستلم أو اختر مبلغًا جاهزًا", "Type the amount received or choose a ready amount"
    LangAdd "اكتب ثمن البيع، أو اختر «استبعاد بدون ثمن", "Type the sale price, or choose Disposal without a price"
    LangAdd "السطر يكون مدينًا أو دائنًا، وليس الاثنين", "A line is debit or credit, not both"
    LangAdd "القيد سطران على الأقل: طرف مدين وطرف دائن", "An entry has at least two lines: a debit side and a credit side"
    LangAdd "المبلغ أكبر من تحصيلات مدى التي لم تُسوَّ", "The amount is more than the Mada collections not yet settled"
    LangAdd "الموازنة لحسابات الإيرادات والمصروفات فقط", "The budget is for revenue and expense accounts only"
    LangAdd "بأكثر من المتوفر يحتاج موافقة مدير النظام", "more than the available quantity needs the approval of the system administrator"
    LangAdd "تم ضبط وضع التطوير: كل أدوات Access ظاهرة", "Developer mode is set: all the Access tools are shown"
    LangAdd "شجرة الحسابات: الحسابات الرئيسية والفرعية", "Account tree: main and sub-accounts"
    LangAdd "لا تملك هذه الصلاحية في شاشة مسير الرواتب", "You do not have this permission in the payroll screen"
    LangAdd "لا توجد مبالغ غير مربوطة أو فواتير مفتوحة", "There are no unlinked amounts or open invoices"
    LangAdd "لا توجد منتجات نشطة للجرد في هذا الاختيار", "There are no active products to count in this choice"
    LangAdd "للتصحيح احذف قيود الإهلاك بدءًا من الأخير", "To correct, delete the depreciation entries starting from the last"
    LangAdd "لم يتم العثور على منتج بالباركود أو الكود", "No product was found with the barcode or the code"
    LangAdd "منتج وصلت كميته إلى حد إعادة الطلب أو أقل", "products have reached the reorder level or less"
    LangAdd "هل تريد عرض تقرير المنتجات منخفضة المخزون", "Do you want to show the low-stock products report"
    LangAdd "يغيّرها المستخدم عند أول دخول (كلمة مؤقتة", "The user changes it at the first login (temporary password"
    LangAdd "أدخل النقدية الفعلية الموجودة في الصندوق", "Enter the actual cash in the box"
    LangAdd "احذف قيود الإهلاك من شهر الاستبعاد أولًا", "Delete the depreciation entries from the month of disposal first"
    LangAdd "اختر حساب البنك الذي سُدِّدت منه الضريبة", "Choose the bank account the tax was paid from"
    LangAdd "اختر سطرًا في الجدول واكتب المبلغ السنوي", "Choose a line in the table and type the yearly amount"
    LangAdd "الدائن، ويُرحَّل لقيود اليومية عند الحفظ", "credit, and is posted to the journal entries when saved"
    LangAdd "المشتريات الخاضعة للضريبة (بعد المرتجعات", "Taxable purchases (after returns"
    LangAdd "دور مدير النظام يملك كل الصلاحيات دائمًا", "The system administrator role always has all the permissions"
    LangAdd "سطر المرتجع من فاتورة غير فاتورة المرتجع", "A return line from an invoice other than the invoice of the return"
    LangAdd "على هذا الحساب قيود، فيبقى حسابًا فرعيًا", "This account has entries, so it stays a sub-account"
    LangAdd "كلمتا المرور غير متطابقتين. لم يتغير شيء", "The two passwords do not match. Nothing changed"
    LangAdd "لا يمكنك تعطيل حسابك وأنت مسجل الدخول به", "You cannot deactivate your own account while logged in with it"
    LangAdd "هذه الشاشة ستكون متاحة بعد تنفيذ المرحلة", "This screen will be available after phase"
    LangAdd "يجب أن يبقى مدير نظام نشط واحد على الأقل", "At least one active system administrator must remain"
    LangAdd "يُقفل ما قبل اليوم فقط: اختر تاريخًا قبل", "Only the days before today are closed: choose a date before"
    LangAdd "اختر أين استُلم ثمن البيع (بنك أو صندوق", "Choose where the sale price was received (bank or box"
    LangAdd "المبيعات الخاضعة للضريبة (بعد المرتجعات", "Taxable sales (after returns"
    LangAdd "المبيعات المحلية الخاضعة للنسبة الصفرية", "Domestic zero-rated sales"
    LangAdd "الميزانية العمومية (قائمة المركز المالي", "Balance sheet (statement of financial position"
    LangAdd "تُقفل السنة بعد انتهائها (بعد 31 ديسمبر", "The year is closed after it ends (after 31 December"
    LangAdd "حدد الكمية المرتجعة لصنف واحد على الأقل", "Set the returned quantity of at least one item"
    LangAdd "راجع التاريخ والأسطر ثم اضغط «حفظ القيد", "Check the date and the lines, then click Save entry"
    LangAdd "سعر البيع الجديد لا يمكن أن يكون سالبًا", "The new sale price cannot be negative"
    LangAdd "عدّل الإضافي والخصومات ثم «ترحيل المسير", "Edit the overtime and deductions, then Post the run"
    LangAdd "كلمة البحث (اسم، كود، باركود، رقم، جوال", "Search text (name, code, barcode, number, mobile"
    LangAdd "لا توجد مصروفات متكررة مستحقة حتى اليوم", "There are no recurring expenses due up to today"
    LangAdd "يجب أن يفعّله مدير النظام قبل الاستخدام", "The system administrator must activate it before use"
    LangAdd "أحرف على الأقل، ولا تساوي اسم المستخدم", "characters at least, and not equal to the user name"
    LangAdd "أدخل النقدية الموجودة فعلًا في الصندوق", "Enter the cash actually in the box"
    LangAdd "أضفه في تصحيحات الإقرار التالي (الخانة", "Add it to the corrections of the next return (box"
    LangAdd "أو اترك التاريخ فارغًا لفتح كل الفترات", "or leave the date empty to open all periods"
    LangAdd "الإقرارات المحفوظة (اختر إقرارًا لعرضه", "Saved returns (choose a return to show it"
    LangAdd "الجرد غير موجود أو تم ترحيله أو إلغاؤه", "The count does not exist or was posted or cancelled"
    LangAdd "الكمية المرتجعة أكبر من الكمية المباعة", "The returned quantity is more than the quantity sold"
    LangAdd "الكمية المرتجعة أكبر من المتاح للإرجاع", "The returned quantity is more than what can be returned"
    LangAdd "المبلغ أكبر من عمولات المندوب المستحقة", "The amount is more than the commissions payable to the sales rep"
    LangAdd "بيانات المحل الضريبية وإعدادات التشغيل", "Tax data of the store and operating settings"
    LangAdd "ترتيب الزر في شاشة اللمس (الأصغر أولًا", "Order of the button on the touch screen (smallest first"
    LangAdd "ديون العملاء ÷ المبيعات الآجلة اليومية", "Customer receivables / daily credit sales"
    LangAdd "سطر لا ينتمي إلى فاتورة الشراء الأصلية", "A line that does not belong to the original purchase invoice"
    LangAdd "سعودي (التأمينات بحصتي الموظف والمنشأة", "Saudi (social insurance with the employee and employer shares"
    LangAdd "في الأرباح المحتجزة، وتُقفل السنة كلها", "in retained earnings, and the whole year is closed"
    LangAdd "لا تملك صلاحية تسجيل مرتجعات المشتريات", "You do not have the permission to record purchase returns"
    LangAdd "أدخل تاريخ السداد والمبلغ وحساب البنك", "Enter the payment date, the amount and the bank account"
    LangAdd "اختر الحجم والإضافات، ثم «إضافة للطلب", "Choose the size and extras, then Add to order"
    LangAdd "اسم المستخدم أو كلمة المرور غير صحيحة", "The user name or the password is wrong"
    LangAdd "الكمية المسجلة لا تطابق حركات المخزون", "The recorded quantity does not match the stock moves"
    LangAdd "الكمية يجب أن تكون أكبر من صفر (السطر", "The quantity must be greater than zero (line"
    LangAdd "المقارنة داخل سنة واحدة (موازنة السنة", "Comparison within one year (the budget of the year"
    LangAdd "تاريخ السداد قبل تاريخ اعتماد الإقرار", "The payment date is before the approval date of the return"
    LangAdd "تُحذف المسودة فقط: ألغِ الترحيل أولًا", "Only the draft is deleted: unpost it first"
    LangAdd "حركة الخزينة اليومية (أول اليوم وآخره", "Daily treasury moves (start and end of the day"
    LangAdd "رقم جديد لا يتكرر؛ لا يتغير بعد الحفظ", "A new number that is not repeated, it does not change after saving"
    LangAdd "سجل التدقيق يحتاج صلاحية «سجل التدقيق", "The audit trail needs the permission Audit trail"
    LangAdd "عرض فقط - التصحيح يكون بمرتجع مشتريات", "View only - a correction is made with a purchase return"
End Sub
