Attribute VB_Name = "modLangData4"
'==============================================================================
' modLangData4  -  Retail Store Management System: part 4 of the Arabic ->
' English dictionary of the interface (modLang). GENERATED FILE - do not edit.
' Source: tools/i18n_en.py  ->  python3 tools/generate.py
'==============================================================================
Option Compare Database
Option Explicit

Public Sub LangData4()
    D4_1
    D4_2
    D4_3
    D4_4
    D4_5
    D4_6
    D4_7
    D4_8
    D4_9
End Sub

Private Sub D4_1()
    LangAdd "طباعة الباركود", "Print barcodes"
    LangAdd "طباعة المقارنة", "Print the comparison"
    LangAdd "طريقة الاستلام", "Receipt method"
    LangAdd "عجز في الصندوق", "Shortage in the box"
    LangAdd "عرض الملصق (مم", "Label width (mm"
    LangAdd "عرض في اليومية", "Show in the journal"
    LangAdd "عميل عليه رصيد", "Customer with a balance"
    LangAdd "فاتورة مشتريات", "Purchase invoice"
    LangAdd "قيد مُحدَّث، و", "updated entries, and"
    LangAdd "لا تملك صلاحية", "You do not have the permission"
    LangAdd "لا توجد حسابات", "There are no accounts"
    LangAdd "ما ينطبق عليها", "what applies to them"
    LangAdd "مثال: 2% تُكتب", "Example: 2% is typed"
    LangAdd "مستحق للموردين", "Due to suppliers"
    LangAdd "مصروف (سند صرف", "Expense (payment voucher"
    LangAdd "مقبول مع تحذير", "Accepted with a warning"
    LangAdd "من مسار النظام", "from the system path"
    LangAdd "منخفضة المخزون", "Low stock"
    LangAdd "موظف   الرواتب", "employees   Salaries"
    LangAdd "ميزان المراجعة", "Trial balance"
    LangAdd "نوع مصروف جديد", "New expense type"
    LangAdd "وارد آخر للبنك", "Other incoming to the bank"
    LangAdd "يحسبه البرنامج", "Calculated by the program"
    LangAdd "يوجد جرد مفتوح", "There is an open count"
    LangAdd "يوجد مسير لشهر", "A run for the month"
    LangAdd "يُصرف من صندوق", "Paid from box"
    LangAdd "يُقبض في صندوق", "Received in box"
    LangAdd "أرصدة العملاء", "Customer balances"
    LangAdd "أسطر الفاتورة", "Invoice lines"
    LangAdd "أسطر الملصقات", "Label lines"
    LangAdd "أسطر الموازنة", "Budget lines"
    LangAdd "أسعار العملات", "Exchange rates"
    LangAdd "أقصى نسبة خصم", "Maximum discount rate"
    LangAdd "أقل من المبلغ", "less than the amount"
    LangAdd "أكبر من قيمته", "more than its value"
    LangAdd "إجمالي الأصول", "Total assets"
    LangAdd "إجمالي الخارج", "Total out"
    LangAdd "إجمالي الخصوم", "Total liabilities"
    LangAdd "إجمالي الدائن", "Total credit"
    LangAdd "إجمالي الداخل", "Total in"
    LangAdd "إجمالي المدين", "Total debit"
    LangAdd "إرسال المختار", "Send selected"
    LangAdd "إعادة الإنشاء", "Rebuild"
    LangAdd "إعادة فتح سنة", "Reopen a year"
    LangAdd "إقفال الفترات", "Period closing"
    LangAdd "إلغاء الترحيل", "Unpost"
    LangAdd "إلغاء المستند", "Cancel document"
    LangAdd "اختر المستخدم", "Choose the user"
    LangAdd "اقتراح للفارغ", "Suggest for empty"
    LangAdd "الباقي للعميل", "Change for the customer"
    LangAdd "البحث المتقدم", "Advanced search"
    LangAdd "البنك غير نشط", "The bank is not active"
    LangAdd "الجهة المصدرة", "Issuer"
    LangAdd "الحساب الدائن", "Credit account"
    LangAdd "الرصيد الحالي", "Current balance"
    LangAdd "الرصيد الموجب", "A positive balance"
    LangAdd "الرقم الإضافي", "Additional number"
    LangAdd "الرقم الضريبي", "VAT number"
    LangAdd "الرمز البريدي", "Postal code"
    LangAdd "الرمز المختصر", "Symbol"
    LangAdd "السجل التجاري", "Commercial registration"
    LangAdd "السنة الماضية", "Last year"
    LangAdd "الشخص المسؤول", "Contact person"
    LangAdd "العملية (فارغ", "Transaction (empty"
    LangAdd "الفرع الرئيسي", "Main branch"
    LangAdd "القائم بالجرد", "Counted by"
    LangAdd "المبلغ المسدد", "Amount paid"
    LangAdd "المسترد نقدًا", "Refunded in cash"
    LangAdd "المفتاح الخاص", "Private key"
    LangAdd "بداية الإهلاك", "Depreciation start"
    LangAdd "بصمة الفاتورة", "Invoice hash"
    LangAdd "بيئة المحاكاة", "Simulation environment"
    LangAdd "بيع / استبعاد", "Sale / disposal"
    LangAdd "تاريخ التعيين", "Hire date"
    LangAdd "تاريخ التفعيل", "Activation date"
    LangAdd "تاريخ العملية", "Transaction date"
    LangAdd "تاريخ المصروف", "Expense date"
    LangAdd "تحديث القائمة", "Refresh list"
    LangAdd "تسجيل الشيكات", "Cheque register"
    LangAdd "تصحيحات سابقة", "Earlier corrections"
    LangAdd "تعذّر الإرسال", "Could not send"
    LangAdd "تفعيل الإرسال", "Enable sending"
    LangAdd "تقرير المخزون", "Stock report"
    LangAdd "تقرير النواقص", "Shortage report"
    LangAdd "تم حفظ الحركة", "The move was saved"
    LangAdd "تُدفع بالكامل", "Paid in full"
    LangAdd "ثمن بيع الأصل", "Sale price of the asset"
    LangAdd "حفظ الصلاحيات", "Save the permissions"
    LangAdd "دليل الحسابات", "Chart of accounts"
    LangAdd "ربح بيع الأصل", "Gain on sale of the asset"
    LangAdd "ربط بالفاتورة", "Link to the invoice"
    LangAdd "سند صرف عمولة", "Commission payment voucher"
    LangAdd "سند صرف لمورد", "Supplier payment voucher"
    LangAdd "سند صرف نقدية", "Cash payment voucher"
    LangAdd "سند قبض نقدية", "Cash receipt voucher"
    LangAdd "شجرة الحسابات", "Account tree"
    LangAdd "شراء أصل ثابت", "Purchase of a fixed asset"
    LangAdd "شهادة تجريبية", "Test certificate"
    LangAdd "صافي المبيعات", "Net sales"
    LangAdd "صلاحيات الدور", "Role permissions"
    LangAdd "صندوق النقدية", "Cash box"
    LangAdd "صُرف من صندوق", "Paid from box"
    LangAdd "ضريبة العمولة", "Fee VAT"
    LangAdd "طباعة التقرير", "Print report"
    LangAdd "طباعة القائمة", "Print the list"
    LangAdd "طباعة اليومية", "Print the journal"
    LangAdd "عدد المحاولات", "Number of attempts"
    LangAdd "عملة البرنامج", "Program currency"
    LangAdd "عمولات مستحقة", "Commissions payable"
    LangAdd "عنوان التوصيل", "Delivery address"
    LangAdd "فات استحقاقها", "Overdue"
    LangAdd "فاتورة المورد", "Supplier invoice"
    LangAdd "فاتورة ضريبية", "Tax invoice"
    LangAdd "فاتورة متأخرة", "has an invoice late by"
    LangAdd "فتح قيد محفوظ", "Open a saved entry"
    LangAdd "فترة المقارنة", "Comparison period"
    LangAdd "فحوص الامتثال", "Compliance checks"
    LangAdd "فواتير الشراء", "Purchase invoices"
    LangAdd "قيد يومية رقم", "Journal entry number"
    LangAdd "كشف حساب عميل", "Customer statement"
End Sub

Private Sub D4_2()
    LangAdd "كشف حساب مورد", "Supplier statement"
    LangAdd "لا توجد نواقص", "There are no shortages"
    LangAdd "لا يوجد صندوق", "No box"
    LangAdd "متوسط التكلفة", "Average cost"
    LangAdd "مثال: الدولار", "Example: the dollar"
    LangAdd "مراكز التكلفة", "Cost centers"
    LangAdd "مرتجع مشتريات", "Purchase return"
    LangAdd "مرحَّل ومصروف", "Posted and paid"
    LangAdd "مركز التقارير", "Report center"
    LangAdd "مسودة الإقرار", "Draft return"
    LangAdd "مصروف بإجمالي", "expenses totalling"
    LangAdd "مصروفات الشهر", "Expenses of the month"
    LangAdd "مطابقة المحدد", "Match the selected"
    LangAdd "معامل التحويل", "Exchange rate"
    LangAdd "مقفلة حتى يوم", "Closed up to the day"
    LangAdd "ملء من الفعلي", "Fill from actuals"
    LangAdd "نسخة احتياطية", "Backup"
    LangAdd "ونسبة الضريبة", "and the VAT rate"
    LangAdd "يتابع المخزون", "Tracks stock"
    LangAdd "يوم الاستحقاق", "Due day"
    LangAdd "آخر سعر شراء", "Last purchase price"
    LangAdd "آخر شهر مسجل", "Last recorded month"
    LangAdd "آيبان الموظف", "Employee IBAN"
    LangAdd "أساس العمولة", "Commission base"
    LangAdd "أسطر المرتجع", "Return lines"
    LangAdd "أعمار الديون", "Aging"
    LangAdd "أكبر من الحد", "more than the limit"
    LangAdd "أمين الصندوق", "Cashier"
    LangAdd "أيام التأخير", "Days late"
    LangAdd "إلغاء الحالة", "Cancel the status"
    LangAdd "إلغاء السداد", "Cancel the payment"
    LangAdd "إنشاء موازنة", "Create a budget"
    LangAdd "إيرادات أخرى", "Other revenue"
    LangAdd "اختر الصندوق", "Choose the box"
    LangAdd "اختر المندوب", "Choose the sales rep"
    LangAdd "استرداد نقدي", "Cash refund"
    LangAdd "اسم المستخدم", "User name"
    LangAdd "الجدول (فارغ", "Table (empty"
    LangAdd "الربط المسجل", "Recorded link"
    LangAdd "الربع الماضي", "Last quarter"
    LangAdd "الرصيد بعدها", "Balance after it"
    LangAdd "السعر للعميل", "Price for the customer"
    LangAdd "الشهر الماضي", "Last month"
    LangAdd "الفروقات فقط", "Differences only"
    LangAdd "القسط الشهري", "Monthly installment"
    LangAdd "المرحَّل إلى", "Carried to"
    LangAdd "المقارنة: في", "Comparison: on"
    LangAdd "المقارنة: من", "Comparison: from"
    LangAdd "اليوم التالي", "Next day"
    LangAdd "اليوم السابق", "Previous day"
    LangAdd "باقي الأسماء", "Other names"
    LangAdd "بدء جرد جديد", "Start a new count"
    LangAdd "بدون الضريبة", "Without VAT"
    LangAdd "بيع أصل ثابت", "Sale of a fixed asset"
    LangAdd "تاريخ السداد", "Payment date"
    LangAdd "تاريخ الشراء", "Purchase date"
    LangAdd "تجربة الدخول", "Test login"
    LangAdd "تحديث الحالة", "Refresh status"
    LangAdd "تحديث القيود", "Refresh entries"
    LangAdd "ترحيل المسير", "Post the run"
    LangAdd "تسجيل الخروج", "Log out"
    LangAdd "تسجيل الدخول", "Log in"
    LangAdd "تسجيل السداد", "Record the payment"
    LangAdd "تعذر التصدير", "Export failed"
    LangAdd "تغيير المجلد", "Change the folder"
    LangAdd "تكلفة الوحدة", "Unit cost"
    LangAdd "تم حذف السطر", "The line was deleted"
    LangAdd "تم حذف الشيك", "The cheque was deleted"
    LangAdd "تم حذف القيد", "The entry was deleted"
    LangAdd "تم حفظ القيد", "The entry was saved"
    LangAdd "جوال التوصيل", "Delivery mobile"
    LangAdd "حالة الإرسال", "Sending status"
    LangAdd "حالة التسوية", "Reconciliation status"
    LangAdd "حذف الموازنة", "Delete the budget"
    LangAdd "خاضع للضريبة", "Taxable"
    LangAdd "خزينة رئيسية", "Main treasury"
    LangAdd "دفتر الأستاذ", "General ledger"
    LangAdd "دولة التشغيل", "Operating country"
    LangAdd "ديون العملاء", "Customer receivables"
    LangAdd "رئيسي / فرعي", "Main / sub"
    LangAdd "رصيد افتتاحي", "Opening balance"
    LangAdd "رصيد البداية", "Starting balance"
    LangAdd "رصيد الصندوق", "Box balance"
    LangAdd "رقم الباركود", "Barcode number"
    LangAdd "رقم الفاتورة", "Invoice number"
    LangAdd "رُفض الإيصال", "The receipt was rejected"
    LangAdd "رُفض المستند", "The document was rejected"
    LangAdd "سحب من البنك", "Withdrawal from the bank"
    LangAdd "سعر بيع جديد", "New sale price"
    LangAdd "شامل الضريبة", "Including VAT"
    LangAdd "صافي الرواتب", "Net salaries"
    LangAdd "صنف    العجز", "Item    Shortage"
    LangAdd "صورة التصنيف", "Category picture"
    LangAdd "طباعة الفترة", "Print the period"
    LangAdd "طباعة المسير", "Print the run"
    LangAdd "طباعة باركود", "Print barcodes"
    LangAdd "عدد الملصقات", "Number of labels"
    LangAdd "عدد المنتجات", "Number of products"
    LangAdd "عملة التعامل", "Trading currency"
    LangAdd "فاتورة اليوم", "Invoice of the day"
    LangAdd "فاتورة جديدة", "New invoice"
    LangAdd "فاتورة مبسطة", "Simplified invoice"
    LangAdd "فتح وعرض فقط", "Open and view only"
    LangAdd "فروقات الجرد", "Count differences"
    LangAdd "فواتير البيع", "Sales invoices"
    LangAdd "قيمة المخزون", "Stock value"
    LangAdd "قيمة المرتجع", "Return value"
    LangAdd "قيود اليومية", "Journal entries"
    LangAdd "لا توجد قيود", "There are no entries"
    LangAdd "لا يكفي لصرف", "is not enough to pay"
    LangAdd "لعرض فواتيره", "to show his invoices"
    LangAdd "لم يتغير شيء", "Nothing changed"
    LangAdd "لم يُصرف بعد", "not paid yet"
    LangAdd "مبلغ المستند", "Document amount"
    LangAdd "مبيعات الشهر", "Sales of the month"
    LangAdd "مبيعات اليوم", "Sales of the day"
    LangAdd "مجمع الإهلاك", "Accumulated depreciation"
    LangAdd "مدينة العميل", "Customer city"
    LangAdd "مربوط ومرتجع", "Linked and returned"
    LangAdd "مرتجع سابقًا", "Returned before"
End Sub

Private Sub D4_3()
    LangAdd "مرتجع مبيعات", "Sales return"
    LangAdd "مركز التكلفة", "Cost center"
    LangAdd "مسودة عمولات", "Commission draft"
    LangAdd "مسير الرواتب", "Payroll"
    LangAdd "مصروفات أخرى", "Other expenses"
    LangAdd "مقفلة بالفعل", "already closed"
    LangAdd "ملف البيانات", "Data file"
    LangAdd "من آخر تصفية", "since the last closing"
    LangAdd "نسبة الضريبة", "VAT rate"
    LangAdd "نسبة العمولة", "Commission rate"
    LangAdd "نهاية الفترة", "End of the period"
    LangAdd "هل أنت متأكد", "Are you sure"
    LangAdd "وحدات القياس", "Units of measure"
    LangAdd "يعود للمخزون", "Back to stock"
    LangAdd "أمين المخزن", "Storekeeper"
    LangAdd "إضافة / حفظ", "Add / Save"
    LangAdd "إضافة للطلب", "Add to order"
    LangAdd "إعادة طباعة", "Reprint"
    LangAdd "إعداد الربط", "Connection setup"
    LangAdd "إقفال السنة", "Year closing"
    LangAdd "إلغاء الجرد", "Cancel the count"
    LangAdd "إلغاء الربط", "Unlink"
    LangAdd "إلغاء الصرف", "Cancel the payment"
    LangAdd "إيداع نقدية", "Cash deposit"
    LangAdd "اختر الحساب", "Choose the account"
    LangAdd "اختر الصورة", "Choose the picture"
    LangAdd "اختر العملة", "Choose the currency"
    LangAdd "اختر العميل", "Choose the customer"
    LangAdd "اختر المجلد", "Choose the folder"
    LangAdd "اختر المنتج", "Choose the product"
    LangAdd "اختر المورد", "Choose the supplier"
    LangAdd "اسم التصنيف", "Category name"
    LangAdd "اسم الصندوق", "Box name"
    LangAdd "اسم المصروف", "Expense name"
    LangAdd "اسم المندوب", "Sales rep name"
    LangAdd "اكتب الفترة", "Type the period"
    LangAdd "اكتب المبلغ", "Type the amount"
    LangAdd "الترحيل إلى", "Transfer to"
    LangAdd "الحد الأدنى", "Minimum"
    LangAdd "الدفع نقدًا", "Pay in cash"
    LangAdd "الرصيد دائن", "Credit balance"
    LangAdd "الرصيد مدين", "Debit balance"
    LangAdd "تأكيد الدفع", "Confirm payment"
    LangAdd "تاريخ الشيك", "Cheque date"
    LangAdd "تاريخ الصرف", "Payment date"
    LangAdd "تاريخ الكشف", "Statement date"
    LangAdd "تبقى كما هي", "stays as it is"
    LangAdd "تحت التحصيل", "Under collection"
    LangAdd "تحصيلات مدى", "Mada collections"
    LangAdd "ترتيب العرض", "Display order"
    LangAdd "ترحيل الجرد", "Post the count"
    LangAdd "ترحيل تصفية", "Closing transfer"
    LangAdd "تسجيل الشيك", "Record the cheque"
    LangAdd "تسجيل الصرف", "Record the payment"
    LangAdd "تسوية الجرد", "Stock count adjustment"
    LangAdd "تسوية تصفية", "Closing settlement"
    LangAdd "تعذر الحساب", "Could not calculate"
    LangAdd "تعذّر تشغيل", "Could not run"
    LangAdd "تكلفة الأصل", "Asset cost"
    LangAdd "تم الحفظ في", "Saved in"
    LangAdd "تنبيه: يوجد", "Warning: there are"
    LangAdd "توليد الكود", "Generate the code"
    LangAdd "جوال المورد", "Supplier mobile"
    LangAdd "حد الائتمان", "Credit limit"
    LangAdd "حذف آخر شهر", "Delete the last month"
    LangAdd "حذف الجارية", "Delete the open one"
    LangAdd "حذف الشيكات", "Delete cheques"
    LangAdd "حذف المسودة", "Delete the draft"
    LangAdd "حفظ التصفية", "Save the closing"
    LangAdd "حفظ المرتجع", "Save the return"
    LangAdd "خصم المخزون", "Stock deduction"
    LangAdd "دائن الفترة", "Period credit"
    LangAdd "رقم التصفية", "Closing number"
    LangAdd "رقم الطاولة", "Table number"
    LangAdd "رقم المستند", "Document number"
    LangAdd "رقم المصروف", "Expense number"
    LangAdd "زيادة تصفية", "Closing overage"
    LangAdd "سبب الإرجاع", "Return reason"
    LangAdd "سجل التدقيق", "Audit trail"
    LangAdd "شارع العميل", "Customer street"
    LangAdd "شهرًا مسجلة", "months recorded"
    LangAdd "صافي المباع", "Net sold"
    LangAdd "صرف الرواتب", "Salary payment"
    LangAdd "صندوق كاشير", "Cashier box"
    LangAdd "صورة المنتج", "Product picture"
    LangAdd "طباعة الجرد", "Print the count"
    LangAdd "طباعة السجل", "Print the log"
    LangAdd "طباعة القيد", "Print the entry"
    LangAdd "طريقة الدفع", "Payment method"
    LangAdd "عرض التقرير", "Show the report"
    LangAdd "فاتورة شراء", "Purchase invoice"
    LangAdd "قائمة الدخل", "Income statement"
    LangAdd "قبل التفعيل", "Before enabling"
    LangAdd "قبل الضريبة", "before VAT"
    LangAdd "قيد التسوية", "Settlement entry"
    LangAdd "قيد اليومية", "Journal entry"
    LangAdd "قيد جديد، و", "new entries, and"
    LangAdd "كل الصناديق", "All boxes"
    LangAdd "كل العمليات", "All transactions"
    LangAdd "كل المنتجات", "All products"
    LangAdd "كلمة المرور", "Password"
    LangAdd "كود التفعيل", "Activation code"
    LangAdd "كود المندوب", "Sales rep code"
    LangAdd "لوحة التحكم", "Dashboard"
    LangAdd "مبلغ الأساس", "Base amount"
    LangAdd "مبلغ الحركة", "Move amount"
    LangAdd "مثال: 25 أو", "Example: 25 or"
    LangAdd "مدة التكرار", "Repeats"
    LangAdd "مدى / بطاقة", "Mada / card"
    LangAdd "مدين الفترة", "Period debit"
    LangAdd "مدينة المحل", "Store city"
    LangAdd "مسار الشعار", "Logo path"
    LangAdd "مسح القائمة", "Clear the list"
    LangAdd "مصدر الشراء", "Purchase source"
    LangAdd "مكان المنتج", "Product location"
    LangAdd "منخفض: الحد", "Low: level"
    LangAdd "نتيجة الطلب", "Request result"
    LangAdd "نوع العملية", "Transaction type"
    LangAdd "نوع المستند", "Document type"
    LangAdd "نوع المصروف", "Expense type"
End Sub

Private Sub D4_4()
    LangAdd "وضع المطوّر", "Developer mode"
    LangAdd "يُحتفظ بآخر", "Keeps the last"
    LangAdd "آخر فاتورة", "Last invoice"
    LangAdd "أسطر الجرد", "Count lines"
    LangAdd "أسطر الطلب", "Order lines"
    LangAdd "أقصى تأخير", "Longest delay"
    LangAdd "أقفل السنة", "Close the year"
    LangAdd "إرجاع الكل", "Return all"
    LangAdd "إشعار دائن", "Credit note"
    LangAdd "إقفال فترة", "Close a period"
    LangAdd "إلغاء الكل", "Clear all"
    LangAdd "إهلاك سابق", "Previous depreciation"
    LangAdd "اختر البنك", "Choose the bank"
    LangAdd "اختر الدور", "Choose the role"
    LangAdd "اختر السند", "Choose the voucher"
    LangAdd "اختر الشهر", "Choose the month"
    LangAdd "اختر الشيك", "Choose the cheque"
    LangAdd "استلمنا من", "Received from"
    LangAdd "اسم الحساب", "Account name"
    LangAdd "اسم العملة", "Currency name"
    LangAdd "اسم العميل", "Customer name"
    LangAdd "اسم المركز", "Center name"
    LangAdd "اسم المنتج", "Product name"
    LangAdd "اسم المورد", "Supplier name"
    LangAdd "اسم الموظف", "Employee name"
    LangAdd "اسم الوحدة", "Unit name"
    LangAdd "اكتب السنة", "Type the year"
    LangAdd "اكتب تاريخ", "Type the date"
    LangAdd "العمر (شهر", "Life (months"
    LangAdd "الفترة: من", "Period: from"
    LangAdd "الفرق (صفر", "Difference (zero"
    LangAdd "المستخدمون", "Users"
    LangAdd "بحث بالاسم", "Search by name"
    LangAdd "بدلات أخرى", "Other allowances"
    LangAdd "بدون ضريبة", "Without VAT"
    LangAdd "بدون طباعة", "No printing"
    LangAdd "بيان السطر", "Line description"
    LangAdd "تحديد الكل", "Select all"
    LangAdd "تحويل صادر", "Outgoing transfer"
    LangAdd "تحويل وارد", "Incoming transfer"
    LangAdd "تعذر الحفظ", "Could not save"
    LangAdd "تم الإرسال", "Sent"
    LangAdd "تم الإلغاء", "Cancelled"
    LangAdd "تمت الخطوة", "Step done:"
    LangAdd "ثمانية عشر", "eighteen"
    LangAdd "حدد الفترة", "Set the period"
    LangAdd "حذف الحركة", "Delete the move"
    LangAdd "حفظ الحركة", "Save the move"
    LangAdd "حفظ وطباعة", "Save and print"
    LangAdd "حقوق ملكية", "Equity"
    LangAdd "حُوِّل إلى", "Transferred to"
    LangAdd "ربط السداد", "Payment matching"
    LangAdd "رصيد الكشف", "Statement balance"
    LangAdd "رقم الجهاز", "Computer number"
    LangAdd "رقم الجوال", "Mobile number"
    LangAdd "رقم الحساب", "Account number"
    LangAdd "رقم المبنى", "Building number"
    LangAdd "رمز التحقق", "Verification code"
    LangAdd "رمز العملة", "Currency code"
    LangAdd "رمز المركز", "Center code"
    LangAdd "رمز الوحدة", "Unit code"
    LangAdd "ريال سعودي", "Saudi riyal"
    LangAdd "شارع المحل", "Store street"
    LangAdd "شاشة البيع", "Sales screen"
    LangAdd "صافي الربح", "Net profit"
    LangAdd "صرفه البنك", "Cashed by the bank"
    LangAdd "طريقة الرد", "Refund method"
    LangAdd "عدد القيود", "Number of entries"
    LangAdd "على الحساب", "On account"
    LangAdd "على العميل", "The customer"
    LangAdd "غير متوازن", "Not balanced"
    LangAdd "فئة إضافات", "Extras category"
    LangAdd "فاتورة بيع", "Sales invoice"
    LangAdd "فتح المجلد", "Open the folder"
    LangAdd "فرق العملة", "Exchange difference"
    LangAdd "قيمة الفرق", "Difference value"
    LangAdd "كل الجداول", "All tables"
    LangAdd "كل الشاشات", "All screens"
    LangAdd "كل المراكز", "All centers"
    LangAdd "كمية الصنف", "Item quantity"
    LangAdd "كود المنتج", "Product code"
    LangAdd "مبلغ السند", "Voucher amount"
    LangAdd "مبلغ الشيك", "Cheque amount"
    LangAdd "مجمل الربح", "Gross profit"
    LangAdd "مرتجع شراء", "Purchase return"
    LangAdd "مرجع البنك", "Bank reference"
    LangAdd "مرحَّلة في", "posted on"
    LangAdd "مسودة مسير", "Run draft"
    LangAdd "من القائمة", "from the list"
    LangAdd "منها ضريبة", "of which VAT"
    LangAdd "نسبة صفرية", "Zero rate"
    LangAdd "نقطة البيع", "Point of sale"
    LangAdd "نوع الحركة", "Move type"
    LangAdd "نوع الحساب", "Account type"
    LangAdd "نوع الشراء", "Purchase type"
    LangAdd "ورقة الجرد", "Count sheet"
    LangAdd "آخر تحديث", "Last update"
    LangAdd "آخر تصفية", "Last closing"
    LangAdd "آخر معامل", "Last rate"
    LangAdd "أربعة عشر", "fourteen"
    LangAdd "أُنشئ منه", "Created from it"
    LangAdd "إعادة فتح", "Reopen"
    LangAdd "إقفال سنة", "Close a year"
    LangAdd "إلى تاريخ", "To date"
    LangAdd "إلى صندوق", "To box"
    LangAdd "إيصال بيع", "Sales receipt"
    LangAdd "اسم الأصل", "Asset name"
    LangAdd "اسم الفرع", "Branch name"
    LangAdd "اسم المحل", "Store name"
    LangAdd "اعتُمد في", "Approved on"
    LangAdd "الإعدادات", "Settings"
    LangAdd "الإيرادات", "Revenue"
    LangAdd "الاستحقاق", "Due date"
    LangAdd "التأمينات", "Social insurance"
    LangAdd "التصنيفات", "Categories"
    LangAdd "التعديلات", "Changes"
    LangAdd "المحاولات", "Attempts"
    LangAdd "المدفوعات", "Payments"
    LangAdd "المرتجعات", "Returns"
    LangAdd "المستندات", "Documents"
End Sub

Private Sub D4_5()
    LangAdd "المشتريات", "Purchases"
    LangAdd "المصروفات", "Expenses"
    LangAdd "المقبوضات", "Receipts"
    LangAdd "المندوبين", "Sales reps"
    LangAdd "بدل السكن", "Housing allowance"
    LangAdd "بدل النقل", "Transport allowance"
    LangAdd "بعد اليوم", "after today"
    LangAdd "بلا نهاية", "No end"
    LangAdd "تحصيل شيك", "Cheque collection"
    LangAdd "تسوية مدى", "Mada settlement"
    LangAdd "تمت إضافة", "Added"
    LangAdd "ثلاثة عشر", "thirteen"
    LangAdd "ثمن البيع", "Sale price"
    LangAdd "جنيه مصري", "Egyptian pound"
    LangAdd "حذف القيد", "Delete the entry"
    LangAdd "حركة منتج", "Product moves"
    LangAdd "حفظ الأصل", "Save the asset"
    LangAdd "حفظ السند", "Save the voucher"
    LangAdd "حفظ القيد", "Save the entry"
    LangAdd "حفظ تصفية", "Save closing"
    LangAdd "حفظ مسودة", "Save draft"
    LangAdd "حي العميل", "Customer district"
    LangAdd "حُدِّث في", "Updated on"
    LangAdd "خصم السطر", "Line discount"
    LangAdd "خصم السلف", "Advance deductions"
    LangAdd "دخول خاطئ", "Wrong login"
    LangAdd "رصيد دائن", "Credit balance"
    LangAdd "رصيد سابق", "Previous balance"
    LangAdd "رقم الجرد", "Count number"
    LangAdd "رقم السند", "Voucher number"
    LangAdd "رقم الشيك", "Cheque number"
    LangAdd "رقم القيد", "Entry number"
    LangAdd "ساخن جدًا", "Extra hot"
    LangAdd "سحب نقدية", "Cash withdrawal"
    LangAdd "سعر البيع", "Sale price"
    LangAdd "سلفة موظف", "Employee advance"
    LangAdd "سنة جديدة", "New year"
    LangAdd "سند نقدية", "Cash voucher"
    LangAdd "سُجِّل في", "Recorded on"
    LangAdd "شراء نقدي", "Cash purchase"
    LangAdd "صرفنا إلى", "Paid to"
    LangAdd "طرق الدفع", "Payment methods"
    LangAdd "طلب توصيل", "Delivery order"
    LangAdd "طلب داخلي", "Dine-in order"
    LangAdd "عجز تصفية", "Closing shortage"
    LangAdd "عكس القيد", "Reverse the entry"
    LangAdd "عمولة مدى", "Mada fee"
    LangAdd "غير مربوط", "Unlinked"
    LangAdd "غير مستحق", "Not due"
    LangAdd "غير مقفلة", "Not closed"
    LangAdd "غير ملائم", "Unsuitable"
    LangAdd "فتح القيد", "Open the entry"
    LangAdd "في المسير", "in the run"
    LangAdd "قيد محذوف", "Deleted entry"
    LangAdd "قيد يومية", "Journal entry"
    LangAdd "كل 3 أشهر", "Every 3 months"
    LangAdd "ليس بصيغة", "is not in the format of"
    LangAdd "مبلغ سنوي", "Yearly amount"
    LangAdd "مرتجع بيع", "Sales return"
    LangAdd "مستبعد في", "Disposed on"
    LangAdd "مقارنة من", "Comparison from"
    LangAdd "مقفلة حتى", "Closed up to"
    LangAdd "منتج جديد", "New product"
    LangAdd "نسخ الرقم", "Copy the number"
    LangAdd "نوع البيع", "Sale type"
    LangAdd "نوع السند", "Voucher type"
    LangAdd "هذا الشهر", "This month"
    LangAdd "هذه السنة", "This year"
    LangAdd "ولم يُرسل", "and not sent"
    LangAdd "ومصروف في", "and paid on"
    LangAdd "يمكن ربطه", "Can be linked"
    LangAdd "يُصرف إلى", "Paid to"
    LangAdd "آخر حركة", "Last move"
    LangAdd "آخر دخول", "Last login"
    LangAdd "آخر نسخة", "Last backup"
    LangAdd "أربعمائة", "four hundred"
    LangAdd "أصل جديد", "New asset"
    LangAdd "اثنا عشر", "twelve"
    LangAdd "الإجمالي", "Total"
    LangAdd "الإضافات", "Extras"
    LangAdd "الارتداد", "Bounce"
    LangAdd "الاستلام", "Receipt"
    LangAdd "الانحراف", "Variance"
    LangAdd "الباركود", "Barcode"
    LangAdd "التقارير", "Reports"
    LangAdd "السعودية", "Saudi Arabia"
    LangAdd "الصادرات", "Exports"
    LangAdd "الصلاحية", "Permission"
    LangAdd "الصناديق", "Boxes"
    LangAdd "العمولات", "Commissions"
    LangAdd "الفاتورة", "Invoice"
    LangAdd "الفواتير", "Invoices"
    LangAdd "المبيعات", "Sales"
    LangAdd "المجموعة", "Group"
    LangAdd "المحافظة", "Governorate"
    LangAdd "المرحَّل", "Posted"
    LangAdd "المستخدم", "User"
    LangAdd "المسيرات", "Runs"
    LangAdd "المنتجات", "Products"
    LangAdd "الموازنة", "Budget"
    LangAdd "الموردون", "Suppliers"
    LangAdd "بدون سكر", "No sugar"
    LangAdd "بيع نقدي", "Cash sale"
    LangAdd "تسعة عشر", "nineteen"
    LangAdd "تم إنشاء", "Created"
    LangAdd "تم الحذف", "Deleted"
    LangAdd "تم الحفظ", "Saved"
    LangAdd "تم الربط", "Linked"
    LangAdd "ثلاثمائة", "three hundred"
    LangAdd "ثلج قليل", "Little ice"
    LangAdd "ثمانمائة", "eight hundred"
    LangAdd "جرد جديد", "New count"
    LangAdd "حتى الآن", "So far"
    LangAdd "حجم الخط", "Font size"
    LangAdd "حي المحل", "Store district"
    LangAdd "خمسة عشر", "fifteen"
    LangAdd "ربع سنوي", "Quarterly"
    LangAdd "رمز الرد", "Reply code"
    LangAdd "سبعة عشر", "seventeen"
    LangAdd "سكر قليل", "Little sugar"
End Sub

Private Sub D4_6()
    LangAdd "شراء آجل", "Credit purchase"
    LangAdd "شهر جديد", "New month"
    LangAdd "شيك صادر", "Issued cheque"
    LangAdd "شيك مرتد", "Bounced cheque"
    LangAdd "شيك وارد", "Received cheque"
    LangAdd "صفر جنيه", "zero pounds"
    LangAdd "صفر ريال", "zero riyals"
    LangAdd "طلب سفري", "Takeaway order"
    LangAdd "غير صالح", "Invalid"
    LangAdd "غير مسدد", "Unpaid"
    LangAdd "غير موزع", "Not allocated"
    LangAdd "فعلي سنة", "Actuals of year"
    LangAdd "فك القفل", "Unlock"
    LangAdd "قيد جديد", "New entry"
    LangAdd "قيد عكسي", "Reversing entry"
    LangAdd "قيد يدوي", "Manual entry"
    LangAdd "كشف حساب", "Account statement"
    LangAdd "لا يُرسل", "Not sent"
    LangAdd "لم يُنشأ", "Not created"
    LangAdd "لون الزر", "Button color"
    LangAdd "معتمد في", "Approved on"
    LangAdd "مقفل حتى", "Closed up to"
    LangAdd "من البنك", "From the bank"
    LangAdd "من تاريخ", "From date"
    LangAdd "من صندوق", "From a box"
    LangAdd "نوع جديد", "New type"
    LangAdd "والمتوفر", "and available"
    LangAdd "ورقة جرد", "Count sheet"
    LangAdd "ينتهي في", "Ends on"
    LangAdd "يوجد فرق", "There is a difference"
    LangAdd "آخر بيع", "Last sale"
    LangAdd "آخر خطأ", "Last error"
    LangAdd "أحد عشر", "eleven"
    LangAdd "أكثر من", "More than"
    LangAdd "إيرادات", "Revenue"
    LangAdd "ابحث في", "Search in"
    LangAdd "استحقاق", "Due"
    LangAdd "استعراض", "Browse"
    LangAdd "افتراضي", "Default"
    LangAdd "الآيبان", "IBAN"
    LangAdd "الأدوار", "Roles"
    LangAdd "الأرباح", "Profit"
    LangAdd "الأساسي", "Basic"
    LangAdd "الأصناف", "Items"
    LangAdd "الأهداف", "Targets"
    LangAdd "الإصدار", "Version"
    LangAdd "الإضافي", "Overtime"
    LangAdd "الإقرار", "Return"
    LangAdd "الإنجاز", "Achievement"
    LangAdd "الإهلاك", "Depreciation"
    LangAdd "البدلات", "Allowances"
    LangAdd "التاريخ", "Date"
    LangAdd "التالية", "Next"
    LangAdd "التحصيل", "Collections"
    LangAdd "الترتيب", "Order"
    LangAdd "الترحيل", "Posting"
    LangAdd "التسوية", "Reconciliation"
    LangAdd "التصنيف", "Category"
    LangAdd "التعديل", "Adjustment"
    LangAdd "التقييم", "Valuation"
    LangAdd "التكرار", "Frequency"
    LangAdd "التكلفة", "Cost"
    LangAdd "الحركات", "Moves"
    LangAdd "الخزينة", "Treasury"
    LangAdd "الدفتري", "Book value"
    LangAdd "الرواتب", "Payroll"
    LangAdd "الزيادة", "Overage"
    LangAdd "السابقة", "Previous"
    LangAdd "السندات", "Vouchers"
    LangAdd "الشيكات", "Cheques"
    LangAdd "الصندوق", "Box"
    LangAdd "الضريبة", "VAT"
    LangAdd "الطابعة", "Printer"
    LangAdd "الطريقة", "Method"
    LangAdd "العملاء", "Customers"
    LangAdd "العملات", "Currencies"
    LangAdd "العملية", "Transaction"
    LangAdd "العمولة", "Commission"
    LangAdd "العنوان", "Address"
    LangAdd "القائمة", "List"
    LangAdd "الكاشير", "Cashier"
    LangAdd "المتبقي", "Remaining"
    LangAdd "المتوفر", "Available"
    LangAdd "المتوقع", "Expected"
    LangAdd "المجموع", "Total"
    LangAdd "المحاسب", "Accountant"
    LangAdd "المحصّل", "Collector"
    LangAdd "المخزون", "Stock"
    LangAdd "المدفوع", "Paid"
    LangAdd "المدينة", "City"
    LangAdd "المراجع", "Reviewer"
    LangAdd "المرتجع", "Return"
    LangAdd "المرتدة", "Bounced"
    LangAdd "المسؤول", "Manager"
    LangAdd "المستحق", "Due"
    LangAdd "المستلم", "Recipient"
    LangAdd "المستند", "Document"
    LangAdd "المستوى", "Level"
    LangAdd "المشروب", "Drink"
    LangAdd "المشكلة", "Problem"
    LangAdd "المصروف", "Expense"
    LangAdd "المطلوب", "required"
    LangAdd "المعامل", "Rate"
    LangAdd "المندوب", "Sales rep"
    LangAdd "المنطقة", "Region"
    LangAdd "الوحدات", "Units"
    LangAdd "بدون حد", "No limit"
    LangAdd "برتقالي", "Orange"
    LangAdd "تجريبية", "Test"
    LangAdd "تسعمائة", "nine hundred"
    LangAdd "خمسمائة", "five hundred"
    LangAdd "رد نقدي", "Cash refund"
    LangAdd "سبعمائة", "seven hundred"
    LangAdd "ستة عشر", "sixteen"
    LangAdd "سطر قيد", "Entry line"
    LangAdd "سند صرف", "Payment voucher"
    LangAdd "سند قبض", "Receipt voucher"
    LangAdd "صرف آخر", "Other payment"
    LangAdd "صرف شيك", "Cheque payment"
    LangAdd "طُبع في", "Printed on"
End Sub

Private Sub D4_7()
    LangAdd "غير نشط", "is not active"
    LangAdd "في شاشة", "in the screen"
    LangAdd "لا توجد", "None"
    LangAdd "للإضافة", "to add"
    LangAdd "لم تجتز", "Failed:"
    LangAdd "متوازنة", "Balanced"
    LangAdd "مرة/سنة", "times/year"
    LangAdd "مستويات", "levels"
    LangAdd "مصروفات", "Expenses"
    LangAdd "ملاحظات", "Notes"
    LangAdd "مليونان", "two million"
    LangAdd "مُبلَّغ", "Reported"
    LangAdd "والدائن", "and credit"
    LangAdd "يبدأ من", "Starts from"
    LangAdd "أجراها", "Done by"
    LangAdd "أربعون", "forty"
    LangAdd "أكتوبر", "October"
    LangAdd "أُرسلت", "Sent"
    LangAdd "إجمالي", "Total"
    LangAdd "ارتداد", "Bounced"
    LangAdd "اعتمده", "Approved by"
    LangAdd "الأساس", "Base"
    LangAdd "الأصول", "Assets"
    LangAdd "البنوك", "Banks"
    LangAdd "البيئة", "Environment"
    LangAdd "البيان", "Description"
    LangAdd "التالي", "Next"
    LangAdd "الجدول", "Table"
    LangAdd "الجهاز", "Computer"
    LangAdd "الجوال", "Mobile"
    LangAdd "الحالة", "Status"
    LangAdd "الحركة", "Move"
    LangAdd "الحساب", "Account"
    LangAdd "الدائن", "Credit"
    LangAdd "الرصيد", "Balance"
    LangAdd "السابق", "Previous"
    LangAdd "الشارع", "Street"
    LangAdd "الشاشة", "Screen"
    LangAdd "الشراء", "Purchase"
    LangAdd "الصافي", "Net"
    LangAdd "العملة", "Currency"
    LangAdd "العميل", "Customer"
    LangAdd "الفئات", "Categories"
    LangAdd "الفترة", "Period"
    LangAdd "الفعلي", "Actual"
    LangAdd "القيمة", "Value"
    LangAdd "الكمية", "Quantity"
    LangAdd "المالك", "Owner"
    LangAdd "المباع", "Sold"
    LangAdd "المبلغ", "Amount"
    LangAdd "المتجر", "Store"
    LangAdd "المجلد", "Folder"
    LangAdd "المدير", "Manager"
    LangAdd "المدين", "Debit"
    LangAdd "المركز", "Center"
    LangAdd "المسجل", "Recorded"
    LangAdd "المسدد", "Paid"
    LangAdd "المنتج", "Product"
    LangAdd "المورد", "Supplier"
    LangAdd "الموظف", "Employee"
    LangAdd "النسبة", "Rate"
    LangAdd "الهاتف", "Phone"
    LangAdd "الوحدة", "Unit"
    LangAdd "بالضبط", "exactly"
    LangAdd "بالفعل", "already exists"
    LangAdd "بزيادة", "over by"
    LangAdd "بلا حد", "No limit"
    LangAdd "بنفسجي", "Purple"
    LangAdd "بواسطة", "by"
    LangAdd "تغيّرت", "changed"
    LangAdd "تم حفظ", "Saved"
    LangAdd "تم عدّ", "Counted"
    LangAdd "ثلاثون", "thirty"
    LangAdd "ثمانون", "eighty"
    LangAdd "ثمانية", "eight"
    LangAdd "جزاءات", "Penalties"
    LangAdd "ديسمبر", "December"
    LangAdd "سبتمبر", "September"
    LangAdd "ستمائة", "six hundred"
    LangAdd "عمولات", "Commissions"
    LangAdd "عميلًا", "customers"
    LangAdd "فاتورة", "Invoice"
    LangAdd "فبراير", "February"
    LangAdd "في حقل", "in the field"
    LangAdd "في يوم", "on day"
    LangAdd "فيروزي", "Teal"
    LangAdd "لا غير", "only"
    LangAdd "لتصنيف", "for category"
    LangAdd "مائتان", "two hundred"
    LangAdd "متوازن", "Balanced"
    LangAdd "محصَّل", "Collected"
    LangAdd "مرحَّل", "Posted"
    LangAdd "مستبعد", "Disposed"
    LangAdd "مستخدم", "User"
    LangAdd "مستردة", "Refunded"
    LangAdd "معاينة", "Preview"
    LangAdd "معتمدة", "Approved"
    LangAdd "مكافآت", "Bonuses"
    LangAdd "ملايين", "million"
    LangAdd "ممنوحة", "Granted"
    LangAdd "من بنك", "From a bank"
    LangAdd "موازنة", "Budget"
    LangAdd "موردًا", "suppliers"
    LangAdd "مُرحّل", "Posted"
    LangAdd "نوفمبر", "November"
    LangAdd "أبريل", "April"
    LangAdd "أربعة", "four"
    LangAdd "أعدّه", "Prepared by"
    LangAdd "أغسطس", "August"
    LangAdd "ألفان", "two thousand"
    LangAdd "أُرسل", "Sent"
    LangAdd "أُضيف", "Added"
    LangAdd "إضافة", "Add"
    LangAdd "إغلاق", "Close"
    LangAdd "إلغاء", "Cancel"
    LangAdd "إيداع", "Deposit"
    LangAdd "اثنان", "two"
    LangAdd "الأصل", "Asset"
    LangAdd "الاسم", "Name"
    LangAdd "البحث", "Search"
End Sub

Private Sub D4_8()
    LangAdd "البند", "Item"
    LangAdd "البنك", "Bank"
    LangAdd "البيع", "Sale"
    LangAdd "الجرد", "Stock count"
    LangAdd "الجهة", "Party"
    LangAdd "الحجم", "Size"
    LangAdd "الحذف", "Delete"
    LangAdd "الحقل", "Field"
    LangAdd "الخصم", "Discount"
    LangAdd "الدفع", "Payment"
    LangAdd "الدور", "Role"
    LangAdd "الربح", "Profit"
    LangAdd "الرقم", "Number"
    LangAdd "الرمز", "Code"
    LangAdd "السبب", "Reason"
    LangAdd "السجل", "Record"
    LangAdd "السعر", "Price"
    LangAdd "السكن", "Housing"
    LangAdd "السنة", "Year"
    LangAdd "السند", "Voucher"
    LangAdd "الشهر", "Month"
    LangAdd "الصرف", "Payment"
    LangAdd "الصنف", "Item"
    LangAdd "الصور", "Pictures"
    LangAdd "العجز", "Shortage"
    LangAdd "العدد", "Count"
    LangAdd "الفرق", "Difference"
    LangAdd "القسم", "Department"
    LangAdd "القيد", "Entry"
    LangAdd "الكود", "Code"
    LangAdd "الملف", "File"
    LangAdd "النقص", "Shortage"
    LangAdd "النوع", "Type"
    LangAdd "الهدف", "Target"
    LangAdd "الوصف", "Description"
    LangAdd "الوقت", "Time"
    LangAdd "اليوم", "Today"
    LangAdd "بقيمة", "worth"
    LangAdd "تاريخ", "Date"
    LangAdd "تحديث", "Refresh"
    LangAdd "تحويل", "Transfer"
    LangAdd "تراجع", "Undo"
    LangAdd "تسعون", "ninety"
    LangAdd "تصدير", "Export"
    LangAdd "تعديل", "Edit"
    LangAdd "تقرير", "Report"
    LangAdd "تنبيه", "Warning"
    LangAdd "توصيل", "Delivery"
    LangAdd "ثلاثة", "three"
    LangAdd "جارية", "Open"
    LangAdd "حرفًا", "characters"
    LangAdd "خزينة", "Treasury"
    LangAdd "خمسون", "fifty"
    LangAdd "داخلي", "Internal"
    LangAdd "دقيقة", "minutes"
    LangAdd "رئيسي", "Main"
    LangAdd "راجعه", "Reviewed by"
    LangAdd "رمادي", "Grey"
    LangAdd "رُوجع", "Checked:"
    LangAdd "زيادة", "Overage"
    LangAdd "سبعون", "seventy"
    LangAdd "طاولة", "Table"
    LangAdd "طباعة", "Print"
    LangAdd "عشرون", "twenty"
    LangAdd "عملية", "Transaction"
    LangAdd "فعلية", "Production"
    LangAdd "كاشير", "Cashier"
    LangAdd "متوقف", "Stopped"
    LangAdd "مدفوع", "Paid"
    LangAdd "مربوط", "Linked"
    LangAdd "مرتجع", "Return"
    LangAdd "مرفوض", "Rejected"
    LangAdd "مستند", "documents"
    LangAdd "مسودة", "Draft"
    LangAdd "مصروف", "Expense"
    LangAdd "مطابق", "Matched"
    LangAdd "مطلوب", "is required"
    LangAdd "معتمد", "Approved"
    LangAdd "مفتوح", "Open"
    LangAdd "مقبوض", "Received"
    LangAdd "ملائم", "Suitable"
    LangAdd "مليون", "million"
    LangAdd "منخفض", "Low"
    LangAdd "مُرسل", "Submitted"
    LangAdd "نتيجة", "Result"
    LangAdd "يساوي", "equals"
    LangAdd "يناير", "January"
    LangAdd "يوليو", "July"
    LangAdd "يومًا", "days"
    LangAdd "يونيو", "June"
    LangAdd "آلاف", "thousand"
    LangAdd "أحرف", "characters"
    LangAdd "أحمر", "Red"
    LangAdd "أخرى", "Other"
    LangAdd "أخضر", "Green"
    LangAdd "أزرق", "Blue"
    LangAdd "أصول", "Assets"
    LangAdd "أيام", "Days"
    LangAdd "احسب", "Calculate"
    LangAdd "اختر", "Choose"
    LangAdd "الحد", "limit"
    LangAdd "الحي", "District"
    LangAdd "الكل", "All"
    LangAdd "بثمن", "for a price"
    LangAdd "بدون", "None"
    LangAdd "تسعة", "nine"
    LangAdd "جديد", "New"
    LangAdd "جنيه", "EGP"
    LangAdd "حساب", "Account"
    LangAdd "خروج", "Exit"
    LangAdd "خصوم", "Liabilities"
    LangAdd "خمسة", "five"
    LangAdd "دائن", "Credit"
    LangAdd "دخول", "Login"
    LangAdd "رجوع", "Back"
    LangAdd "رصيد", "Balance"
    LangAdd "ريال", "SAR"
    LangAdd "سبعة", "seven"
    LangAdd "ستون", "sixty"
    LangAdd "سفري", "Takeaway"
End Sub

Private Sub D4_9()
    LangAdd "سلفة", "Advance"
    LangAdd "سنوي", "Yearly"
    LangAdd "شغّل", "Run"
    LangAdd "شهري", "Monthly"
    LangAdd "صادر", "Issued"
    LangAdd "صالح", "Valid"
    LangAdd "صغير", "Small"
    LangAdd "صفحة", "Page"
    LangAdd "عشرة", "ten"
    LangAdd "غياب", "Absence"
    LangAdd "فارغ", "Empty"
    LangAdd "فرعي", "Sub"
    LangAdd "قائم", "Open"
    LangAdd "كبير", "Large"
    LangAdd "مائة", "one hundred"
    LangAdd "مارس", "March"
    LangAdd "مايو", "May"
    LangAdd "محلي", "Local"
    LangAdd "مدين", "Debit"
    LangAdd "مرتد", "Bounced"
    LangAdd "مسدد", "Paid"
    LangAdd "مسير", "Run"
    LangAdd "ملغى", "Cancelled"
    LangAdd "ناقص", "Missing"
    LangAdd "نسخة", "Backup"
    LangAdd "نقدي", "Cash"
    LangAdd "نيلي", "Indigo"
    LangAdd "هاتف", "Phone"
    LangAdd "هللة", "halalas"
    LangAdd "واحد", "one"
    LangAdd "وارد", "Received"
    LangAdd "وردي", "Pink"
    LangAdd "يوجد", "There are"
    LangAdd "آجل", "Credit"
    LangAdd "ألف", "thousand"
    LangAdd "إلى", "To"
    LangAdd "بحث", "Search"
    LangAdd "بعد", "After"
    LangAdd "بني", "Brown"
    LangAdd "حتى", "Until"
    LangAdd "حذف", "Delete"
    LangAdd "حفظ", "Save"
    LangAdd "ر.س", "SAR"
    LangAdd "ربط", "The connection to"
    LangAdd "رقم", "Number"
    LangAdd "ستة", "six"
    LangAdd "سجل", "Record"
    LangAdd "سحب", "Withdrawal"
    LangAdd "شهر", "Month"
    LangAdd "صفر", "zero"
    LangAdd "صنف", "Item"
    LangAdd "عجز", "Shortage"
    LangAdd "عرض", "View"
    LangAdd "فتح", "Open"
    LangAdd "فرق", "Difference"
    LangAdd "فقط", "Only"
    LangAdd "قبل", "Before"
    LangAdd "قرش", "piasters"
    LangAdd "مسح", "Clear"
    LangAdd "مصر", "Egypt"
    LangAdd "ملف", "File"
    LangAdd "نشط", "Active"
    LangAdd "نعم", "Yes"
    LangAdd "وسط", "Medium"
    LangAdd "في", "in"
    LangAdd "لا", "No"
    LangAdd "من", "From"
    LangAdd "هي", "is"
    LangAdd "و", "and"
End Sub
