Attribute VB_Name = "modLangData3"
'==============================================================================
' modLangData3  -  Retail Store Management System: part 3 of the Arabic ->
' English dictionary of the interface (modLang). GENERATED FILE - do not edit.
' Source: tools/i18n_en.py  ->  python3 tools/generate.py
'==============================================================================
Option Compare Database
Option Explicit

Public Sub LangData3()
    D3_1
    D3_2
    D3_3
    D3_4
    D3_5
    D3_6
    D3_7
End Sub

Private Sub D3_1()
    LangAdd "غير موجودة أو غير نشطة", "does not exist or is not active"
    LangAdd "فاتورة / مرتجع مشتريات", "Purchase invoice / return"
    LangAdd "قائمة الدخل والميزانية", "Income statement and balance sheet"
    LangAdd "قيود التسوية والافتتاح", "Adjusting and opening entries"
    LangAdd "كشف حساب ودفتر الأستاذ", "Account statement and general ledger"
    LangAdd "لا تملك صلاحية الشيكات", "You do not have the permission for cheques"
    LangAdd "متأخرة أكثر من 20 ساعة", "Late more than 20 hours"
    LangAdd "محاولات الدخول الفاشلة", "Failed login attempts"
    LangAdd "ملف البيانات غير موجود", "The data file does not exist"
    LangAdd "من أضاف أو عدّل أو حذف", "Who added, edited or deleted"
    LangAdd "هذا الخيار للمبرمج فقط", "This option is for the developer only"
    LangAdd "هل تسمح بإتمام العملية", "Do you allow the transaction to be completed"
    LangAdd "وارد آخر (فوائد أو قرض", "Other incoming (interest or a loan"
    LangAdd "يمكنك تصفية صندوقك فقط", "You can close your own box only"
    LangAdd "أضفه من زر «منتج جديد", "Add it with the button New product"
    LangAdd "أفضل 10 منتجات مبيعًا", "Top 10 best-selling products"
    LangAdd "أقل من المبلغ المودَع", "less than the deposited amount"
    LangAdd "أو اختر المنتج بالاسم", "or choose the product by name"
    LangAdd "إجمالي تكلفة المبيعات", "Total cost of sales"
    LangAdd "إجمالي ضريبة المدخلات", "Total input VAT"
    LangAdd "إعداد ربط منصة فاتورة", "Fatoora connection setup"
    LangAdd "اختر الأصل من القائمة", "Choose the asset from the list"
    LangAdd "اختر الربط من القائمة", "Choose the link from the list"
    LangAdd "اختر الشيك من القائمة", "Choose the cheque from the list"
    LangAdd "اختر جلسة الجرد أولًا", "Choose the count session first"
    LangAdd "اسم المحل بالإنجليزية", "Store name in English"
    LangAdd "الأسعار شاملة الضريبة", "Prices include VAT"
    LangAdd "الأصناف التي لم تُعدّ", "Items not counted"
    LangAdd "الإجمالي شامل الضريبة", "Total including VAT"
    LangAdd "الحذف وإلغاء الاعتماد", "Delete and cancel approval"
    LangAdd "الدفاتر بعد استبعادها", "the books after its disposal"
    LangAdd "الرصيد الحالي للصندوق", "Current balance of the box"
    LangAdd "السماح بالبيع بالسالب", "Allow selling below zero stock"
    LangAdd "الشيك ليس تحت التحصيل", "The cheque is not under collection"
    LangAdd "المبالغ لا تكون سالبة", "Amounts are never negative"
    LangAdd "المبلغ لا يكون سالبًا", "The amount is never negative"
    LangAdd "المنتجات غير المتحركة", "Slow-moving products"
    LangAdd "الموازنة مقابل الفعلي", "Budget vs actual"
    LangAdd "بداية الفترة الضريبية", "Start of the tax period"
    LangAdd "تاريخ الصرف بعد اليوم", "The payment date is after today"
    LangAdd "تاريخ الكشف بعد اليوم", "The statement date is after today"
    LangAdd "تحديث الكميات المسجلة", "Refresh the recorded quantities"
    LangAdd "تحصيلات مدى لم تُسوَّ", "Mada collections not settled"
    LangAdd "تعذّر التوقيع ببرنامج", "Could not sign with"
    LangAdd "تكلفة البضاعة المباعة", "Cost of goods sold"
    LangAdd "تم تسجيل ارتداد الشيك", "The bounce of the cheque was recorded"
    LangAdd "تم تسجيل سداد الضريبة", "The VAT payment was recorded"
    LangAdd "تمت النسخة الاحتياطية", "Backup done"
    LangAdd "جلسة الجرد غير موجودة", "The count session does not exist"
    LangAdd "رصيد البنك في الدفاتر", "Bank balance in the books"
    LangAdd "شيكات صادرة (للموردين", "Issued cheques (to suppliers"
    LangAdd "صافي الضريبة المستحقة", "Net VAT due"
    LangAdd "ضريبة المخرجات للفترة", "Output VAT of the period"
    LangAdd "ضريبة المدخلات للفترة", "Input VAT of the period"
    LangAdd "طباعة ملصقات الباركود", "Print barcode labels"
    LangAdd "عاد الشيك تحت التحصيل", "The cheque is back under collection"
    LangAdd "عدد النسخ المحتفظ بها", "Number of backups kept"
    LangAdd "غير نشط ولا يمكن بيعه", "is not active and cannot be sold"
    LangAdd "قائمة أنواع المصروفات", "List of expense types"
    LangAdd "قيمة المخزون بالتكلفة", "Stock value at cost"
    LangAdd "لا تملك صلاحية البنوك", "You do not have the permission for banks"
    LangAdd "لا توجد تعديلات للحفظ", "There are no changes to save"
    LangAdd "لا مبيعات آجلة في آخر", "No credit sales in the last"
    LangAdd "مبلغ مستحق على العميل", "an amount due from the customer"
    LangAdd "مراكز التكلفة والفروع", "Cost centers and branches"
    LangAdd "مركز من يُنشئ المصروف", "Center of the user who creates the expense"
    LangAdd "مسير عمولات المندوبين", "Sales rep commission run"
    LangAdd "منتجات منخفضة المخزون", "Low-stock products"
    LangAdd "مندوب   صافي المبيعات", "sales reps   Net sales"
    LangAdd "نسبة السيولة (التداول", "Liquidity (current) ratio"
    LangAdd "نسبة العمولة بين 0% و", "The commission rate is between 0% and"
    LangAdd "يجب تغيير كلمة المرور", "The password must be changed"
    LangAdd "يوجد مسير عمولات لشهر", "A commission run for the month"
    LangAdd "أسطر مرتجع المشتريات", "Purchase return lines"
    LangAdd "أفضل المنتجات مبيعًا", "Best-selling products"
    LangAdd "إيداع نقدية في البنك", "Deposit cash in the bank"
    LangAdd "إيداع نقدية من صندوق", "Deposit cash from a box"
    LangAdd "اختر السند والفاتورة", "Choose the voucher and the invoice"
    LangAdd "اختر طريقة الاستبعاد", "Choose the disposal method"
    LangAdd "اختر قيمة من القائمة", "Choose a value from the list"
    LangAdd "اكتب تاريخ كشف البنك", "Type the date of the bank statement"
    LangAdd "اكتب سبب إعادة الفتح", "Type the reason for reopening"
    LangAdd "التعديلات (المرتجعات", "Adjustments (returns"
    LangAdd "التكلفة بدون الضريبة", "Cost without VAT"
    LangAdd "الرقم الضريبي للعميل", "Customer tax number"
    LangAdd "الشهر التالي للتسجيل", "Next month to record"
    LangAdd "الصندوق (إيداع / سحب", "Box (deposit / withdrawal"
    LangAdd "الفاتورة الإلكترونية", "E-invoicing"
    LangAdd "المبلغ (بدون الضريبة", "Amount (without VAT"
    LangAdd "المبيعات حسب التصنيف", "Sales by category"
    LangAdd "المحصَّلة / المصروفة", "Collected / paid"
    LangAdd "المدفوعات والمصروفات", "Payments and expenses"
    LangAdd "المرتجعات بدون ضريبة", "Returns without VAT"
    LangAdd "المورد يحتسب الضريبة", "The supplier charges VAT"
    LangAdd "بدون اسم إنجليزي فقط", "Without English name only"
    LangAdd "بيع - الثمن في البنك", "Sale - price in the bank"
    LangAdd "بيع - الثمن في صندوق", "Sale - price in a box"
    LangAdd "تصفيات يومية الكاشير", "Daily cashier closings"
    LangAdd "تعذّرت قراءة الشهادة", "Could not read the certificate"
    LangAdd "تم تسجيل صرف الرواتب", "The salary payment was recorded"
    LangAdd "تم حفظ فاتورة الشراء", "The purchase invoice was saved"
    LangAdd "تم حفظ مسودة الإقرار", "The draft of the return was saved"
    LangAdd "تمت إعادة فتح الفترة", "The period was reopened"
    LangAdd "حذف الأصل وقيد شرائه", "Delete the asset and its purchase entry"
    LangAdd "حساب أساسي في النظام", "A system account"
    LangAdd "حساب الأصل (المجموعة", "Asset account (group"
    LangAdd "حساب البنك في الدليل", "Account of the bank in the chart"
    LangAdd "ربط السداد بالفواتير", "Match payments to invoices"
    LangAdd "رصيد دائن غير مستخدم", "Unused credit balance"
    LangAdd "رقم الفاتورة الأصلية", "Original invoice number"
    LangAdd "رقم الهوية / الإقامة", "ID / iqama number"
    LangAdd "رقمًا يبدأ وينتهي بـ", "a number starting and ending with"
    LangAdd "شيك وارد تحت التحصيل", "Received cheque under collection"
    LangAdd "شيكات صادرة لم تُصرف", "Issued cheques not yet cashed"
    LangAdd "صافي الربح: الموازنة", "Net profit: budget"
    LangAdd "ضريبة القيمة المضافة", "VAT"
    LangAdd "عدد الملصقات في الصف", "Labels per row"
    LangAdd "قائمة الملصقات فارغة", "The label list is empty"
    LangAdd "قيود الإهلاك المسجلة", "Recorded depreciation entries"
    LangAdd "لا تملك صلاحية الجرد", "You do not have the permission for stock counts"
End Sub

Private Sub D3_2()
    LangAdd "لا توجد أرصدة مفتوحة", "There are no open balances"
    LangAdd "لا توجد فاتورة سابقة", "There is no previous invoice"
    LangAdd "لا توجد منتجات راكدة", "There are no slow-moving products"
    LangAdd "للأصل إهلاك مسجل حتى", "The asset has depreciation recorded up to"
    LangAdd "للتحويل البنكي؛ فارغ", "for a bank transfer, empty"
    LangAdd "مجلد النسخ الاحتياطي", "Backup folder"
    LangAdd "مسير العمولات الشهري", "Monthly commission run"
    LangAdd "هل تريد تسجيل الخروج", "Do you want to log out"
    LangAdd "أقل المنتجات مبيعًا", "Least-selling products"
    LangAdd "أقل من صافي الرواتب", "less than the net salaries"
    LangAdd "أو ابحث باسم المنتج", "or search by product name"
    LangAdd "إجمالي حقوق الملكية", "Total equity"
    LangAdd "إقفال حتى هذا اليوم", "Close up to this day"
    LangAdd "اختر الحساب المقابل", "Choose the contra account"
    LangAdd "اختر الصندوق واليوم", "Choose the box and the day"
    LangAdd "اختر الفئة ثم الصنف", "Choose the category, then the item"
    LangAdd "ارتفاع الباركود (مم", "Barcode height (mm"
    LangAdd "الاسم المختصر للمحل", "Short store name"
    LangAdd "التكلفة أكبر من صفر", "Cost greater than zero"
    LangAdd "الرقم الضريبي للمحل", "Store tax number"
    LangAdd "الصافي شامل الضريبة", "Net including VAT"
    LangAdd "الفاتورة غير موجودة", "The invoice does not exist"
    LangAdd "القيد الآلي للعملية", "Automatic entry of the transaction"
    LangAdd "الكافيهات (شاشة لمس", "Cafes (touch screen"
    LangAdd "المبيعات بدون ضريبة", "Sales without VAT"
    LangAdd "المبيعات حسب المنتج", "Sales by product"
    LangAdd "المخزون حسب التصنيف", "Stock by category"
    LangAdd "المدفوع للمورد الآن", "Paid to the supplier now"
    LangAdd "المسير مصروف بالفعل", "The run is already paid"
    LangAdd "بدء / تحديث التسوية", "Start / refresh the reconciliation"
    LangAdd "تاريخها + هذه المدة", "its date + this period"
    LangAdd "تحويل إلى صندوق آخر", "Transfer to another box"
    LangAdd "تسجيل مصروفات المحل", "Record the expenses of the store"
    LangAdd "تسليم للمالك (تسوية", "Hand over to the owner (settlement"
    LangAdd "تصفية يومية الكاشير", "Daily cashier closing"
    LangAdd "تعذر تحديث المؤشرات", "Could not refresh the indicators"
    LangAdd "تعذر رسم الإحصائيات", "Could not draw the statistics"
    LangAdd "تعذّر إنشاء الشهادة", "Could not create the certificate"
    LangAdd "تعذّر توقيع المستند", "Could not sign the document"
    LangAdd "تم إقفال الفترة حتى", "The period was closed up to"
    LangAdd "تم الإرسال مع تحذير", "Sent with a warning"
    LangAdd "تم ضبط البرنامج على", "The program is now set for"
    LangAdd "تمت إعادة فتح السنة", "The year was reopened"
    LangAdd "تنبيه المخزون: يوجد", "Stock alert: there are"
    LangAdd "جمهورية مصر العربية", "Arab Republic of Egypt"
    LangAdd "حتى شهر (أي يوم فيه", "Up to month (any day in it"
    LangAdd "سحب نقدية إلى صندوق", "Cash withdrawal to a box"
    LangAdd "صافي إيرادات النشاط", "Net operating revenue"
    LangAdd "صافي الربح (الخسارة", "Net profit (loss"
    LangAdd "عدد الخانات العشرية", "Decimal places"
    LangAdd "فاتورة ضريبية مبسطة", "Simplified tax invoice"
    LangAdd "قيد عكسي جديد للقيد", "New reversing entry for the entry"
    LangAdd "كلمة المرور الجديدة", "New password"
    LangAdd "كلمة المرور الحالية", "Current password"
    LangAdd "لا مبيعات هذا الشهر", "No sales this month"
    LangAdd "لا يتبع الحساب نفسه", "An account cannot belong to itself"
    LangAdd "لكل المنتجات النشطة", "for all active products"
    LangAdd "معامل عملة البرنامج", "Rate of the program currency"
    LangAdd "نقدي أو بطاقة للدفع", "Cash or card for payment"
    LangAdd "نوع السند غير معروف", "Unknown voucher type"
    LangAdd "يُقفل بعد أول عملية", "Locked after the first transaction"
    LangAdd "أسطر القيد المختار", "Lines of the selected entry"
    LangAdd "أسطر فاتورة الشراء", "Purchase invoice lines"
    LangAdd "أسطر مسير العمولات", "Commission run lines"
    LangAdd "إنشاء المستحق الآن", "Create the due now"
    LangAdd "ابدأ التسوية أولًا", "Start the reconciliation first"
    LangAdd "اسم البنك / الحساب", "Bank / account name"
    LangAdd "الأدوار والصلاحيات", "Roles and permissions"
    LangAdd "الأسماء الإنجليزية", "English names"
    LangAdd "الإجمالي قبل الخصم", "Total before discount"
    LangAdd "التأمينات المستحقة", "Social insurance payable"
    LangAdd "التسوية غير موجودة", "The reconciliation does not exist"
    LangAdd "التصفية غير موجودة", "The closing does not exist"
    LangAdd "التكلفة بدون ضريبة", "Cost without VAT"
    LangAdd "العمولات المرحَّلة", "Posted commissions"
    LangAdd "الكافيه: سعر البيع", "Cafe: sale price"
    LangAdd "المبلغ قبل الضريبة", "Amount before VAT"
    LangAdd "المتبقي على الحساب", "Remaining on account"
    LangAdd "المستخدم غير موجود", "The user does not exist"
    LangAdd "المصروفات المتكررة", "Recurring expenses"
    LangAdd "المنشأة (غير سعودي", "Employer (non-Saudi"
    LangAdd "المنطقة / خط السير", "Region / route"
    LangAdd "الموازنة التقديرية", "Budget"
    LangAdd "الموظف صاحب السلفة", "Employee taking the advance"
    LangAdd "الميزانية العمومية", "Balance sheet"
    LangAdd "بسبب محاولات خاطئة", "after wrong attempts"
    LangAdd "بنك الساحب (الوارد", "Drawer bank (received"
    LangAdd "تحويل بين الصناديق", "Transfer between boxes"
    LangAdd "تحويل من صندوق آخر", "Transfer from another box"
    LangAdd "تسجيل إهلاك الأصول", "Record asset depreciation"
    LangAdd "تعذر حفظ سند الصرف", "Could not save the payment voucher"
    LangAdd "تعذر حفظ سند القبض", "Could not save the receipt voucher"
    LangAdd "تم تسجيل صرف الشيك", "The payment of the cheque was recorded"
    LangAdd "تم حفظ إعداد الربط", "The connection setup was saved"
    LangAdd "تم حفظ كلمة المرور", "The password was saved"
    LangAdd "حصة المنشأة (سعودي", "Employer share (Saudi"
    LangAdd "حصة الموظف السعودي", "Saudi employee share"
    LangAdd "خصم من رصيد العميل", "Deduct from the customer balance"
    LangAdd "خصم من رصيد المورد", "Deduct from the supplier balance"
    LangAdd "ربط تلقائي بالأقدم", "Auto-link to the oldest"
    LangAdd "رقم فاتورة المصروف", "Expense invoice number"
    LangAdd "سبب إلغاء الاعتماد", "Reason for cancelling the approval"
    LangAdd "سجل الأصول الثابتة", "Fixed asset register"
    LangAdd "سحب نقدية من البنك", "Cash withdrawal from the bank"
    LangAdd "صافي الربح المتوقع", "Expected net profit"
    LangAdd "صافي ما يدخل البنك", "Net amount into the bank"
    LangAdd "عرض معاينة الطباعة", "Show print preview"
    LangAdd "فحص سلامة البيانات", "Data integrity check"
    LangAdd "قبل الخصم والضريبة", "before discount and VAT"
    LangAdd "قيمة وحدة واحدة بـ", "Value of one unit in"
    LangAdd "كلمة المرور معيّنة", "Password set"
    LangAdd "لا توجد أصول ثابتة", "There are no fixed assets"
    LangAdd "لا توجد فترة مقفلة", "There is no closed period"
    LangAdd "لا توجد قيود إهلاك", "There are no depreciation entries"
    LangAdd "للدفع النقدي؛ فارغ", "for a cash payment, empty"
    LangAdd "متوسط فترة التحصيل", "Average collection period"
    LangAdd "مثال: النخبة. فارغ", "Example: Elite. Empty"
    LangAdd "مجموع الأرصدة (صفر", "Total of the balances (zero"
    LangAdd "مرتجع بيع (رد نقدي", "Sales return (cash refund"
    LangAdd "مستحقة خلال 7 أيام", "Due within 7 days"
End Sub

Private Sub D3_3()
    LangAdd "مستويات على الأكثر", "levels at most"
    LangAdd "منخفضة المخزون فقط", "Low stock only"
    LangAdd "نسخة احتياطية الآن", "Back up now"
    LangAdd "وحدات بيع المنتجات", "Product sale units"
    LangAdd "يومًا عن استحقاقها", "days after its due date"
    LangAdd "أسطر القيد اليدوي", "Manual entry lines"
    LangAdd "أسطر مسير الرواتب", "Payroll lines"
    LangAdd "أنشئ موازنة للسنة", "Create a budget for the year"
    LangAdd "إضافة كل الحسابات", "Add all accounts"
    LangAdd "اختر تاريخًا بعده", "Choose a date after it"
    LangAdd "ارتفاع الملصق (مم", "Label height (mm"
    LangAdd "اضغط لعرض التقرير", "Click to show the report"
    LangAdd "اكتب اسم المستخدم", "Type the user name"
    LangAdd "اكتب النسب الثلاث", "Type the three rates"
    LangAdd "اكتب تاريخ الحركة", "Type the date of the move"
    LangAdd "الإقرار غير معتمد", "The return is not approved"
    LangAdd "الإقرار غير موجود", "The return does not exist"
    LangAdd "الاسم بالإنجليزية", "English name"
    LangAdd "البريد الإلكتروني", "E-mail"
    LangAdd "التاريخ بعد اليوم", "The date is after today"
    LangAdd "التقرير غير موجود", "The report does not exist"
    LangAdd "الحد الأعلى للأجر", "Maximum wage"
    LangAdd "الحركة غير موجودة", "The move does not exist"
    LangAdd "الحسابات الختامية", "Financial statements"
    LangAdd "الخزينة / الصندوق", "Treasury / box"
    LangAdd "الخزينة والصناديق", "Treasury and boxes"
    LangAdd "الرصيد في الدفاتر", "Balance in the books"
    LangAdd "الشاشة غير موجودة", "The screen does not exist"
    LangAdd "الشيك تحت التحصيل", "Cheque under collection"
    LangAdd "الصافي بدون ضريبة", "Net without VAT"
    LangAdd "العمولات المستحقة", "Commissions payable"
    LangAdd "الفرق عن الموازنة", "Difference from budget"
    LangAdd "الفواتير المفتوحة", "Open invoices"
    LangAdd "القيمة بسعر البيع", "Value at sale price"
    LangAdd "المبلغ مع الضريبة", "Amount with VAT"
    LangAdd "المبيعات حسب فترة", "Sales by period"
    LangAdd "المحاسبة والمالية", "Accounting and finance"
    LangAdd "المستند غير موجود", "The document does not exist"
    LangAdd "المسير غير مرحَّل", "The run is not posted"
    LangAdd "المشتريات المعفاة", "Exempt purchases"
    LangAdd "المصروفات (تفصيلي", "Expenses (detailed"
    LangAdd "المطاعم (شاشة لمس", "Restaurants (touch screen"
    LangAdd "المقارنة: المجموع", "Comparison: total"
    LangAdd "الهامش الأيسر (مم", "Left margin (mm"
    LangAdd "الهامش الأيمن (مم", "Right margin (mm"
    LangAdd "الهامش السفلي (مم", "Bottom margin (mm"
    LangAdd "الهامش العلوي (مم", "Top margin (mm"
    LangAdd "تحويل إلى بنك آخر", "Transfer to another bank"
    LangAdd "تسوية تحصيلات مدى", "Settlement of Mada collections"
    LangAdd "تعذر تحديث القيود", "Could not refresh the entries"
    LangAdd "تعذر حفظ الفاتورة", "Could not save the invoice"
    LangAdd "تغيير كلمة المرور", "Change password"
    LangAdd "تم اعتماد الإقرار", "The return was approved"
    LangAdd "تمت الإضافة للطلب", "Added to the order"
    LangAdd "حذف قيد إهلاك شهر", "Delete the depreciation entry of the month"
    LangAdd "حذف مسودة الإقرار", "Delete the draft of the return"
    LangAdd "حفظ نسب التأمينات", "Save the social insurance rates"
    LangAdd "رصيد الصندوق الآن", "Box balance now"
    LangAdd "رقم فاتورة المورد", "Supplier invoice number"
    LangAdd "سبب الإرجاع مطلوب", "The return reason is required"
    LangAdd "سجّل الدخول أولًا", "Log in first"
    LangAdd "سند قبض / سند صرف", "Receipt voucher / payment voucher"
    LangAdd "شيكات تحت التحصيل", "Cheques under collection"
    LangAdd "صادر آخر من البنك", "Other outgoing from the bank"
    LangAdd "صافي ضريبة الفترة", "Net VAT of the period"
    LangAdd "غير مسجل بالضريبة", "Not registered for VAT"
    LangAdd "فاتورة المورد رقم", "Supplier invoice number"
    LangAdd "قسط السلفة الشهري", "Monthly advance installment"
    LangAdd "لا توجد شهادة بعد", "No certificate yet"
    LangAdd "لم تُحدد الفاتورة", "The invoice was not set"
    LangAdd "مثال: 38 أو 40 أو", "Example: 38 or 40 or"
    LangAdd "مجلد صور المنتجات", "Product pictures folder"
    LangAdd "مستند مفتوح. اختر", "An open document. Choose"
    LangAdd "نسبة الضريبة ليست", "The VAT rate is not"
    LangAdd "و - لتعديل الكمية", "and - to change the quantity"
    LangAdd "يسمح بالبيع الآجل", "Allows credit sales"
    LangAdd "يُولَّد عند الحفظ", "Generated when saved"
    LangAdd "آخر حركات المنتج", "Latest product moves"
    LangAdd "إجمالي المشتريات", "Total purchases"
    LangAdd "إرسال كل المعلّق", "Send all pending"
    LangAdd "إقفال الفترة حتى", "Close the period up to"
    LangAdd "إلى بنك (التحويل", "To bank (transfer"
    LangAdd "إنشاء مسير الشهر", "Create the run of the month"
    LangAdd "احفظ السجل أولًا", "Save the record first"
    LangAdd "اختر تاريخًا قبل", "Choose a date before"
    LangAdd "اختر جهة الترحيل", "Choose where to transfer"
    LangAdd "اختر قيدًا أولًا", "Choose an entry first"
    LangAdd "اختر مصدر الشراء", "Choose the purchase source"
    LangAdd "اختر نوع المصروف", "Choose the expense type"
    LangAdd "اكتب تاريخ الصرف", "Type the payment date"
    LangAdd "اكتب تاريخ القيد", "Type the date of the entry"
    LangAdd "الأجهزة المفعّلة", "Activated computers"
    LangAdd "الأصل غير مستبعد", "The asset is not disposed"
    LangAdd "الاستحقاق التالي", "Next due date"
    LangAdd "الباركود المطبوع", "Printed barcode"
    LangAdd "الباركود والنصوص", "Barcode and texts"
    LangAdd "البدلات والإضافي", "Allowances and overtime"
    LangAdd "البيئة التجريبية", "Test environment"
    LangAdd "الخزينة الرئيسية", "Main treasury"
    LangAdd "الخزينة المستلمة", "Receiving treasury"
    LangAdd "الرصيد الافتتاحي", "Opening balance"
    LangAdd "السعر بدون ضريبة", "Price without VAT"
    LangAdd "العمولة المتوقعة", "Expected commission"
    LangAdd "العميل غير موجود", "The customer does not exist"
    LangAdd "الفترة مقفلة حتى", "The period is closed up to"
    LangAdd "المبيعات الشهرية", "Monthly sales"
    LangAdd "المبيعات المعفاة", "Exempt sales"
    LangAdd "المبيعات اليومية", "Daily sales"
    LangAdd "المخزون يكفي نحو", "The stock is enough for about"
    LangAdd "المركز الافتراضي", "Default center"
    LangAdd "المسير غير مصروف", "The run is not paid"
    LangAdd "المسير ليس مسودة", "The run is not a draft"
    LangAdd "المقارنة: الحساب", "Comparison: account"
    LangAdd "المنتج غير موجود", "The product does not exist"
    LangAdd "المورد الافتراضي", "Default supplier"
    LangAdd "الواردة والصادرة", "Received and issued"
    LangAdd "تحويل بين البنوك", "Transfer between banks"
    LangAdd "تسويات هذا البنك", "Reconciliations of this bank"
    LangAdd "تصنيفات المنتجات", "Product categories"
    LangAdd "تعذر إقفال السنة", "The year could not be closed"
End Sub

Private Sub D3_4()
    LangAdd "تعذر إنشاء الجرد", "The count could not be created"
    LangAdd "تعذر ترحيل الجرد", "Could not post the count"
    LangAdd "تعذر حفظ التصفية", "Could not save the closing"
    LangAdd "تعذر حفظ المرتجع", "Could not save the return"
    LangAdd "تعذر فتح التقرير", "Could not open the report"
    LangAdd "تفعيل هذا الجهاز", "Activate this computer"
    LangAdd "تم حفظ سند الصرف", "The payment voucher was saved"
    LangAdd "تم حفظ سند القبض", "The receipt voucher was saved"
    LangAdd "تم فك قفل الحساب", "The account was unlocked"
    LangAdd "توجد موازنة لسنة", "A budget for the year"
    LangAdd "توزيع على الأشهر", "Spread over the months"
    LangAdd "حذف مسودة المسير", "Delete the draft of the run"
    LangAdd "حركة بنكية جديدة", "New bank transaction"
    LangAdd "خصم على الفاتورة", "Invoice discount"
    LangAdd "راجع مدير النظام", "Ask the system administrator"
    LangAdd "رصيد المنتج سالب", "The product balance is negative"
    LangAdd "رصيد دائن مرحَّل", "Carried credit balance"
    LangAdd "رقم أو اسم السجل", "Number or name of the record"
    LangAdd "رقم فاتورة البيع", "Sales invoice number"
    LangAdd "زيادة في الصندوق", "Overage in the box"
    LangAdd "سعر الحجم الكبير", "Large size price"
    LangAdd "صافي خسارة السنة", "Net loss of the year"
    LangAdd "طباعة حركة اليوم", "Print the moves of the day"
    LangAdd "طباعة كشف الحساب", "Print the statement"
    LangAdd "عاد المسير مسودة", "The run is a draft again"
    LangAdd "عمليات المستندات", "Document transactions"
    LangAdd "عمولات المندوبين", "Sales rep commissions"
    LangAdd "عن فاتورة الشراء", "for the purchase invoice"
    LangAdd "غير مسموح بالآجل", "Credit not allowed"
    LangAdd "لم يُقبل المستند", "The document was not accepted"
    LangAdd "مجمع إهلاك الأصل", "Accumulated depreciation of the asset"
    LangAdd "محاكاة (السعودية", "Simulation (Saudi Arabia"
    LangAdd "مردودات المبيعات", "Sales returns"
    LangAdd "مستحقات الموردين", "Supplier payables"
    LangAdd "مستخدمة لسجل آخر", "is used by another record"
    LangAdd "مسودة (غير معتمد", "Draft (not approved"
    LangAdd "من بداية الصندوق", "since the box started"
    LangAdd "من صلاحيات الدور", "From the role permissions"
    LangAdd "نظام إدارة المحل", "Store management system"
    LangAdd "نقطة بيع الكافيه", "Cafe point of sale"
    LangAdd "هل تريد المتابعة", "Do you want to continue"
    LangAdd "وتاريخ الاستحقاق", "and the due date"
    LangAdd "يظهر للمبرمج فقط", "Shown to the developer only"
    LangAdd "آخر مصروف أُنشئ", "Last expense created"
    LangAdd "أكبر من المتبقي", "more than the remaining"
    LangAdd "أنواع المصروفات", "Expense types"
    LangAdd "أهداف المندوبين", "Sales rep targets"
    LangAdd "أول صندوق كاشير", "First cashier box"
    LangAdd "أيام عدم الحركة", "Days without moves"
    LangAdd "إجمالي العمولات", "Total commissions"
    LangAdd "إجمالي المبيعات", "Total sales"
    LangAdd "إظهار غير النشط", "Show inactive"
    LangAdd "إعادة فتح السنة", "Reopen the year"
    LangAdd "إلغاء الاستبعاد", "Cancel the disposal"
    LangAdd "إيداع من المالك", "Deposit from the owner"
    LangAdd "اختر حساب الأصل", "Choose the asset account"
    LangAdd "اختر نوع الحركة", "Choose the move type"
    LangAdd "اكتب بيان القيد", "Type the description of the entry"
    LangAdd "الإقرار الضريبي", "VAT return"
    LangAdd "البنك الافتراضي", "Default bank"
    LangAdd "التسوية البنكية", "Bank reconciliation"
    LangAdd "الحركات البنكية", "Bank transactions"
    LangAdd "الحركات المسجلة", "Recorded moves"
    LangAdd "الحساب مقفل حتى", "The account is locked until"
    LangAdd "الحفظ والاعتماد", "Save and approve"
    LangAdd "السبب / ملاحظات", "Reason / notes"
    LangAdd "السند غير موجود", "The voucher does not exist"
    LangAdd "الشيك غير موجود", "The cheque does not exist"
    LangAdd "الصندوق غير نشط", "The box is not active"
    LangAdd "الضريبة بالعملة", "VAT in currency"
    LangAdd "العميل (اختياري", "Customer (optional"
    LangAdd "العميل / المورد", "Customer / supplier"
    LangAdd "الفترة: المجموع", "Period: total"
    LangAdd "الفروع والأقسام", "Branches and departments"
    LangAdd "القوائم المالية", "Financial statements"
    LangAdd "القيد غير موجود", "The entry does not exist"
    LangAdd "القيمة الدفترية", "Book value"
    LangAdd "القيمة المتبقية", "Residual value"
    LangAdd "القيمة بالتكلفة", "Value at cost"
    LangAdd "الكمية المرتجعة", "Quantity returned"
    LangAdd "الكمية المشتراة", "Quantity bought"
    LangAdd "المبلغ المرحَّل", "Transferred amount"
    LangAdd "المحلات (باركود", "Shops (barcode"
    LangAdd "المرجع (اختياري", "Reference (optional"
    LangAdd "المسير بلا أسطر", "The run has no lines"
    LangAdd "النسبة بين 0% و", "The rate is between 0% and"
    LangAdd "النسخ الاحتياطي", "Backup"
    LangAdd "بانتظار الإرسال", "Waiting to be sent"
    LangAdd "بحث (رقم / بيان", "Search (number / description"
    LangAdd "تاريخ كشف البنك", "Bank statement date"
    LangAdd "تسوية مع المالك", "Settlement with the owner"
    LangAdd "تعذر الحذف (خطأ", "Could not delete (error"
    LangAdd "تعذر حفظ الحركة", "Could not save the move"
    LangAdd "تعذرت الاستعادة", "Restore failed"
    LangAdd "تعيين كلمة مرور", "Set a password"
    LangAdd "تم ترحيل المسير", "The run was posted"
    LangAdd "تم حفظ الفاتورة", "The invoice was saved"
    LangAdd "رصيد الصندوق في", "Box balance on"
    LangAdd "رقم جهاز العميل", "Customer computer number"
    LangAdd "سعر الحجم الوسط", "Medium size price"
    LangAdd "سند تحويل نقدية", "Cash transfer voucher"
    LangAdd "سند قبض من عميل", "Customer receipt voucher"
    LangAdd "سُدِّدت من حساب", "paid from the account"
    LangAdd "صرف عمولة مندوب", "Sales rep commission payment"
    LangAdd "صلاحيات الأدوار", "Role permissions"
    LangAdd "صلاحيات الشاشات", "Screen permissions"
    LangAdd "طريقة الاسترداد", "Refund method"
    LangAdd "طريقة رد المبلغ", "Method of refunding the amount"
    LangAdd "عرض أرفع خط (مم", "Narrowest bar width (mm"
    LangAdd "فتح أصل العملية", "Open the source transaction"
    LangAdd "في مسير الرواتب", "On payroll"
    LangAdd "لا خصوم متداولة", "No current liabilities"
    LangAdd "لا يوجد مندوبون", "No sales reps"
    LangAdd "مدة السداد (يوم", "Payment terms (days"
    LangAdd "مركز قيد عمولته", "Center of his commission entry"
    LangAdd "مستخدم البرنامج", "Program user"
    LangAdd "معفى من الضريبة", "Exempt from VAT"
    LangAdd "ملصقات الباركود", "Barcode labels"
    LangAdd "ملف XML لفاتورة", "XML file of an invoice"
    LangAdd "نسبة مجمل الربح", "Gross profit ratio"
End Sub

Private Sub D3_5()
    LangAdd "نقطة بيع المطعم", "Restaurant point of sale"
    LangAdd "هل تريد الترحيل", "Do you want to post"
    LangAdd "يبقى في الصندوق", "Stays in the box"
    LangAdd "أحرف (ISO) مثل", "letters (ISO) such as"
    LangAdd "أحرف على الأقل", "characters at least"
    LangAdd "أداء المندوبين", "Sales rep performance"
    LangAdd "أرصدة الموردين", "Supplier balances"
    LangAdd "أقل من التكلفة", "below cost"
    LangAdd "إعدادات الملصق", "Label settings"
    LangAdd "إلغاء الاعتماد", "Cancel approval"
    LangAdd "إلغاء المطابقة", "Unmatch"
    LangAdd "إيداع في البنك", "Deposit in the bank"
    LangAdd "إيرادات النشاط", "Operating revenue"
    LangAdd "اختر بند الصرف", "Choose the payment item"
    LangAdd "اختر بند القبض", "Choose the receipt item"
    LangAdd "اعتماد الإقرار", "Approve the return"
    LangAdd "اعتماد التسوية", "Approve the reconciliation"
    LangAdd "اقتراحات جديدة", "New suggestions"
    LangAdd "اكتب اسم الأصل", "Type the asset name"
    LangAdd "اكتب رقم الشيك", "Type the cheque number"
    LangAdd "الأصول الثابتة", "Fixed assets"
    LangAdd "الإجمالي: مدين", "Total: debit"
    LangAdd "الإرجاع للمورد", "Return to the supplier"
    LangAdd "الإضافة والحفظ", "Add and save"
    LangAdd "الإهلاك الشهري", "Monthly depreciation"
    LangAdd "الاسم بالعربية", "Arabic name"
    LangAdd "البيئة الفعلية", "Production environment"
    LangAdd "الجهة / البيان", "Party / description"
    LangAdd "الحساب الرئيسي", "Main account"
    LangAdd "الخاضع للضريبة", "Taxable"
    LangAdd "الدخول والخروج", "Login and logout"
    LangAdd "الراتب الأساسي", "Basic salary"
    LangAdd "الربح التشغيلي", "Operating profit"
    LangAdd "الرصيد الختامي", "Closing balance"
    LangAdd "الرصيد المستحق", "Balance due"
    LangAdd "الرصيد بالعملة", "Balance in currency"
    LangAdd "الرقم التسلسلي", "Serial number"
    LangAdd "الشيك مستحق في", "The cheque is due on"
    LangAdd "الفئة الضريبية", "VAT category"
    LangAdd "الفترة الحالية", "Current period"
    LangAdd "الفترة: الحساب", "Period: account"
    LangAdd "الفرق مع الكشف", "Difference with the statement"
    LangAdd "القيود اليدوية", "Manual entries"
    LangAdd "الكمية الحالية", "Current quantity"
    LangAdd "الكمية الفعلية", "Actual quantity"
    LangAdd "الكمية المباعة", "Quantity sold"
    LangAdd "الكمية المسجلة", "Recorded quantity"
    LangAdd "المبلغ المدفوع", "Amount paid"
    LangAdd "المبلغ المربوط", "Linked amount"
    LangAdd "المبلغ المستلم", "Amount received"
    LangAdd "المتاح للإرجاع", "Available to return"
    LangAdd "المخزون الحالي", "Current stock"
    LangAdd "المستحق للمورد", "Due to the supplier"
    LangAdd "المستخدم (فارغ", "User (empty"
    LangAdd "المسمى الوظيفي", "Job title"
    LangAdd "المعمول بها في", "applied in"
    LangAdd "بمتوسط التكلفة", "at average cost"
    LangAdd "تاريخ الاعتماد", "Approval date"
    LangAdd "تاريخ الفاتورة", "Invoice date"
    LangAdd "تحصيل في البنك", "Collection in the bank"
    LangAdd "تذييل الفاتورة", "Invoice footer"
    LangAdd "تسجيل شيك جديد", "Record a new cheque"
    LangAdd "تعذر حفظ السند", "Could not save the voucher"
    LangAdd "تعذر حفظ الشيك", "Could not save the cheque"
    LangAdd "تعذر حفظ القيد", "Could not save the entry"
    LangAdd "تفاصيل العملية", "Transaction details"
    LangAdd "تفعيل البرنامج", "Program activation"
    LangAdd "تكلفة المبيعات", "Cost of sales"
    LangAdd "تم إقفال السنة", "The year was closed"
    LangAdd "تم إلغاء الصرف", "The payment was cancelled"
    LangAdd "تم الحفظ بنجاح", "Saved successfully"
    LangAdd "تم ترحيل الجرد", "The count was posted"
    LangAdd "تم تسجيل إهلاك", "Depreciation recorded for"
    LangAdd "تم تسجيل الشيك", "The cheque was recorded"
    LangAdd "تم تعطيل السجل", "The record was deactivated"
    LangAdd "تم حفظ التصفية", "The closing was saved"
    LangAdd "تم حفظ التعديل", "The change was saved"
    LangAdd "تم حفظ المرتجع", "The return was saved"
    LangAdd "جزاءات وخصومات", "Penalties and deductions"
    LangAdd "حد إعادة الطلب", "Reorder level"
    LangAdd "خيارات المشروب", "Drink options"
    LangAdd "رسالة المنظومة", "Platform message"
    LangAdd "رصيد آخر المدة", "Closing balance"
    LangAdd "رصيد آخر اليوم", "Balance at the end of the day"
    LangAdd "رصيد أول المدة", "Opening balance"
    LangAdd "رصيد أول اليوم", "Balance at the start of the day"
    LangAdd "رواتب الموظفين", "Employee salaries"
    LangAdd "سداد سلفة موظف", "Employee advance repayment"
    LangAdd "شاشات المستخدم", "User screens"
    LangAdd "صافي تسوية مدى", "Net Mada settlement"
    LangAdd "صافي ربح السنة", "Net profit of the year"
    LangAdd "ضريبة المخرجات", "Output VAT"
    LangAdd "ضريبة المدخلات", "Input VAT"
    LangAdd "طابعة الملصقات", "Label printer"
    LangAdd "طباعة الباركود", "Print barcodes"
    LangAdd "طباعة المقارنة", "Print the comparison"
    LangAdd "طريقة الاستلام", "Receipt method"
    LangAdd "عجز في الصندوق", "Shortage in the box"
    LangAdd "عرض الملصق (مم", "Label width (mm"
    LangAdd "عرض في اليومية", "Show in the journal"
    LangAdd "عميل عليه رصيد", "Customer with a balance"
    LangAdd "فاتورة مشتريات", "Purchase invoice"
    LangAdd "قيد مُحدَّث، و", "updated entries, and"
    LangAdd "لا تملك صلاحية", "You do not have the permission"
    LangAdd "لا توجد حسابات", "There are no accounts"
    LangAdd "ما ينطبق عليها", "what applies to them"
    LangAdd "مثال: 2% تُكتب", "Example: 2% is typed"
    LangAdd "مستحق للموردين", "Due to suppliers"
    LangAdd "مصروف (سند صرف", "Expense (payment voucher"
    LangAdd "مقبول مع تحذير", "Accepted with a warning"
    LangAdd "من مسار النظام", "from the system path"
    LangAdd "منخفضة المخزون", "Low stock"
    LangAdd "موظف   الرواتب", "employees   Salaries"
    LangAdd "ميزان المراجعة", "Trial balance"
    LangAdd "نوع مصروف جديد", "New expense type"
    LangAdd "وارد آخر للبنك", "Other incoming to the bank"
    LangAdd "يحسبه البرنامج", "Calculated by the program"
    LangAdd "يوجد جرد مفتوح", "There is an open count"
    LangAdd "يوجد مسير لشهر", "A run for the month"
    LangAdd "يُصرف من صندوق", "Paid from box"
End Sub

Private Sub D3_6()
    LangAdd "يُقبض في صندوق", "Received in box"
    LangAdd "أرصدة العملاء", "Customer balances"
    LangAdd "أسطر الفاتورة", "Invoice lines"
    LangAdd "أسطر الملصقات", "Label lines"
    LangAdd "أسطر الموازنة", "Budget lines"
    LangAdd "أسعار العملات", "Exchange rates"
    LangAdd "أقصى نسبة خصم", "Maximum discount rate"
    LangAdd "أقل من المبلغ", "less than the amount"
    LangAdd "أكبر من قيمته", "more than its value"
    LangAdd "إجمالي الأصول", "Total assets"
    LangAdd "إجمالي الخارج", "Total out"
    LangAdd "إجمالي الخصوم", "Total liabilities"
    LangAdd "إجمالي الدائن", "Total credit"
    LangAdd "إجمالي الداخل", "Total in"
    LangAdd "إجمالي المدين", "Total debit"
    LangAdd "إرسال المختار", "Send selected"
    LangAdd "إعادة الإنشاء", "Rebuild"
    LangAdd "إعادة فتح سنة", "Reopen a year"
    LangAdd "إقفال الفترات", "Period closing"
    LangAdd "إلغاء الترحيل", "Unpost"
    LangAdd "اختر المستخدم", "Choose the user"
    LangAdd "اقتراح للفارغ", "Suggest for empty"
    LangAdd "الباقي للعميل", "Change for the customer"
    LangAdd "البحث المتقدم", "Advanced search"
    LangAdd "البنك غير نشط", "The bank is not active"
    LangAdd "الجهة المصدرة", "Issuer"
    LangAdd "الحساب الدائن", "Credit account"
    LangAdd "الرصيد الحالي", "Current balance"
    LangAdd "الرصيد الموجب", "A positive balance"
    LangAdd "الرقم الإضافي", "Additional number"
    LangAdd "الرقم الضريبي", "VAT number"
    LangAdd "الرمز البريدي", "Postal code"
    LangAdd "الرمز المختصر", "Symbol"
    LangAdd "السجل التجاري", "Commercial registration"
    LangAdd "السنة الماضية", "Last year"
    LangAdd "الشخص المسؤول", "Contact person"
    LangAdd "العملية (فارغ", "Transaction (empty"
    LangAdd "القائم بالجرد", "Counted by"
    LangAdd "المبلغ المسدد", "Amount paid"
    LangAdd "المسترد نقدًا", "Refunded in cash"
    LangAdd "المفتاح الخاص", "Private key"
    LangAdd "بداية الإهلاك", "Depreciation start"
    LangAdd "بصمة الفاتورة", "Invoice hash"
    LangAdd "بيئة المحاكاة", "Simulation environment"
    LangAdd "بيع / استبعاد", "Sale / disposal"
    LangAdd "تاريخ التعيين", "Hire date"
    LangAdd "تاريخ التفعيل", "Activation date"
    LangAdd "تاريخ العملية", "Transaction date"
    LangAdd "تاريخ المصروف", "Expense date"
    LangAdd "تحديث القائمة", "Refresh list"
    LangAdd "تسجيل الشيكات", "Cheque register"
    LangAdd "تصحيحات سابقة", "Earlier corrections"
    LangAdd "تعذّر الإرسال", "Could not send"
    LangAdd "تفعيل الإرسال", "Enable sending"
    LangAdd "تقرير المخزون", "Stock report"
    LangAdd "تقرير النواقص", "Shortage report"
    LangAdd "تم حفظ الحركة", "The move was saved"
    LangAdd "تُدفع بالكامل", "Paid in full"
    LangAdd "ثمن بيع الأصل", "Sale price of the asset"
    LangAdd "حفظ الصلاحيات", "Save the permissions"
    LangAdd "دليل الحسابات", "Chart of accounts"
    LangAdd "ربح بيع الأصل", "Gain on sale of the asset"
    LangAdd "ربط بالفاتورة", "Link to the invoice"
    LangAdd "سند صرف عمولة", "Commission payment voucher"
    LangAdd "سند صرف لمورد", "Supplier payment voucher"
    LangAdd "سند صرف نقدية", "Cash payment voucher"
    LangAdd "سند قبض نقدية", "Cash receipt voucher"
    LangAdd "شجرة الحسابات", "Account tree"
    LangAdd "شراء أصل ثابت", "Purchase of a fixed asset"
    LangAdd "شهادة تجريبية", "Test certificate"
    LangAdd "صافي المبيعات", "Net sales"
    LangAdd "صلاحيات الدور", "Role permissions"
    LangAdd "صندوق النقدية", "Cash box"
    LangAdd "صُرف من صندوق", "Paid from box"
    LangAdd "ضريبة العمولة", "Fee VAT"
    LangAdd "طباعة القائمة", "Print the list"
    LangAdd "طباعة اليومية", "Print the journal"
    LangAdd "عدد المحاولات", "Number of attempts"
    LangAdd "عملة البرنامج", "Program currency"
    LangAdd "عمولات مستحقة", "Commissions payable"
    LangAdd "عنوان التوصيل", "Delivery address"
    LangAdd "فات استحقاقها", "Overdue"
    LangAdd "فاتورة المورد", "Supplier invoice"
    LangAdd "فاتورة ضريبية", "Tax invoice"
    LangAdd "فاتورة متأخرة", "has an invoice late by"
    LangAdd "فتح قيد محفوظ", "Open a saved entry"
    LangAdd "فترة المقارنة", "Comparison period"
    LangAdd "فواتير الشراء", "Purchase invoices"
    LangAdd "قيد يومية رقم", "Journal entry number"
    LangAdd "كشف حساب عميل", "Customer statement"
    LangAdd "كشف حساب مورد", "Supplier statement"
    LangAdd "لا توجد نواقص", "There are no shortages"
    LangAdd "لا يوجد صندوق", "No box"
    LangAdd "متوسط التكلفة", "Average cost"
    LangAdd "مثال: الدولار", "Example: the dollar"
    LangAdd "مراكز التكلفة", "Cost centers"
    LangAdd "مرتجع مشتريات", "Purchase return"
    LangAdd "مرحَّل ومصروف", "Posted and paid"
    LangAdd "مركز التقارير", "Report center"
    LangAdd "مسودة الإقرار", "Draft return"
    LangAdd "مصروف بإجمالي", "expenses totalling"
    LangAdd "مصروفات الشهر", "Expenses of the month"
    LangAdd "مطابقة المحدد", "Match the selected"
    LangAdd "معامل التحويل", "Exchange rate"
    LangAdd "مقفلة حتى يوم", "Closed up to the day"
    LangAdd "ملء من الفعلي", "Fill from actuals"
    LangAdd "نسخة احتياطية", "Backup"
    LangAdd "ونسبة الضريبة", "and the VAT rate"
    LangAdd "يتابع المخزون", "Tracks stock"
    LangAdd "يوم الاستحقاق", "Due day"
    LangAdd "آخر سعر شراء", "Last purchase price"
    LangAdd "آخر شهر مسجل", "Last recorded month"
    LangAdd "آيبان الموظف", "Employee IBAN"
    LangAdd "أساس العمولة", "Commission base"
    LangAdd "أسطر المرتجع", "Return lines"
    LangAdd "أعمار الديون", "Aging"
    LangAdd "أكبر من الحد", "more than the limit"
    LangAdd "أمين الصندوق", "Cashier"
    LangAdd "أيام التأخير", "Days late"
    LangAdd "إلغاء الحالة", "Cancel the status"
End Sub

Private Sub D3_7()
    LangAdd "إلغاء السداد", "Cancel the payment"
    LangAdd "إنشاء موازنة", "Create a budget"
    LangAdd "إيرادات أخرى", "Other revenue"
    LangAdd "اختر الصندوق", "Choose the box"
    LangAdd "اختر المندوب", "Choose the sales rep"
    LangAdd "استرداد نقدي", "Cash refund"
    LangAdd "اسم المستخدم", "User name"
    LangAdd "الجدول (فارغ", "Table (empty"
    LangAdd "الربط المسجل", "Recorded link"
    LangAdd "الربع الماضي", "Last quarter"
    LangAdd "الرصيد بعدها", "Balance after it"
    LangAdd "السعر للعميل", "Price for the customer"
    LangAdd "الشهر الماضي", "Last month"
    LangAdd "الفروقات فقط", "Differences only"
    LangAdd "القسط الشهري", "Monthly installment"
    LangAdd "المرحَّل إلى", "Carried to"
    LangAdd "المقارنة: في", "Comparison: on"
    LangAdd "المقارنة: من", "Comparison: from"
    LangAdd "اليوم التالي", "Next day"
    LangAdd "اليوم السابق", "Previous day"
    LangAdd "باقي الأسماء", "Other names"
    LangAdd "بدء جرد جديد", "Start a new count"
    LangAdd "بدون الضريبة", "Without VAT"
    LangAdd "بيع أصل ثابت", "Sale of a fixed asset"
    LangAdd "تاريخ السداد", "Payment date"
    LangAdd "تاريخ الشراء", "Purchase date"
    LangAdd "تحديث القيود", "Refresh entries"
    LangAdd "ترحيل المسير", "Post the run"
    LangAdd "تسجيل الخروج", "Log out"
    LangAdd "تسجيل الدخول", "Log in"
    LangAdd "تسجيل السداد", "Record the payment"
    LangAdd "تعذر التصدير", "Export failed"
    LangAdd "تغيير المجلد", "Change the folder"
    LangAdd "تكلفة الوحدة", "Unit cost"
    LangAdd "تم حذف السطر", "The line was deleted"
    LangAdd "تم حذف الشيك", "The cheque was deleted"
    LangAdd "تم حذف القيد", "The entry was deleted"
    LangAdd "تم حفظ القيد", "The entry was saved"
    LangAdd "جوال التوصيل", "Delivery mobile"
    LangAdd "حالة الإرسال", "Sending status"
    LangAdd "حالة التسوية", "Reconciliation status"
    LangAdd "حذف الموازنة", "Delete the budget"
    LangAdd "خاضع للضريبة", "Taxable"
    LangAdd "خزينة رئيسية", "Main treasury"
    LangAdd "دفتر الأستاذ", "General ledger"
    LangAdd "دولة التشغيل", "Operating country"
    LangAdd "ديون العملاء", "Customer receivables"
    LangAdd "رئيسي / فرعي", "Main / sub"
    LangAdd "رصيد افتتاحي", "Opening balance"
    LangAdd "رصيد البداية", "Starting balance"
    LangAdd "رصيد الصندوق", "Box balance"
    LangAdd "رقم الباركود", "Barcode number"
    LangAdd "رقم الفاتورة", "Invoice number"
    LangAdd "سحب من البنك", "Withdrawal from the bank"
    LangAdd "سعر بيع جديد", "New sale price"
    LangAdd "شامل الضريبة", "Including VAT"
    LangAdd "صافي الرواتب", "Net salaries"
    LangAdd "صنف    العجز", "Item    Shortage"
    LangAdd "صورة التصنيف", "Category picture"
    LangAdd "طباعة الفترة", "Print the period"
    LangAdd "طباعة المسير", "Print the run"
    LangAdd "طباعة باركود", "Print barcodes"
    LangAdd "عدد الملصقات", "Number of labels"
    LangAdd "عدد المنتجات", "Number of products"
    LangAdd "عملة التعامل", "Trading currency"
    LangAdd "فاتورة اليوم", "Invoice of the day"
    LangAdd "فاتورة جديدة", "New invoice"
    LangAdd "فتح وعرض فقط", "Open and view only"
    LangAdd "فروقات الجرد", "Count differences"
    LangAdd "فواتير البيع", "Sales invoices"
    LangAdd "قيمة المخزون", "Stock value"
    LangAdd "قيمة المرتجع", "Return value"
    LangAdd "قيود اليومية", "Journal entries"
    LangAdd "لا توجد قيود", "There are no entries"
    LangAdd "لا يكفي لصرف", "is not enough to pay"
    LangAdd "لعرض فواتيره", "to show his invoices"
    LangAdd "لم يتغير شيء", "Nothing changed"
    LangAdd "لم يُصرف بعد", "not paid yet"
    LangAdd "مبلغ المستند", "Document amount"
    LangAdd "مبيعات الشهر", "Sales of the month"
    LangAdd "مبيعات اليوم", "Sales of the day"
    LangAdd "مجمع الإهلاك", "Accumulated depreciation"
    LangAdd "مدينة العميل", "Customer city"
    LangAdd "مربوط ومرتجع", "Linked and returned"
    LangAdd "مرتجع سابقًا", "Returned before"
    LangAdd "مرتجع مبيعات", "Sales return"
    LangAdd "مركز التكلفة", "Cost center"
    LangAdd "مسودة عمولات", "Commission draft"
    LangAdd "مسير الرواتب", "Payroll"
    LangAdd "مصروفات أخرى", "Other expenses"
    LangAdd "مقفلة بالفعل", "already closed"
    LangAdd "ملف البيانات", "Data file"
    LangAdd "من آخر تصفية", "since the last closing"
    LangAdd "نسبة الضريبة", "VAT rate"
    LangAdd "نسبة العمولة", "Commission rate"
    LangAdd "نهاية الفترة", "End of the period"
    LangAdd "هل أنت متأكد", "Are you sure"
    LangAdd "وحدات القياس", "Units of measure"
    LangAdd "يعود للمخزون", "Back to stock"
    LangAdd "أمين المخزن", "Storekeeper"
    LangAdd "إضافة / حفظ", "Add / Save"
    LangAdd "إضافة للطلب", "Add to order"
    LangAdd "إعادة طباعة", "Reprint"
    LangAdd "إعداد الربط", "Connection setup"
    LangAdd "إقفال السنة", "Year closing"
    LangAdd "إلغاء الجرد", "Cancel the count"
End Sub
