Attribute VB_Name = "modLangData2"
'==============================================================================
' modLangData2  -  Retail Store Management System: part 2 of the Arabic ->
' English dictionary of the interface (modLang). GENERATED FILE - do not edit.
' Source: tools/i18n_en.py  ->  python3 tools/generate.py
'==============================================================================
Option Compare Database
Option Explicit

Public Sub LangData2()
    D2_1
    D2_2
    D2_3
    D2_4
    D2_5
End Sub

Private Sub D2_1()
    LangAdd "لم يتم العثور على منتج بالباركود أو الكود", "No product was found with the barcode or the code"
    LangAdd "ملف المفتاح الخاص غير محدد في إعداد الربط", "The private key file is not set in the connection setup"
    LangAdd "منتج وصلت كميته إلى حد إعادة الطلب أو أقل", "products have reached the reorder level or less"
    LangAdd "هل تريد عرض تقرير المنتجات منخفضة المخزون", "Do you want to show the low-stock products report"
    LangAdd "يغيّرها المستخدم عند أول دخول (كلمة مؤقتة", "The user changes it at the first login (temporary password"
    LangAdd "أدخل النقدية الفعلية الموجودة في الصندوق", "Enter the actual cash in the box"
    LangAdd "احذف قيود الإهلاك من شهر الاستبعاد أولًا", "Delete the depreciation entries from the month of disposal first"
    LangAdd "اختر حساب البنك الذي سُدِّدت منه الضريبة", "Choose the bank account the tax was paid from"
    LangAdd "اختر سطرًا في الجدول واكتب المبلغ السنوي", "Choose a line in the table and type the yearly amount"
    LangAdd "الدائن، ويُرحَّل لقيود اليومية عند الحفظ", "credit, and is posted to the journal entries when saved"
    LangAdd "المشتريات الخاضعة للضريبة (بعد المرتجعات", "Taxable purchases (after returns"
    LangAdd "بيانات دخول جهاز نقطة البيع (Client ID و", "Credentials of the POS device (Client ID and"
    LangAdd "دور مدير النظام يملك كل الصلاحيات دائمًا", "The system administrator role always has all the permissions"
    LangAdd "رفضت المصلحة بيانات جهاز نقطة البيع (رمز", "The Tax Authority refused the POS device data (code"
    LangAdd "سطر المرتجع من فاتورة غير فاتورة المرتجع", "A return line from an invoice other than the invoice of the return"
    LangAdd "على هذا الحساب قيود، فيبقى حسابًا فرعيًا", "This account has entries, so it stays a sub-account"
    LangAdd "كلمتا المرور غير متطابقتين. لم يتغير شيء", "The two passwords do not match. Nothing changed"
    LangAdd "لا يمكنك تعطيل حسابك وأنت مسجل الدخول به", "You cannot deactivate your own account while logged in with it"
    LangAdd "مبلغ مستحق للمورد (بعملة البرنامج دائمًا", "an amount due to the supplier (always in the program currency"
    LangAdd "هذه الشاشة ستكون متاحة بعد تنفيذ المرحلة", "This screen will be available after phase"
    LangAdd "يجب أن يبقى مدير نظام نشط واحد على الأقل", "At least one active system administrator must remain"
    LangAdd "يُقفل ما قبل اليوم فقط: اختر تاريخًا قبل", "Only the days before today are closed: choose a date before"
    LangAdd "اختر أين استُلم ثمن البيع (بنك أو صندوق", "Choose where the sale price was received (bank or box"
    LangAdd "المبيعات الخاضعة للضريبة (بعد المرتجعات", "Taxable sales (after returns"
    LangAdd "المبيعات المحلية الخاضعة للنسبة الصفرية", "Domestic zero-rated sales"
    LangAdd "الميزانية العمومية (قائمة المركز المالي", "Balance sheet (statement of financial position"
    LangAdd "تُقفل السنة بعد انتهائها (بعد 31 ديسمبر", "The year is closed after it ends (after 31 December"
    LangAdd "حدد الكمية المرتجعة لصنف واحد على الأقل", "Set the returned quantity of at least one item"
    LangAdd "راجع التاريخ والأسطر ثم اضغط «حفظ القيد", "Check the date and the lines, then click Save entry"
    LangAdd "سعر البيع الجديد لا يمكن أن يكون سالبًا", "The new sale price cannot be negative"
    LangAdd "عدّل الإضافي والخصومات ثم «ترحيل المسير", "Edit the overtime and deductions, then Post the run"
    LangAdd "كلمة البحث (اسم، كود، باركود، رقم، جوال", "Search text (name, code, barcode, number, mobile"
    LangAdd "لا توجد مصروفات متكررة مستحقة حتى اليوم", "There are no recurring expenses due up to today"
    LangAdd "لا يمكن تفعيل الفاتورة الإلكترونية الآن", "E-invoicing cannot be enabled now"
    LangAdd "مصر: كود الصنف المسجّل في بوابة المصلحة", "Egypt: product code registered on the Tax Authority portal"
    LangAdd "يجب أن يفعّله مدير النظام قبل الاستخدام", "The system administrator must activate it before use"
    LangAdd "أحرف على الأقل، ولا تساوي اسم المستخدم", "characters at least, and not equal to the user name"
    LangAdd "أدخل النقدية الموجودة فعلًا في الصندوق", "Enter the cash actually in the box"
    LangAdd "أضفه في تصحيحات الإقرار التالي (الخانة", "Add it to the corrections of the next return (box"
    LangAdd "أو اترك التاريخ فارغًا لفتح كل الفترات", "or leave the date empty to open all periods"
    LangAdd "إعداد الربط يحتاج صلاحية إعدادات المحل", "The connection setup needs the store settings permission"
    LangAdd "الإقرارات المحفوظة (اختر إقرارًا لعرضه", "Saved returns (choose a return to show it"
    LangAdd "الجرد غير موجود أو تم ترحيله أو إلغاؤه", "The count does not exist or was posted or cancelled"
    LangAdd "الشهادة التجريبية للبيئة التجريبية فقط", "The test certificate is for the test environment only"
    LangAdd "الكمية المرتجعة أكبر من الكمية المباعة", "The returned quantity is more than the quantity sold"
    LangAdd "الكمية المرتجعة أكبر من المتاح للإرجاع", "The returned quantity is more than what can be returned"
    LangAdd "المبلغ أكبر من عمولات المندوب المستحقة", "The amount is more than the commissions payable to the sales rep"
    LangAdd "بيانات المحل الضريبية وإعدادات التشغيل", "Tax data of the store and operating settings"
    LangAdd "ترتيب الزر في شاشة اللمس (الأصغر أولًا", "Order of the button on the touch screen (smallest first"
    LangAdd "ديون العملاء ÷ المبيعات الآجلة اليومية", "Customer receivables / daily credit sales"
    LangAdd "سطر لا ينتمي إلى فاتورة الشراء الأصلية", "A line that does not belong to the original purchase invoice"
    LangAdd "سعودي (التأمينات بحصتي الموظف والمنشأة", "Saudi (social insurance with the employee and employer shares"
    LangAdd "في الأرباح المحتجزة، وتُقفل السنة كلها", "in retained earnings, and the whole year is closed"
    LangAdd "لا تملك صلاحية تسجيل مرتجعات المشتريات", "You do not have the permission to record purchase returns"
    LangAdd "أدخل تاريخ السداد والمبلغ وحساب البنك", "Enter the payment date, the amount and the bank account"
    LangAdd "اختر الحجم والإضافات، ثم «إضافة للطلب", "Choose the size and extras, then Add to order"
    LangAdd "اسم المستخدم أو كلمة المرور غير صحيحة", "The user name or the password is wrong"
    LangAdd "اكتب رمز التحقق (OTP) من بوابة فاتورة", "Enter the verification code (OTP) from the Fatoora portal"
    LangAdd "الكمية المسجلة لا تطابق حركات المخزون", "The recorded quantity does not match the stock moves"
    LangAdd "الكمية يجب أن تكون أكبر من صفر (السطر", "The quantity must be greater than zero (line"
    LangAdd "المقارنة داخل سنة واحدة (موازنة السنة", "Comparison within one year (the budget of the year"
    LangAdd "تاريخ السداد قبل تاريخ اعتماد الإقرار", "The payment date is before the approval date of the return"
    LangAdd "تُحذف المسودة فقط: ألغِ الترحيل أولًا", "Only the draft is deleted: unpost it first"
    LangAdd "حركة الخزينة اليومية (أول اليوم وآخره", "Daily treasury moves (start and end of the day"
    LangAdd "رقم جديد لا يتكرر؛ لا يتغير بعد الحفظ", "A new number that is not repeated, it does not change after saving"
    LangAdd "سجل التدقيق يحتاج صلاحية «سجل التدقيق", "The audit trail needs the permission Audit trail"
    LangAdd "عرض فقط - التصحيح يكون بمرتجع مشتريات", "View only - a correction is made with a purchase return"
    LangAdd "غير نشط. فعّله من شاشة المنتجات أولًا", "is not active. Activate it in the Products screen first"
    LangAdd "فحص سلامة البيانات: لا توجد أي مشكلات", "Data integrity check: no problems at all"
    LangAdd "لا تملك صلاحية اعتماد التسوية البنكية", "You do not have the permission to approve the bank reconciliation"
    LangAdd "لا تملك صلاحية تسجيل فواتير المشتريات", "You do not have the permission to record purchase invoices"
    LangAdd "لا تملك هذه الصلاحية في شاشة الموازنة", "You do not have this permission in the budget screen"
    LangAdd "لا توجد حركة نقدية للاختيارات المحددة", "There is no cash move for the choices made"
    LangAdd "مقفلة بقيد إقفال. أعد فتح السنة أولًا", "closed with a closing entry. Reopen the year first"
    LangAdd "من بداية الصندوق (لا توجد تصفية سابقة", "since the box started (no previous closing"
    LangAdd "هذا سجل أساسي في النظام ولا يمكن حذفه", "This is a system record and cannot be deleted"
    LangAdd "هل تريد إنشاء المصروفات المستحقة الآن", "Do you want to create the due expenses now"
    LangAdd "أرصدة الموردين بالعملات وفروق العملة", "Supplier balances by currency and exchange differences"
    LangAdd "أُنشئ مفتاح وشهادة تجريبية في المجلد", "A test key and certificate were created in the folder"
    LangAdd "إجمالي المصروفات التشغيلية والإدارية", "Total operating and administrative expenses"
    LangAdd "إلغاء سداد الإقرار؟ يُحذف قيد السداد", "Cancel the payment of the return? The payment entry is deleted"
    LangAdd "اكتب سبب إلغاء الاعتماد في الملاحظات", "Type the reason for cancelling the approval in the notes"
    LangAdd "السماح لمدير النظام بتغيير اسم المحل", "Allow the system administrator to change the store name"
    LangAdd "العمولة وضريبتها أقل من مبلغ التسوية", "The fee and its VAT are less than the settled amount"
    LangAdd "الكمية الفعلية لا يمكن أن تكون سالبة", "The actual quantity cannot be negative"
    LangAdd "بالفعل. لإرجاعها استخدم «إعادة الفتح", "already. To undo it use Reopen"
    LangAdd "تسجيل الإهلاك لكل شهر لم يُسجَّل حتى", "Record depreciation for every month not recorded up to"
    LangAdd "تعذّر فحص إعداد الفاتورة الإلكترونية", "Could not check the e-invoicing setup"
    LangAdd "تقارير الخزينة تحتاج صلاحية «الخزينة", "The treasury reports need the permission Treasury"
    LangAdd "رمز الوحدة لدى مصلحة الضرائب المصرية", "Unit code of the Egyptian Tax Authority"
    LangAdd "ستُستبدل كل البيانات الحالية بالنسخة", "All the current data will be replaced by the backup"
    LangAdd "سجل جديد - أدخل البيانات ثم اضغط حفظ", "New record - enter the data, then click Save"
    LangAdd "شامل الضريبة بعد المرتجعات - المجموع", "Including VAT after returns - total"
    LangAdd "صافي ربح (خسارة) الفترات غير المقفلة", "Net profit (loss) of the periods not closed"
    LangAdd "ضريبة مستردة (تُرحَّل للإقرار التالي", "Refundable VAT (carried to the next return"
    LangAdd "طلبات المستند المختار وردود المنظومة", "Requests of the selected document and the replies of the platform"
    LangAdd "كلمة المرور غير صحيحة. تم قفل الحساب", "The password is wrong. The account was locked"
    LangAdd "كلمة المرور لا تبدأ ولا تنتهي بمسافة", "The password does not start or end with a space"
    LangAdd "لا تملك صلاحية تعديل التسوية البنكية", "You do not have the permission to edit the bank reconciliation"
    LangAdd "لا توجد إيرادات أو مصروفات في الفترة", "There is no revenue or expense in the period"
    LangAdd "لا يوجد قيد تسوية: الإقرار غير معتمد", "No settlement entry: the return is not approved"
    LangAdd "ليست لديك صلاحية تصفية يومية الكاشير", "You do not have the permission for the daily cashier closing"
    LangAdd "مستحق الآن: اضغط «إنشاء المستحق الآن", "Due now: click Create the due now"
    LangAdd "نهائيًا؟ يُحذف قيده من اليومية أيضًا", "for good? Its journal entry is deleted too"
    LangAdd "ويمكنك التصفية حسب الاختيار (اختياري", "and you can filter by the choice (optional"
    LangAdd "أدخل بداية الفترة الضريبية ونهايتها", "Enter the start and end of the tax period"
    LangAdd "إعداد ربط منظومة الإيصال الإلكتروني", "E-receipt connection setup"
    LangAdd "اعتمد الإقرار أولًا، ثم سجّل السداد", "Approve the return first, then record the payment"
    LangAdd "الأصول المتداولة ÷ الخصوم المتداولة", "Current assets / current liabilities"
    LangAdd "السبب / ملاحظات (مطلوب لإعادة الفتح", "Reason / notes (required to reopen"
    LangAdd "العملية غير موجودة أو مطابقة من قبل", "The transaction does not exist or is already matched"
    LangAdd "القيمة المدخلة غير صحيحة لهذا الحقل", "The value entered is not valid for this field"
    LangAdd "تغيير اسم المحل يتم عن طريق المبرمج", "The store name is changed by the developer"
    LangAdd "حساب رئيسي: يشمل كل حساباته التابعة", "Main account: includes all its sub-accounts"
    LangAdd "رصيد العميل المسجل لا يطابق الحركات", "The recorded customer balance does not match the moves"
    LangAdd "رصيد المورد المسجل لا يطابق الحركات", "The recorded supplier balance does not match the moves"
    LangAdd "ضريبة مستردة تُرحَّل للإقرار التالي", "Refundable VAT carried to the next return"
    LangAdd "لا تملك صلاحية تعديل المخزون يدويًا", "You do not have the permission to adjust the stock by hand"
    LangAdd "للمبرمج: توليد كود تفعيل لجهاز عميل", "For the developer: generate an activation code for a customer computer"
    LangAdd "مستحقة خلال 7 أيام أو فات استحقاقها", "Due within 7 days or overdue"
End Sub

Private Sub D2_2()
    LangAdd "اكتب التاريخ والمعامل (أكبر من صفر", "Type the date and the rate (greater than zero"
    LangAdd "الأصل مستبعد: ألغِ الاستبعاد أولًا", "The asset is disposed: cancel the disposal first"
    LangAdd "العمولة وضريبتها لا تكونان سالبتين", "The fee and its VAT are never negative"
    LangAdd "المصروف بعملة أخرى: اكتب مبلغه بها", "An expense in another currency: type its amount in it"
    LangAdd "تسجيل ارتداد الشيك؟ يعود مبلغه على", "Record the bounce of the cheque? Its amount goes back to"
    LangAdd "تم الدخول إلى منظومة المصلحة بنجاح", "Logged in to the Tax Authority system"
    LangAdd "رقم التسجيل الضريبي في مصر 9 أرقام", "The Egyptian tax registration number has 9 digits"
    LangAdd "رقم التسجيل الضريبي للمحل (9 أرقام", "Tax registration number of the store (9 digits"
    LangAdd "فحص سلامة البيانات: لا توجد مشكلات", "Data integrity check: no problems"
    LangAdd "لا تملك صلاحية المندوبين وعمولاتهم", "You do not have the permission for sales reps and their commissions"
    LangAdd "لا تملك صلاحية حذف الحركات البنكية", "You do not have the permission to delete bank transactions"
    LangAdd "لا توجد أرصدة موردين بعملات أجنبية", "There are no supplier balances in foreign currencies"
    LangAdd "لا تُسجَّل دفعات على العميل النقدي", "No payments are recorded on the cash customer"
    LangAdd "مبيعاته ومسير راتبه على هذا المركز", "His sales and payroll are on this center"
    LangAdd "نوع الحركة غير متاح للإدخال اليدوي", "The move type is not available for manual entry"
    LangAdd "هذا الحساب معطّل. راجع مدير النظام", "This account is disabled. Ask the system administrator"
    LangAdd "أدخل تاريخ البداية وتاريخ النهاية", "Enter the start date and the end date"
    LangAdd "إلى تاريخ (الميزانية في هذا اليوم", "To date (the balance sheet on this day"
    LangAdd "اختر آخر يوم في الفترة التي تُقفل", "Choose the last day of the period to close"
    LangAdd "اطلب شهادة الامتثال أولًا (الخطوة", "Request the compliance certificate first (step"
    LangAdd "اكتب كلمة المرور مرة أخرى للتأكيد", "Type the password again to confirm"
    LangAdd "الإقرار غير موجود أو معتمد بالفعل", "The return does not exist or is already approved"
    LangAdd "البرنامج غير مفعّل على هذا الجهاز", "The program is not activated on this computer"
    LangAdd "البنك الافتراضي للتحويلات البنكية", "Default bank for bank transfers"
    LangAdd "المفتاح المشترك (إن أعطته المصلحة", "Pre-shared key (if given by the Tax Authority"
    LangAdd "امسح الباركود (يضيف 1) أو 3*الكود", "Scan the barcode (adds 1) or 3*code"
    LangAdd "بيانات ناقصة للفاتورة الإلكترونية", "Missing data for e-invoicing"
    LangAdd "بيع آجل لعميل غير مسموح له بالآجل", "A credit sale to a customer not allowed to buy on credit"
    LangAdd "حذف التسوية الجارية وكل مطابقاتها", "Delete the open reconciliation and all its matches"
    LangAdd "حذف الحركة البنكية المحددة وقيدها", "Delete the selected bank transaction and its entry"
    LangAdd "حسب صافي الكمية خلال فترة التقرير", "By net quantity during the report period"
    LangAdd "خصم الغياب أكبر من الأساسي والسكن", "The absence deduction is more than the basic and housing"
    LangAdd "رقمنا (PUR-) أو رقم فاتورة المورد", "Our number (PUR-) or the supplier invoice number"
    LangAdd "سطر لا ينتمي إلى الفاتورة الأصلية", "A line that does not belong to the original invoice"
    LangAdd "طلب سفري: يُغلَّف ويُسلَّم للعميل", "Takeaway order: packed and handed to the customer"
    LangAdd "لا تملك صلاحية تعيين كلمات المرور", "You do not have the permission to set passwords"
    LangAdd "لا يتوقف البيع الآجل بسبب التأخير", "Credit sales are not stopped for delays"
    LangAdd "مركز المستخدم أو المركز الافتراضي", "The center of the user or the default center"
    LangAdd "هذا الشيك مسجل من قبل لنفس العميل", "This cheque is already recorded for the same customer"
    LangAdd "والفاتورة الإلكترونية لهذه الدولة", "and the e-invoicing of this country"
    LangAdd "أكمل فحوص الامتثال أولًا (الخطوة", "Complete the compliance checks first (step"
    LangAdd "اختر كلمة مرور مختلفة عن الحالية", "Choose a password different from the current one"
    LangAdd "اكتب تاريخ الشراء وبداية الإهلاك", "Type the purchase date and the start of depreciation"
    LangAdd "الخزينة الرئيسية وصناديق الكاشير", "Main treasury and cashier boxes"
    LangAdd "الرصيد المتبقي على العميل حاليًا", "Balance currently due from the customer"
    LangAdd "المبيعات الخاضعة للنسبة الأساسية", "Sales at the standard rate"
    LangAdd "المشتريات الخاضعة للنسبة الصفرية", "Zero-rated purchases"
    LangAdd "ترحيل المسير وإنشاء قيد العمولات", "Post the run and create the commissions entry"
    LangAdd "تم إلغاء الحفظ: الكمية غير كافية", "Saving was cancelled: the quantity is not enough"
    LangAdd "تم تفعيل البرنامج على هذا الجهاز", "The program was activated on this computer"
    LangAdd "تم نسخ رقم الجهاز. أرسله للمبرمج", "The computer number was copied. Send it to the developer"
    LangAdd "تُنسب له فواتير العميل وتحصيلاته", "The invoices and collections of the customer are credited to him"
    LangAdd "حصّل المتأخر أولًا، أو بِع نقدًا", "Collect the overdue amount first, or sell for cash"
    LangAdd "راجعها وعدّل ما يلزم ثم اضغط حفظ", "Review them, correct what is needed, then press Save"
    LangAdd "فاتورة الشراء الأصلية غير موجودة", "The original purchase invoice does not exist"
    LangAdd "كود التفعيل غير صحيح لهذا الجهاز", "The activation code is not valid for this computer"
    LangAdd "كود المصلحة (EGS أو GS1) للأصناف", "Tax Authority code (EGS or GS1) of the products"
    LangAdd "لا تملك صلاحية تسجيل سندات الصرف", "You do not have the permission to record payment vouchers"
    LangAdd "لا تملك صلاحية تعديل أسعار البيع", "You do not have the permission to change sale prices"
    LangAdd "لا توجد حركة نقدية في هذه الفترة", "There is no cash move in this period"
    LangAdd "لا يحتاج هذا التقرير أي اختيارات", "This report needs no choices"
    LangAdd "لا يمكن إلغاء جرد مُرحّل أو ملغى", "A posted or cancelled count cannot be cancelled"
    LangAdd "لا يُسجَّل شيك على العميل النقدي", "No cheque is recorded on the cash customer"
    LangAdd "مصروف متكرر مستحق (إيجار، كهرباء", "Recurring expense due (rent, electricity"
    LangAdd "ملء كل أشهر الموازنة من فعلي سنة", "Fill every month of the budget from the actuals of a year"
    LangAdd "موجود قبل البرنامج (رصيد افتتاحي", "Owned before the program (opening balance"
    LangAdd "يُولَّد تلقائيًا إذا تُرك فارغًا", "Generated automatically if left empty"
    LangAdd "اختر الشهر ثم «إنشاء مسير الشهر", "Choose the month, then Create the run of the month"
    LangAdd "الإقرار مسدد: ألغِ السداد أولًا", "The return is paid: cancel the payment first"
    LangAdd "الحسابات البنكية للمحل وأرصدتها", "The bank accounts of the store and their balances"
    LangAdd "الرقم التسلسلي لجهاز نقطة البيع", "Serial number of the POS device"
    LangAdd "العملاء والموردون حسب الاستحقاق", "Customers and suppliers by due date"
    LangAdd "الموظفون وأسماء الدخول والأدوار", "Employees, login names and roles"
    LangAdd "بحث بالاسم أو الكود أو الباركود", "Search by name, code or barcode"
    LangAdd "بيانات ناقصة للإيصال الإلكتروني", "Missing data for the e-receipt"
    LangAdd "تاريخ النهاية قبل تاريخ البداية", "The end date is before the start date"
    LangAdd "ترحيل المسير وإنشاء قيد الرواتب", "Post the run and create the payroll entry"
    LangAdd "تعذّر الدخول إلى منظومة المصلحة", "Could not log in to the Tax Authority system"
    LangAdd "تفعيل البرنامج لمدير النظام فقط", "Activation is for the system administrator only"
    LangAdd "توليد أكواد التفعيل للمبرمج فقط", "Activation codes are generated by the developer only"
    LangAdd "خلال فترة التقرير، شامل الضريبة", "during the report period, including VAT"
    LangAdd "رحّل المسير أولًا، ثم سجّل صرفه", "Post the run first, then record its payment"
    LangAdd "عند حفظ فاتورة البيع أو المرتجع", "When the sales invoice or the return is saved"
    LangAdd "فروقات المخزون (جرد، إضافة، خصم", "Stock differences (count, addition, deduction"
    LangAdd "لا تملك صلاحية إدارة المستخدمين", "You do not have the permission to manage users"
    LangAdd "لا توجد قيود للاختيارات المحددة", "There are no entries for the choices made"
    LangAdd "لا يمكن التحويل إلى نفس الصندوق", "Cannot transfer to the same box"
    LangAdd "لا يمكن الترحيل إلى نفس الصندوق", "Cannot transfer to the same box"
    LangAdd "لا يمكن تعديل التصفية بعد الحفظ", "The closing cannot be edited after saving"
    LangAdd "لا يوجد منتج بالباركود أو الكود", "No product with the barcode or the code"
    LangAdd "لم تُصدر الهيئة الشهادة الفعلية", "ZATCA did not issue the production certificate"
    LangAdd "يوجد إقرار معتمد بعد هذه الفترة", "There is an approved return after this period"
    LangAdd "يُحذف قيد إقفالها وتُفتح فترتها", "Its closing entry is deleted and its period opened"
    LangAdd "يُخصم كل رصيد السلف في أول مسير", "The whole advance balance is deducted in the first run"
    LangAdd "آخر تسوية معتمدة لهذا البنك في", "Last approved reconciliation of this bank on"
    LangAdd "إعادة الفتح: تصبح الفترة مقفلة", "Reopening: the period becomes closed"
    LangAdd "إلغاء التفعيل لمدير النظام فقط", "Deactivation is for the system administrator only"
    LangAdd "إلغاء ربط هذا المبلغ بالفاتورة", "Unlink this amount from the invoice"
    LangAdd "إيرادات ومصروفات كل مركز تكلفة", "Revenue and expenses of each cost center"
    LangAdd "اختر الحساب في كل سطر فيه مبلغ", "Choose the account in every line with an amount"
    LangAdd "اختر الخزينة التي تستلم المبلغ", "Choose the treasury that receives the amount"
    LangAdd "الحساب المقابل (الحركات الأخرى", "Contra account (other moves"
    LangAdd "الخزينة والصناديق (الرصيد الآن", "Treasury and boxes (balance now"
    LangAdd "السند والفاتورة لطرفين مختلفين", "The voucher and the invoice belong to different parties"
    LangAdd "الشاشة التي يفتحها زر المبيعات", "The screen opened by the Sales button"
    LangAdd "الكمية يجب أن تكون أكبر من صفر", "The quantity must be greater than zero"
    LangAdd "المبلغ أكبر من رصيد سلف الموظف", "The amount is more than the advance balance of the employee"
    LangAdd "المبلغ يجب أن يكون أكبر من صفر", "The amount must be greater than zero"
    LangAdd "المبيعات الشهرية (آخر 12 شهرًا", "Monthly sales (last 12 months"
    LangAdd "المسير مصروف: ألغِ الصرف أولًا", "The run is paid: cancel the payment first"
    LangAdd "تقرير الملصقات غير موجود. شغّل", "The labels report does not exist. Run"
    LangAdd "حركة الخزينة / الصندوق (تفصيلي", "Treasury / box moves (detailed"
    LangAdd "رحّله أو ألغه قبل بدء جرد جديد", "Post it or cancel it before starting a new count"
    LangAdd "قيمة وحدة واحدة بعملة البرنامج", "Value of one unit in the program currency"
    LangAdd "كل شاشات الحسابات في مكان واحد", "All the accounting screens in one place"
    LangAdd "لا تملك صلاحية إدارة الصلاحيات", "You do not have the permission to manage permissions"
    LangAdd "لا تملك صلاحية الإقرار الضريبي", "You do not have the permission for the VAT return"
    LangAdd "لا تملك صلاحية النسخ الاحتياطي", "You do not have the permission for backups"
    LangAdd "لا تملك صلاحية تعديل سعر البيع", "You do not have the permission to change the sale price"
    LangAdd "لا توجد فاتورة شراء بهذا الرقم", "There is no purchase invoice with this number"
End Sub

Private Sub D2_3()
    LangAdd "لا يوجد سداد مسجل لهذا الإقرار", "No payment is recorded for this return"
    LangAdd "للبيع الآجل اختر عميلًا مسجلًا", "For a credit sale choose a registered customer"
    LangAdd "للعملاء المنشآت (فاتورة ضريبية", "For business customers (tax invoice"
    LangAdd "لم تُصدر الهيئة شهادة الامتثال", "ZATCA did not issue the compliance certificate"
    LangAdd "ليست لديك صلاحية سندات الخزينة", "You do not have the permission for treasury vouchers"
    LangAdd "مجلد Images بجانب ملف البيانات", "Images folder next to the data file"
    LangAdd "مجموع أرصدة المستوى الأول (صفر", "Total of the first-level balances (zero"
    LangAdd "من 1 إلى 28 (يوم الإيجار مثلًا", "From 1 to 28 (the rent day, for example"
    LangAdd "نقر مزدوج على السطر يفتح القيد", "Double-click a line to open the entry"
    LangAdd "أرسل إيصال البيع الأصلي أولًا", "Send the receipt of the original sale first"
    LangAdd "أولًا: السنوات تُقفل بالترتيب", "first: years are closed in order"
    LangAdd "إضافة وتعديل الأصناف والأسعار", "Add and edit items and prices"
    LangAdd "إعداد الإيصال الإلكتروني ناقص", "The e-receipt setup is incomplete"
    LangAdd "اختر البنك المسحوب عليه الشيك", "Choose the bank the cheque is drawn on"
    LangAdd "اختر تقريرًا من القائمة أولًا", "Choose a report from the list first"
    LangAdd "اختر عملية أو أكثر من القائمة", "Choose one or more transactions from the list"
    LangAdd "اختر كلمة مرور جديدة للمتابعة", "Choose a new password to continue"
    LangAdd "اسم العميل على الكوب (اختياري", "Customer name on the cup (optional"
    LangAdd "اكتب الحد الأعلى للأجر الخاضع", "Type the maximum insurable wage"
    LangAdd "اكتب تاريخ البيع أو الاستبعاد", "Type the date of the sale or disposal"
    LangAdd "الإيجار والكهرباء والاشتراكات", "Rent, electricity and subscriptions"
    LangAdd "البرنامج مفعّل على هذا الجهاز", "The program is activated on this computer"
    LangAdd "التكلفة لا يمكن أن تكون سالبة", "The cost cannot be negative"
    LangAdd "الرمز البريدي للعميل (5 أرقام", "Customer postal code (5 digits"
    LangAdd "المصروفات التشغيلية والإدارية", "Operating and administrative expenses"
    LangAdd "النقدية الفعلية لا تكون سالبة", "The actual cash is never negative"
    LangAdd "انقر مرتين على النتيجة لفتحها", "Double-click a result to open it"
    LangAdd "بدون مسافات، 3 أحرف على الأقل", "No spaces, at least 3 characters"
    LangAdd "بعد المصروفات وفروقات المخزون", "after expenses and stock differences"
    LangAdd "بيع الأصل المعروض أو استبعاده", "Sell or dispose of the asset shown"
    LangAdd "تُعاد فتح آخر تسوية للبنك فقط", "Only the last reconciliation of the bank can be reopened"
    LangAdd "رغم ذلك؟ (بصلاحية مدير النظام", "anyway? (with the permission of the system administrator"
    LangAdd "رقم هذا الجهاز (أرسله للمبرمج", "Number of this computer (send it to the developer"
    LangAdd "طلب التوصيل يحتاج جوال العميل", "A delivery order needs the customer mobile"
    LangAdd "عرض فقط - التصحيح يكون بمرتجع", "View only - a correction is made with a return"
    LangAdd "كلمة المرور الحالية غير صحيحة", "The current password is wrong"
    LangAdd "كلمة مرور جديدة لحساب المبرمج", "New password for the developer account"
    LangAdd "لا تملك صلاحية الأصول الثابتة", "You do not have the permission for fixed assets"
    LangAdd "لا تملك صلاحية القيود اليدوية", "You do not have the permission for manual entries"
    LangAdd "لا تملك صلاحية تقارير الأرباح", "You do not have the permission for profit reports"
    LangAdd "لا توجد منتجات منخفضة المخزون", "There are no low-stock products"
    LangAdd "لا يمكنك تغيير صلاحياتك بنفسك", "You cannot change your own permissions"
    LangAdd "لا يوجد عملاء مسندون لمندوبين", "No customers are assigned to sales reps"
    LangAdd "موجود في الموازنة لنفس المركز", "already in the budget for the same center"
    LangAdd "هذا الإجراء غير موجود في شاشة", "This action does not exist in the screen"
    LangAdd "هل تريد حذف هذا السجل نهائيًا", "Do you want to delete this record for good"
    LangAdd "وتحديث المخزون ومتوسط التكلفة", "and the stock and average cost are updated"
    LangAdd "يبقى في الصندوق (عهدة الكاشير", "Stays in the box (cashier float"
    LangAdd "إقفال الفترات والسنة المالية", "Period and fiscal year closing"
    LangAdd "إلغاء ترحيل المسير وحذف قيده", "Unpost the run and delete its entry"
    LangAdd "اختر المنتج من القائمة أولًا", "Choose the product from the list first"
    LangAdd "اختر النسخة من القائمة أولًا", "Choose the backup from the list first"
    LangAdd "اختر فاتورة آجلة عليها متبقٍ", "Choose a credit invoice with an amount remaining"
    LangAdd "اختر نوع الشيك: وارد أو صادر", "Choose the cheque type: received or issued"
    LangAdd "استبعاد بدون ثمن (تلف أو فقد", "Disposal without a price (damage or loss"
    LangAdd "استحقاق فاتورة الشراء الآجلة", "Due date of a credit purchase invoice"
    LangAdd "اكتب السنة التي يُنسخ فعليها", "Type the year whose actuals are copied"
    LangAdd "التسوية غير موجودة أو معتمدة", "The reconciliation does not exist or is approved"
    LangAdd "الرصيد المستحق للمورد حاليًا", "Balance currently due to the supplier"
    LangAdd "الرمز البريدي للمحل (5 أرقام", "Store postal code (5 digits"
    LangAdd "العمر الإنتاجي شهر على الأقل", "The useful life is at least one month"
    LangAdd "المبلغ بالعملة (بدون الضريبة", "Amount in currency (without VAT"
    LangAdd "المنظومة غير متاحة الآن (رمز", "The platform is not available now (code"
    LangAdd "النسخ الموجودة (الأحدث أولًا", "Existing backups (newest first"
    LangAdd "بداية الإهلاك قبل شهر الشراء", "The depreciation starts before the month of purchase"
    LangAdd "تسجيل دفعة من عميل على حسابه", "Record a payment from a customer on his account"
    LangAdd "حتى لا تتغير مستندات الإقرار", "so that the documents of the return do not change"
    LangAdd "حركة يدوية على المنتج المحدد", "A manual move on the selected product"
    LangAdd "خصم السلفة أكبر من رصيد سلفه", "The advance deduction is more than his advance balance"
    LangAdd "خصم على الفاتورة (بدون ضريبة", "Invoice discount (without VAT"
    LangAdd "دليل الحسابات (شجرة الحسابات", "Chart of accounts (account tree"
    LangAdd "رد غير متوقع من المصلحة (رمز", "Unexpected reply from the Tax Authority (code"
    LangAdd "صافي الضريبة المستحقة للسداد", "Net VAT due for payment"
    LangAdd "ضريبة المدخلات أقل من المبلغ", "Input VAT is less than the amount"
    LangAdd "على حساب آخر (مستحقات أو قرض", "On another account (accruals or a loan"
    LangAdd "عملة البرنامج لا تحتاج سعرًا", "The program currency needs no rate"
    LangAdd "قائمة الدخل حسب مركز التكلفة", "Income statement by cost center"
    LangAdd "لا تملك صلاحية إقفال الفترات", "You do not have the permission to close periods"
    LangAdd "لا تملك هذه الصلاحية في شاشة", "You do not have this permission in the screen"
    LangAdd "لا توجد تصفيات في هذه الفترة", "There are no closings in this period"
    LangAdd "لا توجد مبيعات في هذه الفترة", "There are no sales in this period"
    LangAdd "لمن لا مركز له من المستخدمين", "for users without a center"
    LangAdd "مبالغ الموازنة لا تكون سالبة", "Budget amounts are never negative"
    LangAdd "مطابق: لا يوجد عجز ولا زيادة", "Matched: no shortage and no overage"
    LangAdd "منظومة مصلحة الضرائب المصرية", "the Egyptian Tax Authority system"
    LangAdd "وضع المطوّر لمدير النظام فقط", "Developer mode is for the system administrator only"
    LangAdd "يتطلب صلاحية الأرقام المالية", "Needs the permission Financial figures"
    LangAdd "إجمالي الخصوم وحقوق الملكية", "Total liabilities and equity"
    LangAdd "إقفال الفترة والسنة المالية", "Period and fiscal year closing"
    LangAdd "إلغاء صرف الرواتب وحذف قيده", "Cancel the salary payment and delete its entry"
    LangAdd "اجتازت العينات فحص الامتثال", "The samples passed the compliance checks"
    LangAdd "اختر آخر شهر يُسجَّل إهلاكه", "Choose the last month to record depreciation for"
    LangAdd "اختر الفاتورة الأصلية أولًا", "Choose the original invoice first"
    LangAdd "الإحصائيات والرسوم البيانية", "Statistics and charts"
    LangAdd "الباقي غير المربوط من السند", "The unlinked remainder of the voucher"
    LangAdd "الفاتورة الأصلية غير موجودة", "The original invoice does not exist"
    LangAdd "المصروفات (إجمالي حسب النوع", "Expenses (total by type"
    LangAdd "بالكامل (لا تبقى فترة مقفلة", "fully (no period stays closed"
    LangAdd "بنكنا (الصادر: المسحوب عليه", "Our bank (issued: drawn on"
    LangAdd "تسجيل الإهلاك حتى هذا الشهر", "Record depreciation up to this month"
    LangAdd "تعذّر إنشاء المفتاح ببرنامج", "Could not create the key with"
    LangAdd "تعذّر ضبط عملة ملف البيانات", "Could not set the currency of the data file"
    LangAdd "تم الحفظ لكن تعذّرت الطباعة", "Saved, but printing failed"
    LangAdd "تم ضبط وضع المستخدم النهائي", "End-user mode is set"
    LangAdd "تُعاد فتح آخر سنة مقفلة فقط", "Only the last closed year can be reopened"
    LangAdd "خصم الفاتورة أكبر من قيمتها", "The invoice discount is more than its value"
    LangAdd "رد غير متوقع من الهيئة (رمز", "Unexpected reply from ZATCA (code"
    LangAdd "صادر آخر (رسوم بنكية وغيرها", "Other outgoing (bank fees and others"
    LangAdd "صافي الضريبة المستحقة (سالب", "Net VAT due (negative"
    LangAdd "صافي المبيعات (بدون الضريبة", "Net sales (without VAT"
    LangAdd "لا تكلفة مبيعات أو لا مخزون", "No cost of sales or no stock"
    LangAdd "لا تملك صلاحية مسير الرواتب", "You do not have the permission for payroll"
    LangAdd "لا توجد أشهر لم تُسجَّل حتى", "There are no unrecorded months up to"
    LangAdd "لا توجد قيود للفترة المحددة", "There are no entries for the period set"
    LangAdd "مثال: PCE للحبة، KGM للكيلو", "Example: PCE for a piece, KGM for a kilo"
    LangAdd "مصروف من المصروفات المتكررة", "An expense from the recurring expenses"
    LangAdd "ملف المفتاح الخاص غير موجود", "The private key file was not found"
    LangAdd "يُقيَّد صافي الربح (الخسارة", "The net profit (loss"
    LangAdd "أضف صنفًا واحدًا على الأقل", "Add at least one item"
    LangAdd "أقصى خصم بدون موافقة (مثال", "Maximum discount without approval (example"
End Sub

Private Sub D2_4()
    LangAdd "ألغِ اعتماد الإقرار اللاحق", "Cancel the approval of the later return"
    LangAdd "إعادة فتح التسوية المعتمدة", "Reopen the approved reconciliation"
    LangAdd "إقرار ضريبة القيمة المضافة", "VAT return"
    LangAdd "اختر الصرف من بنك أو صندوق", "Choose to pay from a bank or a box"
    LangAdd "اختر الصندوق الذي دُفع منه", "Choose the box it was paid from"
    LangAdd "اختر الصندوق المحوَّل إليه", "Choose the box transferred to"
    LangAdd "اختر قيمة صحيحة من القائمة", "Choose a valid value from the list"
    LangAdd "البريد الإلكتروني غير صحيح", "The e-mail is not valid"
    LangAdd "السطر الثاني أسفل الباركود", "Second line below the barcode"
    LangAdd "السطر الثاني أعلى الباركود", "Second line above the barcode"
    LangAdd "العملاء والأهداف والعمولات", "Customers, targets and commissions"
    LangAdd "المجموع قبل الخصم والضريبة", "Total before discount and VAT"
    LangAdd "المرتجعات على هذه الفاتورة", "Returns on this invoice"
    LangAdd "المسير غير موجود أو مرحَّل", "The run does not exist or is posted"
    LangAdd "بعد اعتماد الإقرار الضريبي", "after the VAT return is approved"
    LangAdd "تأكيد أخير: استعادة النسخة", "Last confirmation: restore the backup"
    LangAdd "تاريخ الصرف قبل شهر المسير", "The payment date is before the month of the run"
    LangAdd "ترحيل إلى الخزينة الرئيسية", "Transfer to the main treasury"
    LangAdd "تصحيحات من الفترات السابقة", "Corrections from previous periods"
    LangAdd "تعذر عمل النسخة الاحتياطية", "Could not make the backup"
    LangAdd "تغيير أو تعيين كلمة المرور", "Change or set the password"
    LangAdd "دائن الفترة (المستوى الأول", "Period credit (first level"
    LangAdd "رقم الجهاز 16 حرفًا بالشكل", "The computer number has 16 characters in the form"
    LangAdd "في فترة مقفلة (الإقفال حتى", "in a closed period (closed up to"
    LangAdd "كلمة المرور يجب ألا تقل عن", "The password must have at least"
    LangAdd "لا تملك صلاحية سندات الصرف", "You do not have the permission for payment vouchers"
    LangAdd "لا تملك صلاحية سندات القبض", "You do not have the permission for receipt vouchers"
    LangAdd "لا توجد قيود في هذه الفترة", "There are no entries in this period"
    LangAdd "لا توجد موازنة لسنة الفترة", "There is no budget for the year of the period"
    LangAdd "لا يُنشأ مسير لشهر لم يبدأ", "No run is created for a month that has not started"
    LangAdd "لكل فترة ضريبية إقرار واحد", "One return for each tax period"
    LangAdd "لم يُثبَّت بعد في البرنامج", "is not installed in the program yet"
    LangAdd "ليست لديك صلاحية المصروفات", "You do not have the permission for expenses"
    LangAdd "مدين الفترة (المستوى الأول", "Period debit (first level"
    LangAdd "مصر: كود الصنف لدى المصلحة", "Egypt: Tax Authority product code"
    LangAdd "هامش الربح الإجمالي (الشهر", "Gross profit margin (month"
    LangAdd "هل تريد مسح قائمة الملصقات", "Do you want to clear the label list"
    LangAdd "وسيصبح المورد مدينًا للمحل", "and the supplier will owe the store"
    LangAdd "إعادة الفتح إلى هذا اليوم", "Reopen up to this day"
    LangAdd "إلغاء بيع / استبعاد الأصل", "Cancel the sale / disposal of the asset"
    LangAdd "إلغاء تفعيل الجهاز المحدد", "Deactivate the selected computer"
    LangAdd "اكتب المبلغ بعملة المصروف", "Type the amount in the currency of the expense"
    LangAdd "اكتب معامل التحويل للعملة", "Type the exchange rate of the currency"
    LangAdd "الأرقام من المستندات الآن", "The figures come from the documents now"
    LangAdd "الأصل غير موجود أو مستبعد", "The asset does not exist or is disposed"
    LangAdd "الإقرارات تُعتمد بالترتيب", "Returns are approved in order"
    LangAdd "التحويل بين بنكين مختلفين", "Transfer between two different banks"
    LangAdd "الحسابات البنكية والتسوية", "Bank accounts and reconciliation"
    LangAdd "السطر الأول أسفل الباركود", "First line below the barcode"
    LangAdd "السطر الأول أعلى الباركود", "First line above the barcode"
    LangAdd "الكمية المتوفرة غير كافية", "The available quantity is not enough"
    LangAdd "المبلغ أقل من الإجمالي بـ", "The amount is less than the total by"
    LangAdd "تأكيد كلمة المرور الجديدة", "Confirm the new password"
    LangAdd "تاريخ الاستحقاق قبل تاريخ", "The due date is before the date"
    LangAdd "تجاوز حد الائتمان: الرصيد", "Credit limit exceeded: balance"
    LangAdd "تسجيل دفعة لمورد من حسابه", "Record a payment to a supplier on his account"
    LangAdd "تسوية، صافي قيمة الفروقات", "Adjustment, net value of the differences"
    LangAdd "تم اعتماد التسوية البنكية", "The bank reconciliation was approved"
    LangAdd "تم حفظ الأسماء الإنجليزية", "English names saved"
    LangAdd "تنبيه: الكمية المتوفرة من", "Warning: the available quantity of"
    LangAdd "تُقترح في فواتيره وسنداته", "Suggested in his invoices and vouchers"
    LangAdd "حدد ما يستطيع كل دور فعله", "Set what each role can do"
    LangAdd "حذف الموازنة كلها بأسطرها", "Delete the whole budget with its lines"
    LangAdd "خسارة بيع / استبعاد الأصل", "Loss on sale / disposal of the asset"
    LangAdd "دفتر الأستاذ (كل الحسابات", "General ledger (all accounts"
    LangAdd "رصيد الكشف في هذا التاريخ", "Statement balance on this date"
    LangAdd "رقم الهوية / الرقم القومي", "ID / national ID number"
    LangAdd "سداد ضريبة القيمة المضافة", "VAT payment"
    LangAdd "صرف العمولة يكون بسند صرف", "A commission is paid with a payment voucher"
    LangAdd "طلب التوصيل يحتاج العنوان", "A delivery order needs the address"
    LangAdd "عمولات المندوبين المستحقة", "Sales rep commissions payable"
    LangAdd "غير مسموح له بالبيع الآجل", "is not allowed to buy on credit"
    LangAdd "قيد يكتبه المحاسب: المدين", "An entry written by the accountant: debit"
    LangAdd "كل القيود وميزان المراجعة", "All entries and the trial balance"
    LangAdd "لا توجد أصناف في الفاتورة", "There are no items in the invoice"
    LangAdd "لا توجد فاتورة بهذا الرقم", "There is no invoice with this number"
    LangAdd "لا توجد فاتورة شراء سابقة", "There is no previous purchase invoice"
    LangAdd "لا يمكنك تغيير دورك بنفسك", "You cannot change your own role"
    LangAdd "مسار برنامج OpenSSL (فارغ", "OpenSSL program path (empty"
    LangAdd "مصر: EA للحبة، KGM للكيلو", "Egypt: EA for a piece, KGM for a kilo"
    LangAdd "مصروف (يُسجل في المصروفات", "Expense (recorded in the expenses"
    LangAdd "ملخص ضريبة القيمة المضافة", "VAT summary"
    LangAdd "ميزان المراجعة بالمستويات", "Trial balance by level"
    LangAdd "أدخل المبلغ (أكبر من صفر", "Enter the amount (greater than zero"
    LangAdd "أعد فتح الشاشات المفتوحة", "Reopen the open screens"
    LangAdd "اختر البنك الذي دُفع منه", "Choose the bank it was paid from"
    LangAdd "اختر البنك المحوَّل إليه", "Choose the bank transferred to"
    LangAdd "اختر جردًا مفتوحًا أولًا", "Choose an open count first"
    LangAdd "اختر سطر حساب من القائمة", "Choose an account line from the list"
    LangAdd "اختر فاتورة الشراء أولًا", "Choose the purchase invoice first"
    LangAdd "اكتب سبب إعادة فتح السنة", "Type the reason for reopening the year"
    LangAdd "التاريخ قبل تاريخ الشراء", "The date is before the purchase date"
    LangAdd "الحساب الرئيسي غير موجود", "The main account does not exist"
    LangAdd "الشراء والبيع والاستبعاد", "Purchase, sale and disposal"
    LangAdd "الشيكات الواردة والصادرة", "Received and issued cheques"
    LangAdd "الطباعة عند حفظ الفاتورة", "Printing when the invoice is saved"
    LangAdd "الفترة تتداخل مع الإقرار", "The period overlaps the return"
    LangAdd "القيد غير متوازن: المدين", "The entry is not balanced: debit"
    LangAdd "المبلغ المسدد بين 0.01 و", "The amount paid is between 0.01 and"
    LangAdd "المتبقي في الصندوق (عهدة", "Left in the box (float"
    LangAdd "المملكة العربية السعودية", "Kingdom of Saudi Arabia"
    LangAdd "بيانات الموردين وأرصدتهم", "Supplier data and balances"
    LangAdd "تاريخ الاعتماد بعد اليوم", "The approval date is after today"
    LangAdd "تحديث القيود من العمليات", "Refresh the entries from the transactions"
    LangAdd "تصنيف الجرد الجديد (فارغ", "Category of the new count (empty"
    LangAdd "تعذر حفظ مرتجع المشتريات", "Could not save the purchase return"
    LangAdd "تُكتب عليه القيود؛ رئيسي", "takes entries, main"
    LangAdd "ثمن البيع لا يكون سالبًا", "The sale price is never negative"
    LangAdd "جلسة الجرد (الأحدث أولًا", "Count session (newest first"
    LangAdd "رقم مبنى العميل (4 أرقام", "Customer building number (4 digits"
    LangAdd "سجل الإقفال وإعادة الفتح", "Closing and reopening log"
    LangAdd "طباعة مباشرة بدون معاينة", "Print directly without preview"
    LangAdd "عملاء المندوبين وأرصدتهم", "Sales rep customers and balances"
    LangAdd "لا توجد عمليات في الفترة", "There are no transactions in the period"
    LangAdd "مرتجع شراء (استرداد نقدي", "Purchase return (cash refund"
    LangAdd "مرتجع مبيعات (إشعار دائن", "Sales return (credit note"
    LangAdd "مسجلة مسبقًا لنفس المورد", "already recorded for the same supplier"
    LangAdd "نهاية الفترة قبل بدايتها", "The end of the period is before its start"
    LangAdd "هذا الشهر: صافي المبيعات", "This month: net sales"
    LangAdd "هل تريد الحفظ على أي حال", "Do you want to save anyway"
End Sub

Private Sub D2_5()
    LangAdd "هل تريد الخروج من النظام", "Do you want to exit the system"
    LangAdd "يجمع حساباته التابعة فقط", "Sums its sub-accounts only"
    LangAdd "أدخل تاريخ أعمار الديون", "Enter the aging date"
    LangAdd "أرصدة الخزينة والصناديق", "Treasury and cash box balances"
    LangAdd "أصلح هذا أولًا، ثم أقفل", "Fix this first, then close"
    LangAdd "أكبر من الحد المسموح لك", "more than the limit allowed to you"
    LangAdd "إجمالي الإيرادات الأخرى", "Total other revenue"
    LangAdd "إجمالي المصروفات الأخرى", "Total other expenses"
    LangAdd "إعدادات ملصقات الباركود", "Barcode label settings"
    LangAdd "إقفال فترة (شهر أو أكثر", "Close a period (a month or more"
    LangAdd "اختر الموظف صاحب السلفة", "Choose the employee who takes the advance"
    LangAdd "اختر تقريرًا من القائمة", "Choose a report from the list"
    LangAdd "اختر مستندًا من القائمة", "Choose a document from the list"
    LangAdd "استحقاق الفاتورة الآجلة", "Due date of a credit invoice"
    LangAdd "الأشهر تُسجَّل بالترتيب", "months are recorded in order"
    LangAdd "الاسم الإنجليزي أطول من", "The English name is longer than"
    LangAdd "التأمينات - حصة المنشأة", "Social insurance - employer share"
    LangAdd "التاريخ قبل تاريخ الشيك", "The date is before the cheque date"
    LangAdd "الجهاز مسجّل لدى الهيئة", "The device is registered with ZATCA"
    LangAdd "الخصومات أكبر من الراتب", "The deductions are more than the salary"
    LangAdd "الرصيد الدفتري (المفروض", "Book balance (expected"
    LangAdd "الشهر التالي للإهلاك هو", "The next month to depreciate is"
    LangAdd "المسافة بين الأعمدة (مم", "Space between columns (mm"
    LangAdd "المصروفات (بدون الضريبة", "Expenses (without VAT"
    LangAdd "المطابقة في هذه التسوية", "Matched in this reconciliation"
    LangAdd "المنتجات منخفضة المخزون", "Low-stock products"
End Sub
