Attribute VB_Name = "modLangData2"
'==============================================================================
' modLangData2  -  Retail Store Management System: part 2 of the Arabic ->
' English dictionary of the interface (modLang). GENERATED FILE - do not edit.
' Source: tools/i18n_en.py  ->  python3 tools/generate.py
'==============================================================================
Option Compare Database
Option Explicit

Public Sub LangData2()
    D2_1
    D2_2
    D2_3
    D2_4
    D2_5
End Sub

Private Sub D2_1()
    LangAdd "تُحذف المسودة فقط: ألغِ الترحيل أولًا", "Only the draft is deleted: unpost it first"
    LangAdd "حركة الخزينة اليومية (أول اليوم وآخره", "Daily treasury moves (start and end of the day"
    LangAdd "رقم جديد لا يتكرر؛ لا يتغير بعد الحفظ", "A new number that is not repeated, it does not change after saving"
    LangAdd "سجل التدقيق يحتاج صلاحية «سجل التدقيق", "The audit trail needs the permission Audit trail"
    LangAdd "عرض فقط - التصحيح يكون بمرتجع مشتريات", "View only - a correction is made with a purchase return"
    LangAdd "غير نشط. فعّله من شاشة المنتجات أولًا", "is not active. Activate it in the Products screen first"
    LangAdd "فحص سلامة البيانات: لا توجد أي مشكلات", "Data integrity check: no problems at all"
    LangAdd "لا تملك صلاحية اعتماد التسوية البنكية", "You do not have the permission to approve the bank reconciliation"
    LangAdd "لا تملك صلاحية تسجيل فواتير المشتريات", "You do not have the permission to record purchase invoices"
    LangAdd "لا تملك هذه الصلاحية في شاشة الموازنة", "You do not have this permission in the budget screen"
    LangAdd "لا توجد حركة نقدية للاختيارات المحددة", "There is no cash move for the choices made"
    LangAdd "مقفلة بقيد إقفال. أعد فتح السنة أولًا", "closed with a closing entry. Reopen the year first"
    LangAdd "من بداية الصندوق (لا توجد تصفية سابقة", "since the box started (no previous closing"
    LangAdd "هذا سجل أساسي في النظام ولا يمكن حذفه", "This is a system record and cannot be deleted"
    LangAdd "هل تريد إنشاء المصروفات المستحقة الآن", "Do you want to create the due expenses now"
    LangAdd "أرصدة الموردين بالعملات وفروق العملة", "Supplier balances by currency and exchange differences"
    LangAdd "إجمالي المصروفات التشغيلية والإدارية", "Total operating and administrative expenses"
    LangAdd "إلغاء سداد الإقرار؟ يُحذف قيد السداد", "Cancel the payment of the return? The payment entry is deleted"
    LangAdd "اكتب سبب إلغاء الاعتماد في الملاحظات", "Type the reason for cancelling the approval in the notes"
    LangAdd "السماح لمدير النظام بتغيير اسم المحل", "Allow the system administrator to change the store name"
    LangAdd "العمولة وضريبتها أقل من مبلغ التسوية", "The fee and its VAT are less than the settled amount"
    LangAdd "الكمية الفعلية لا يمكن أن تكون سالبة", "The actual quantity cannot be negative"
    LangAdd "بالفعل. لإرجاعها استخدم «إعادة الفتح", "already. To undo it use Reopen"
    LangAdd "تسجيل الإهلاك لكل شهر لم يُسجَّل حتى", "Record depreciation for every month not recorded up to"
    LangAdd "تقارير الخزينة تحتاج صلاحية «الخزينة", "The treasury reports need the permission Treasury"
    LangAdd "ستُستبدل كل البيانات الحالية بالنسخة", "All the current data will be replaced by the backup"
    LangAdd "سجل جديد - أدخل البيانات ثم اضغط حفظ", "New record - enter the data, then click Save"
    LangAdd "شامل الضريبة بعد المرتجعات - المجموع", "Including VAT after returns - total"
    LangAdd "صافي ربح (خسارة) الفترات غير المقفلة", "Net profit (loss) of the periods not closed"
    LangAdd "ضريبة مستردة (تُرحَّل للإقرار التالي", "Refundable VAT (carried to the next return"
    LangAdd "كلمة المرور غير صحيحة. تم قفل الحساب", "The password is wrong. The account was locked"
    LangAdd "كلمة المرور لا تبدأ ولا تنتهي بمسافة", "The password does not start or end with a space"
    LangAdd "لا تملك صلاحية تعديل التسوية البنكية", "You do not have the permission to edit the bank reconciliation"
    LangAdd "لا توجد إيرادات أو مصروفات في الفترة", "There is no revenue or expense in the period"
    LangAdd "لا يوجد قيد تسوية: الإقرار غير معتمد", "No settlement entry: the return is not approved"
    LangAdd "ليست لديك صلاحية تصفية يومية الكاشير", "You do not have the permission for the daily cashier closing"
    LangAdd "مستحق الآن: اضغط «إنشاء المستحق الآن", "Due now: click Create the due now"
    LangAdd "نهائيًا؟ يُحذف قيده من اليومية أيضًا", "for good? Its journal entry is deleted too"
    LangAdd "ويمكنك التصفية حسب الاختيار (اختياري", "and you can filter by the choice (optional"
    LangAdd "أدخل بداية الفترة الضريبية ونهايتها", "Enter the start and end of the tax period"
    LangAdd "اعتمد الإقرار أولًا، ثم سجّل السداد", "Approve the return first, then record the payment"
    LangAdd "الأصول المتداولة ÷ الخصوم المتداولة", "Current assets / current liabilities"
    LangAdd "السبب / ملاحظات (مطلوب لإعادة الفتح", "Reason / notes (required to reopen"
    LangAdd "العملية غير موجودة أو مطابقة من قبل", "The transaction does not exist or is already matched"
    LangAdd "القيمة المدخلة غير صحيحة لهذا الحقل", "The value entered is not valid for this field"
    LangAdd "تغيير اسم المحل يتم عن طريق المبرمج", "The store name is changed by the developer"
    LangAdd "حساب رئيسي: يشمل كل حساباته التابعة", "Main account: includes all its sub-accounts"
    LangAdd "رصيد العميل المسجل لا يطابق الحركات", "The recorded customer balance does not match the moves"
    LangAdd "رصيد المورد المسجل لا يطابق الحركات", "The recorded supplier balance does not match the moves"
    LangAdd "ضريبة مستردة تُرحَّل للإقرار التالي", "Refundable VAT carried to the next return"
    LangAdd "لا تملك صلاحية تعديل المخزون يدويًا", "You do not have the permission to adjust the stock by hand"
    LangAdd "للمبرمج: توليد كود تفعيل لجهاز عميل", "For the developer: generate an activation code for a customer computer"
    LangAdd "مستحقة خلال 7 أيام أو فات استحقاقها", "Due within 7 days or overdue"
    LangAdd "نسبة الضريبة ليست 15%. هل أنت متأكد", "The VAT rate is not 15%. Are you sure"
    LangAdd "اكتب التاريخ والمعامل (أكبر من صفر", "Type the date and the rate (greater than zero"
    LangAdd "الأصل مستبعد: ألغِ الاستبعاد أولًا", "The asset is disposed: cancel the disposal first"
    LangAdd "العمولة وضريبتها لا تكونان سالبتين", "The fee and its VAT are never negative"
    LangAdd "المصروف بعملة أخرى: اكتب مبلغه بها", "An expense in another currency: type its amount in it"
    LangAdd "تسجيل ارتداد الشيك؟ يعود مبلغه على", "Record the bounce of the cheque? Its amount goes back to"
    LangAdd "فحص سلامة البيانات: لا توجد مشكلات", "Data integrity check: no problems"
    LangAdd "لا تملك صلاحية المندوبين وعمولاتهم", "You do not have the permission for sales reps and their commissions"
    LangAdd "لا تملك صلاحية حذف الحركات البنكية", "You do not have the permission to delete bank transactions"
    LangAdd "لا توجد أرصدة موردين بعملات أجنبية", "There are no supplier balances in foreign currencies"
    LangAdd "لا تُسجَّل دفعات على العميل النقدي", "No payments are recorded on the cash customer"
    LangAdd "مبيعاته ومسير راتبه على هذا المركز", "His sales and payroll are on this center"
    LangAdd "نوع الحركة غير متاح للإدخال اليدوي", "The move type is not available for manual entry"
    LangAdd "هذا الحساب معطّل. راجع مدير النظام", "This account is disabled. Ask the system administrator"
    LangAdd "أدخل تاريخ البداية وتاريخ النهاية", "Enter the start date and the end date"
    LangAdd "إلى تاريخ (الميزانية في هذا اليوم", "To date (the balance sheet on this day"
    LangAdd "اختر آخر يوم في الفترة التي تُقفل", "Choose the last day of the period to close"
    LangAdd "اكتب كلمة المرور مرة أخرى للتأكيد", "Type the password again to confirm"
    LangAdd "الإقرار غير موجود أو معتمد بالفعل", "The return does not exist or is already approved"
    LangAdd "البرنامج غير مفعّل على هذا الجهاز", "The program is not activated on this computer"
    LangAdd "البنك الافتراضي للتحويلات البنكية", "Default bank for bank transfers"
    LangAdd "امسح الباركود (يضيف 1) أو 3*الكود", "Scan the barcode (adds 1) or 3*code"
    LangAdd "بيع آجل لعميل غير مسموح له بالآجل", "A credit sale to a customer not allowed to buy on credit"
    LangAdd "حذف التسوية الجارية وكل مطابقاتها", "Delete the open reconciliation and all its matches"
    LangAdd "حذف الحركة البنكية المحددة وقيدها", "Delete the selected bank transaction and its entry"
    LangAdd "حسب صافي الكمية خلال فترة التقرير", "By net quantity during the report period"
    LangAdd "خصم الغياب أكبر من الأساسي والسكن", "The absence deduction is more than the basic and housing"
    LangAdd "رقمنا (PUR-) أو رقم فاتورة المورد", "Our number (PUR-) or the supplier invoice number"
    LangAdd "سطر لا ينتمي إلى الفاتورة الأصلية", "A line that does not belong to the original invoice"
    LangAdd "طلب سفري: يُغلَّف ويُسلَّم للعميل", "Takeaway order: packed and handed to the customer"
    LangAdd "لا تملك صلاحية تعيين كلمات المرور", "You do not have the permission to set passwords"
    LangAdd "لا يتوقف البيع الآجل بسبب التأخير", "Credit sales are not stopped for delays"
    LangAdd "مبلغ مستحق للمورد (بالريال دائمًا", "an amount due to the supplier (always in SAR"
    LangAdd "مركز المستخدم أو المركز الافتراضي", "The center of the user or the default center"
    LangAdd "هذا الشيك مسجل من قبل لنفس العميل", "This cheque is already recorded for the same customer"
    LangAdd "اختر كلمة مرور مختلفة عن الحالية", "Choose a password different from the current one"
    LangAdd "اكتب تاريخ الشراء وبداية الإهلاك", "Type the purchase date and the start of depreciation"
    LangAdd "الخزينة الرئيسية وصناديق الكاشير", "Main treasury and cashier boxes"
    LangAdd "الرصيد المتبقي على العميل حاليًا", "Balance currently due from the customer"
    LangAdd "المبيعات الخاضعة للنسبة الأساسية", "Sales at the standard rate"
    LangAdd "المشتريات الخاضعة للنسبة الصفرية", "Zero-rated purchases"
    LangAdd "ترحيل المسير وإنشاء قيد العمولات", "Post the run and create the commissions entry"
    LangAdd "تم إلغاء الحفظ: الكمية غير كافية", "Saving was cancelled: the quantity is not enough"
    LangAdd "تم تفعيل البرنامج على هذا الجهاز", "The program was activated on this computer"
    LangAdd "تم نسخ رقم الجهاز. أرسله للمبرمج", "The computer number was copied. Send it to the developer"
    LangAdd "تُنسب له فواتير العميل وتحصيلاته", "The invoices and collections of the customer are credited to him"
    LangAdd "حصّل المتأخر أولًا، أو بِع نقدًا", "Collect the overdue amount first, or sell for cash"
    LangAdd "راجعها وعدّل ما يلزم ثم اضغط حفظ", "Review them, correct what is needed, then press Save"
    LangAdd "فاتورة الشراء الأصلية غير موجودة", "The original purchase invoice does not exist"
    LangAdd "كود التفعيل غير صحيح لهذا الجهاز", "The activation code is not valid for this computer"
    LangAdd "لا تملك صلاحية تسجيل سندات الصرف", "You do not have the permission to record payment vouchers"
    LangAdd "لا تملك صلاحية تعديل أسعار البيع", "You do not have the permission to change sale prices"
    LangAdd "لا توجد حركة نقدية في هذه الفترة", "There is no cash move in this period"
    LangAdd "لا يحتاج هذا التقرير أي اختيارات", "This report needs no choices"
    LangAdd "لا يمكن إلغاء جرد مُرحّل أو ملغى", "A posted or cancelled count cannot be cancelled"
    LangAdd "لا يُسجَّل شيك على العميل النقدي", "No cheque is recorded on the cash customer"
    LangAdd "مصروف متكرر مستحق (إيجار، كهرباء", "Recurring expense due (rent, electricity"
    LangAdd "ملء كل أشهر الموازنة من فعلي سنة", "Fill every month of the budget from the actuals of a year"
    LangAdd "موجود قبل البرنامج (رصيد افتتاحي", "Owned before the program (opening balance"
    LangAdd "يُولَّد تلقائيًا إذا تُرك فارغًا", "Generated automatically if left empty"
    LangAdd "اختر الشهر ثم «إنشاء مسير الشهر", "Choose the month, then Create the run of the month"
    LangAdd "الإقرار مسدد: ألغِ السداد أولًا", "The return is paid: cancel the payment first"
    LangAdd "الحسابات البنكية للمحل وأرصدتها", "The bank accounts of the store and their balances"
    LangAdd "العملاء والموردون حسب الاستحقاق", "Customers and suppliers by due date"
    LangAdd "الموظفون وأسماء الدخول والأدوار", "Employees, login names and roles"
    LangAdd "بحث بالاسم أو الكود أو الباركود", "Search by name, code or barcode"
    LangAdd "تاريخ النهاية قبل تاريخ البداية", "The end date is before the start date"
End Sub

Private Sub D2_2()
    LangAdd "ترحيل المسير وإنشاء قيد الرواتب", "Post the run and create the payroll entry"
    LangAdd "تفعيل البرنامج لمدير النظام فقط", "Activation is for the system administrator only"
    LangAdd "توليد أكواد التفعيل للمبرمج فقط", "Activation codes are generated by the developer only"
    LangAdd "خلال فترة التقرير، شامل الضريبة", "during the report period, including VAT"
    LangAdd "رحّل المسير أولًا، ثم سجّل صرفه", "Post the run first, then record its payment"
    LangAdd "عند حفظ فاتورة البيع أو المرتجع", "When the sales invoice or the return is saved"
    LangAdd "فروقات المخزون (جرد، إضافة، خصم", "Stock differences (count, addition, deduction"
    LangAdd "لا تملك صلاحية إدارة المستخدمين", "You do not have the permission to manage users"
    LangAdd "لا توجد قيود للاختيارات المحددة", "There are no entries for the choices made"
    LangAdd "لا يمكن التحويل إلى نفس الصندوق", "Cannot transfer to the same box"
    LangAdd "لا يمكن الترحيل إلى نفس الصندوق", "Cannot transfer to the same box"
    LangAdd "لا يمكن تعديل التصفية بعد الحفظ", "The closing cannot be edited after saving"
    LangAdd "لا يوجد منتج بالباركود أو الكود", "No product with the barcode or the code"
    LangAdd "يوجد إقرار معتمد بعد هذه الفترة", "There is an approved return after this period"
    LangAdd "يُحذف قيد إقفالها وتُفتح فترتها", "Its closing entry is deleted and its period opened"
    LangAdd "يُخصم كل رصيد السلف في أول مسير", "The whole advance balance is deducted in the first run"
    LangAdd "آخر تسوية معتمدة لهذا البنك في", "Last approved reconciliation of this bank on"
    LangAdd "إعادة الفتح: تصبح الفترة مقفلة", "Reopening: the period becomes closed"
    LangAdd "إلغاء التفعيل لمدير النظام فقط", "Deactivation is for the system administrator only"
    LangAdd "إلغاء ربط هذا المبلغ بالفاتورة", "Unlink this amount from the invoice"
    LangAdd "إيرادات ومصروفات كل مركز تكلفة", "Revenue and expenses of each cost center"
    LangAdd "اختر الحساب في كل سطر فيه مبلغ", "Choose the account in every line with an amount"
    LangAdd "اختر الخزينة التي تستلم المبلغ", "Choose the treasury that receives the amount"
    LangAdd "الحساب المقابل (الحركات الأخرى", "Contra account (other moves"
    LangAdd "الخزينة والصناديق (الرصيد الآن", "Treasury and boxes (balance now"
    LangAdd "السند والفاتورة لطرفين مختلفين", "The voucher and the invoice belong to different parties"
    LangAdd "الشاشة التي يفتحها زر المبيعات", "The screen opened by the Sales button"
    LangAdd "الكمية يجب أن تكون أكبر من صفر", "The quantity must be greater than zero"
    LangAdd "المبلغ أكبر من رصيد سلف الموظف", "The amount is more than the advance balance of the employee"
    LangAdd "المبلغ يجب أن يكون أكبر من صفر", "The amount must be greater than zero"
    LangAdd "المبيعات الشهرية (آخر 12 شهرًا", "Monthly sales (last 12 months"
    LangAdd "المسير مصروف: ألغِ الصرف أولًا", "The run is paid: cancel the payment first"
    LangAdd "تقرير الملصقات غير موجود. شغّل", "The labels report does not exist. Run"
    LangAdd "حركة الخزينة / الصندوق (تفصيلي", "Treasury / box moves (detailed"
    LangAdd "رحّله أو ألغه قبل بدء جرد جديد", "Post it or cancel it before starting a new count"
    LangAdd "كل شاشات الحسابات في مكان واحد", "All the accounting screens in one place"
    LangAdd "لا تملك صلاحية إدارة الصلاحيات", "You do not have the permission to manage permissions"
    LangAdd "لا تملك صلاحية الإقرار الضريبي", "You do not have the permission for the VAT return"
    LangAdd "لا تملك صلاحية النسخ الاحتياطي", "You do not have the permission for backups"
    LangAdd "لا تملك صلاحية تعديل سعر البيع", "You do not have the permission to change the sale price"
    LangAdd "لا توجد فاتورة شراء بهذا الرقم", "There is no purchase invoice with this number"
    LangAdd "لا يوجد سداد مسجل لهذا الإقرار", "No payment is recorded for this return"
    LangAdd "للبيع الآجل اختر عميلًا مسجلًا", "For a credit sale choose a registered customer"
    LangAdd "للعملاء المنشآت (فاتورة ضريبية", "For business customers (tax invoice"
    LangAdd "ليست لديك صلاحية سندات الخزينة", "You do not have the permission for treasury vouchers"
    LangAdd "مجلد Images بجانب ملف البيانات", "Images folder next to the data file"
    LangAdd "مجموع أرصدة المستوى الأول (صفر", "Total of the first-level balances (zero"
    LangAdd "من 1 إلى 28 (يوم الإيجار مثلًا", "From 1 to 28 (the rent day, for example"
    LangAdd "نقر مزدوج على السطر يفتح القيد", "Double-click a line to open the entry"
    LangAdd "أولًا: السنوات تُقفل بالترتيب", "first: years are closed in order"
    LangAdd "إضافة وتعديل الأصناف والأسعار", "Add and edit items and prices"
    LangAdd "اختر البنك المسحوب عليه الشيك", "Choose the bank the cheque is drawn on"
    LangAdd "اختر تقريرًا من القائمة أولًا", "Choose a report from the list first"
    LangAdd "اختر عملية أو أكثر من القائمة", "Choose one or more transactions from the list"
    LangAdd "اختر كلمة مرور جديدة للمتابعة", "Choose a new password to continue"
    LangAdd "اسم العميل على الكوب (اختياري", "Customer name on the cup (optional"
    LangAdd "اكتب الحد الأعلى للأجر الخاضع", "Type the maximum insurable wage"
    LangAdd "اكتب تاريخ البيع أو الاستبعاد", "Type the date of the sale or disposal"
    LangAdd "الإيجار والكهرباء والاشتراكات", "Rent, electricity and subscriptions"
    LangAdd "البرنامج مفعّل على هذا الجهاز", "The program is activated on this computer"
    LangAdd "التكلفة لا يمكن أن تكون سالبة", "The cost cannot be negative"
    LangAdd "المصروفات التشغيلية والإدارية", "Operating and administrative expenses"
    LangAdd "النقدية الفعلية لا تكون سالبة", "The actual cash is never negative"
    LangAdd "انقر مرتين على النتيجة لفتحها", "Double-click a result to open it"
    LangAdd "بدون مسافات، 3 أحرف على الأقل", "No spaces, at least 3 characters"
    LangAdd "بعد المصروفات وفروقات المخزون", "after expenses and stock differences"
    LangAdd "بيع الأصل المعروض أو استبعاده", "Sell or dispose of the asset shown"
    LangAdd "تُعاد فتح آخر تسوية للبنك فقط", "Only the last reconciliation of the bank can be reopened"
    LangAdd "رغم ذلك؟ (بصلاحية مدير النظام", "anyway? (with the permission of the system administrator"
    LangAdd "رقم هذا الجهاز (أرسله للمبرمج", "Number of this computer (send it to the developer"
    LangAdd "طلب التوصيل يحتاج جوال العميل", "A delivery order needs the customer mobile"
    LangAdd "عرض فقط - التصحيح يكون بمرتجع", "View only - a correction is made with a return"
    LangAdd "كلمة المرور الحالية غير صحيحة", "The current password is wrong"
    LangAdd "كلمة مرور جديدة لحساب المبرمج", "New password for the developer account"
    LangAdd "لا تملك صلاحية الأصول الثابتة", "You do not have the permission for fixed assets"
    LangAdd "لا تملك صلاحية القيود اليدوية", "You do not have the permission for manual entries"
    LangAdd "لا تملك صلاحية تقارير الأرباح", "You do not have the permission for profit reports"
    LangAdd "لا توجد منتجات منخفضة المخزون", "There are no low-stock products"
    LangAdd "لا يمكنك تغيير صلاحياتك بنفسك", "You cannot change your own permissions"
    LangAdd "لا يوجد عملاء مسندون لمندوبين", "No customers are assigned to sales reps"
    LangAdd "موجود في الموازنة لنفس المركز", "already in the budget for the same center"
    LangAdd "هذا الإجراء غير موجود في شاشة", "This action does not exist in the screen"
    LangAdd "هل تريد حذف هذا السجل نهائيًا", "Do you want to delete this record for good"
    LangAdd "وتحديث المخزون ومتوسط التكلفة", "and the stock and average cost are updated"
    LangAdd "يبقى في الصندوق (عهدة الكاشير", "Stays in the box (cashier float"
    LangAdd "إقفال الفترات والسنة المالية", "Period and fiscal year closing"
    LangAdd "إلغاء ترحيل المسير وحذف قيده", "Unpost the run and delete its entry"
    LangAdd "اختر المنتج من القائمة أولًا", "Choose the product from the list first"
    LangAdd "اختر النسخة من القائمة أولًا", "Choose the backup from the list first"
    LangAdd "اختر فاتورة آجلة عليها متبقٍ", "Choose a credit invoice with an amount remaining"
    LangAdd "اختر نوع الشيك: وارد أو صادر", "Choose the cheque type: received or issued"
    LangAdd "استبعاد بدون ثمن (تلف أو فقد", "Disposal without a price (damage or loss"
    LangAdd "استحقاق فاتورة الشراء الآجلة", "Due date of a credit purchase invoice"
    LangAdd "اكتب السنة التي يُنسخ فعليها", "Type the year whose actuals are copied"
    LangAdd "التسوية غير موجودة أو معتمدة", "The reconciliation does not exist or is approved"
    LangAdd "الرصيد المستحق للمورد حاليًا", "Balance currently due to the supplier"
    LangAdd "العمر الإنتاجي شهر على الأقل", "The useful life is at least one month"
    LangAdd "المبلغ بالعملة (بدون الضريبة", "Amount in currency (without VAT"
    LangAdd "النسخ الموجودة (الأحدث أولًا", "Existing backups (newest first"
    LangAdd "بداية الإهلاك قبل شهر الشراء", "The depreciation starts before the month of purchase"
    LangAdd "تسجيل دفعة من عميل على حسابه", "Record a payment from a customer on his account"
    LangAdd "حتى لا تتغير مستندات الإقرار", "so that the documents of the return do not change"
    LangAdd "حركة يدوية على المنتج المحدد", "A manual move on the selected product"
    LangAdd "خصم السلفة أكبر من رصيد سلفه", "The advance deduction is more than his advance balance"
    LangAdd "خصم على الفاتورة (بدون ضريبة", "Invoice discount (without VAT"
    LangAdd "دليل الحسابات (شجرة الحسابات", "Chart of accounts (account tree"
    LangAdd "صافي الضريبة المستحقة للسداد", "Net VAT due for payment"
    LangAdd "ضريبة المدخلات أقل من المبلغ", "Input VAT is less than the amount"
    LangAdd "على حساب آخر (مستحقات أو قرض", "On another account (accruals or a loan"
    LangAdd "عملة البرنامج لا تحتاج سعرًا", "The program currency needs no rate"
    LangAdd "قائمة الدخل حسب مركز التكلفة", "Income statement by cost center"
    LangAdd "لا تملك صلاحية إقفال الفترات", "You do not have the permission to close periods"
    LangAdd "لا تملك هذه الصلاحية في شاشة", "You do not have this permission in the screen"
    LangAdd "لا توجد تصفيات في هذه الفترة", "There are no closings in this period"
    LangAdd "لا توجد مبيعات في هذه الفترة", "There are no sales in this period"
    LangAdd "لمن لا مركز له من المستخدمين", "for users without a center"
    LangAdd "مبالغ الموازنة لا تكون سالبة", "Budget amounts are never negative"
    LangAdd "مطابق: لا يوجد عجز ولا زيادة", "Matched: no shortage and no overage"
    LangAdd "وضع المطوّر لمدير النظام فقط", "Developer mode is for the system administrator only"
    LangAdd "يتطلب صلاحية الأرقام المالية", "Needs the permission Financial figures"
End Sub

Private Sub D2_3()
    LangAdd "إجمالي الخصوم وحقوق الملكية", "Total liabilities and equity"
    LangAdd "إقفال الفترة والسنة المالية", "Period and fiscal year closing"
    LangAdd "إلغاء صرف الرواتب وحذف قيده", "Cancel the salary payment and delete its entry"
    LangAdd "اختر آخر شهر يُسجَّل إهلاكه", "Choose the last month to record depreciation for"
    LangAdd "اختر الفاتورة الأصلية أولًا", "Choose the original invoice first"
    LangAdd "الإحصائيات والرسوم البيانية", "Statistics and charts"
    LangAdd "الباقي غير المربوط من السند", "The unlinked remainder of the voucher"
    LangAdd "الفاتورة الأصلية غير موجودة", "The original invoice does not exist"
    LangAdd "المصروفات (إجمالي حسب النوع", "Expenses (total by type"
    LangAdd "بالكامل (لا تبقى فترة مقفلة", "fully (no period stays closed"
    LangAdd "بنكنا (الصادر: المسحوب عليه", "Our bank (issued: drawn on"
    LangAdd "تسجيل الإهلاك حتى هذا الشهر", "Record depreciation up to this month"
    LangAdd "تم الحفظ لكن تعذّرت الطباعة", "Saved, but printing failed"
    LangAdd "تم ضبط وضع المستخدم النهائي", "End-user mode is set"
    LangAdd "تُعاد فتح آخر سنة مقفلة فقط", "Only the last closed year can be reopened"
    LangAdd "خصم الفاتورة أكبر من قيمتها", "The invoice discount is more than its value"
    LangAdd "صادر آخر (رسوم بنكية وغيرها", "Other outgoing (bank fees and others"
    LangAdd "صافي الضريبة المستحقة (سالب", "Net VAT due (negative"
    LangAdd "صافي المبيعات (بدون الضريبة", "Net sales (without VAT"
    LangAdd "لا تكلفة مبيعات أو لا مخزون", "No cost of sales or no stock"
    LangAdd "لا تملك صلاحية مسير الرواتب", "You do not have the permission for payroll"
    LangAdd "لا توجد أشهر لم تُسجَّل حتى", "There are no unrecorded months up to"
    LangAdd "لا توجد قيود للفترة المحددة", "There are no entries for the period set"
    LangAdd "مثال: PCE للحبة، KGM للكيلو", "Example: PCE for a piece, KGM for a kilo"
    LangAdd "مصروف من المصروفات المتكررة", "An expense from the recurring expenses"
    LangAdd "يُقيَّد صافي الربح (الخسارة", "The net profit (loss"
    LangAdd "أضف صنفًا واحدًا على الأقل", "Add at least one item"
    LangAdd "أقصى خصم بدون موافقة (مثال", "Maximum discount without approval (example"
    LangAdd "ألغِ اعتماد الإقرار اللاحق", "Cancel the approval of the later return"
    LangAdd "إعادة فتح التسوية المعتمدة", "Reopen the approved reconciliation"
    LangAdd "إقرار ضريبة القيمة المضافة", "VAT return"
    LangAdd "اختر الصرف من بنك أو صندوق", "Choose to pay from a bank or a box"
    LangAdd "اختر الصندوق الذي دُفع منه", "Choose the box it was paid from"
    LangAdd "اختر الصندوق المحوَّل إليه", "Choose the box transferred to"
    LangAdd "اختر قيمة صحيحة من القائمة", "Choose a valid value from the list"
    LangAdd "البريد الإلكتروني غير صحيح", "The e-mail is not valid"
    LangAdd "السطر الثاني أسفل الباركود", "Second line below the barcode"
    LangAdd "السطر الثاني أعلى الباركود", "Second line above the barcode"
    LangAdd "العملاء والأهداف والعمولات", "Customers, targets and commissions"
    LangAdd "المجموع قبل الخصم والضريبة", "Total before discount and VAT"
    LangAdd "المرتجعات على هذه الفاتورة", "Returns on this invoice"
    LangAdd "المسير غير موجود أو مرحَّل", "The run does not exist or is posted"
    LangAdd "بعد اعتماد الإقرار الضريبي", "after the VAT return is approved"
    LangAdd "تأكيد أخير: استعادة النسخة", "Last confirmation: restore the backup"
    LangAdd "تاريخ الصرف قبل شهر المسير", "The payment date is before the month of the run"
    LangAdd "ترحيل إلى الخزينة الرئيسية", "Transfer to the main treasury"
    LangAdd "تصحيحات من الفترات السابقة", "Corrections from previous periods"
    LangAdd "تعذر عمل النسخة الاحتياطية", "Could not make the backup"
    LangAdd "تغيير أو تعيين كلمة المرور", "Change or set the password"
    LangAdd "دائن الفترة (المستوى الأول", "Period credit (first level"
    LangAdd "رقم الجهاز 16 حرفًا بالشكل", "The computer number has 16 characters in the form"
    LangAdd "في فترة مقفلة (الإقفال حتى", "in a closed period (closed up to"
    LangAdd "كلمة المرور يجب ألا تقل عن", "The password must have at least"
    LangAdd "لا تملك صلاحية سندات الصرف", "You do not have the permission for payment vouchers"
    LangAdd "لا تملك صلاحية سندات القبض", "You do not have the permission for receipt vouchers"
    LangAdd "لا توجد قيود في هذه الفترة", "There are no entries in this period"
    LangAdd "لا توجد موازنة لسنة الفترة", "There is no budget for the year of the period"
    LangAdd "لا يُنشأ مسير لشهر لم يبدأ", "No run is created for a month that has not started"
    LangAdd "لكل فترة ضريبية إقرار واحد", "One return for each tax period"
    LangAdd "ليست لديك صلاحية المصروفات", "You do not have the permission for expenses"
    LangAdd "مدين الفترة (المستوى الأول", "Period debit (first level"
    LangAdd "هامش الربح الإجمالي (الشهر", "Gross profit margin (month"
    LangAdd "هل تريد مسح قائمة الملصقات", "Do you want to clear the label list"
    LangAdd "وسيصبح المورد مدينًا للمحل", "and the supplier will owe the store"
    LangAdd "إعادة الفتح إلى هذا اليوم", "Reopen up to this day"
    LangAdd "إلغاء بيع / استبعاد الأصل", "Cancel the sale / disposal of the asset"
    LangAdd "إلغاء تفعيل الجهاز المحدد", "Deactivate the selected computer"
    LangAdd "اكتب المبلغ بعملة المصروف", "Type the amount in the currency of the expense"
    LangAdd "اكتب معامل التحويل للعملة", "Type the exchange rate of the currency"
    LangAdd "الأرقام من المستندات الآن", "The figures come from the documents now"
    LangAdd "الأصل غير موجود أو مستبعد", "The asset does not exist or is disposed"
    LangAdd "الإقرارات تُعتمد بالترتيب", "Returns are approved in order"
    LangAdd "التحويل بين بنكين مختلفين", "Transfer between two different banks"
    LangAdd "الحسابات البنكية والتسوية", "Bank accounts and reconciliation"
    LangAdd "السطر الأول أسفل الباركود", "First line below the barcode"
    LangAdd "السطر الأول أعلى الباركود", "First line above the barcode"
    LangAdd "الكمية المتوفرة غير كافية", "The available quantity is not enough"
    LangAdd "المبلغ أقل من الإجمالي بـ", "The amount is less than the total by"
    LangAdd "تأكيد كلمة المرور الجديدة", "Confirm the new password"
    LangAdd "تاريخ الاستحقاق قبل تاريخ", "The due date is before the date"
    LangAdd "تجاوز حد الائتمان: الرصيد", "Credit limit exceeded: balance"
    LangAdd "تسجيل دفعة لمورد من حسابه", "Record a payment to a supplier on his account"
    LangAdd "تسوية، صافي قيمة الفروقات", "Adjustment, net value of the differences"
    LangAdd "تم اعتماد التسوية البنكية", "The bank reconciliation was approved"
    LangAdd "تم حفظ الأسماء الإنجليزية", "English names saved"
    LangAdd "تنبيه: الكمية المتوفرة من", "Warning: the available quantity of"
    LangAdd "تُقترح في فواتيره وسنداته", "Suggested in his invoices and vouchers"
    LangAdd "حدد ما يستطيع كل دور فعله", "Set what each role can do"
    LangAdd "حذف الموازنة كلها بأسطرها", "Delete the whole budget with its lines"
    LangAdd "خسارة بيع / استبعاد الأصل", "Loss on sale / disposal of the asset"
    LangAdd "دفتر الأستاذ (كل الحسابات", "General ledger (all accounts"
    LangAdd "رصيد الكشف في هذا التاريخ", "Statement balance on this date"
    LangAdd "سداد ضريبة القيمة المضافة", "VAT payment"
    LangAdd "صرف العمولة يكون بسند صرف", "A commission is paid with a payment voucher"
    LangAdd "طلب التوصيل يحتاج العنوان", "A delivery order needs the address"
    LangAdd "عمولات المندوبين المستحقة", "Sales rep commissions payable"
    LangAdd "غير مسموح له بالبيع الآجل", "is not allowed to buy on credit"
    LangAdd "قيد يكتبه المحاسب: المدين", "An entry written by the accountant: debit"
    LangAdd "كل القيود وميزان المراجعة", "All entries and the trial balance"
    LangAdd "لا توجد أصناف في الفاتورة", "There are no items in the invoice"
    LangAdd "لا توجد فاتورة بهذا الرقم", "There is no invoice with this number"
    LangAdd "لا توجد فاتورة شراء سابقة", "There is no previous purchase invoice"
    LangAdd "لا يمكنك تغيير دورك بنفسك", "You cannot change your own role"
    LangAdd "مصروف (يُسجل في المصروفات", "Expense (recorded in the expenses"
    LangAdd "ملخص ضريبة القيمة المضافة", "VAT summary"
    LangAdd "ميزان المراجعة بالمستويات", "Trial balance by level"
    LangAdd "أدخل المبلغ (أكبر من صفر", "Enter the amount (greater than zero"
    LangAdd "اختر البنك الذي دُفع منه", "Choose the bank it was paid from"
    LangAdd "اختر البنك المحوَّل إليه", "Choose the bank transferred to"
    LangAdd "اختر جردًا مفتوحًا أولًا", "Choose an open count first"
    LangAdd "اختر سطر حساب من القائمة", "Choose an account line from the list"
    LangAdd "اختر فاتورة الشراء أولًا", "Choose the purchase invoice first"
    LangAdd "اكتب سبب إعادة فتح السنة", "Type the reason for reopening the year"
    LangAdd "التاريخ قبل تاريخ الشراء", "The date is before the purchase date"
    LangAdd "الحساب الرئيسي غير موجود", "The main account does not exist"
    LangAdd "الشراء والبيع والاستبعاد", "Purchase, sale and disposal"
    LangAdd "الشيكات الواردة والصادرة", "Received and issued cheques"
    LangAdd "الطباعة عند حفظ الفاتورة", "Printing when the invoice is saved"
    LangAdd "الفترة تتداخل مع الإقرار", "The period overlaps the return"
    LangAdd "القيد غير متوازن: المدين", "The entry is not balanced: debit"
End Sub

Private Sub D2_4()
    LangAdd "المبلغ المسدد بين 0.01 و", "The amount paid is between 0.01 and"
    LangAdd "المتبقي في الصندوق (عهدة", "Left in the box (float"
    LangAdd "بيانات الموردين وأرصدتهم", "Supplier data and balances"
    LangAdd "تاريخ الاعتماد بعد اليوم", "The approval date is after today"
    LangAdd "تحديث القيود من العمليات", "Refresh the entries from the transactions"
    LangAdd "تصنيف الجرد الجديد (فارغ", "Category of the new count (empty"
    LangAdd "تعذر حفظ مرتجع المشتريات", "Could not save the purchase return"
    LangAdd "تُكتب عليه القيود؛ رئيسي", "takes entries, main"
    LangAdd "ثمن البيع لا يكون سالبًا", "The sale price is never negative"
    LangAdd "جلسة الجرد (الأحدث أولًا", "Count session (newest first"
    LangAdd "سجل الإقفال وإعادة الفتح", "Closing and reopening log"
    LangAdd "طباعة مباشرة بدون معاينة", "Print directly without preview"
    LangAdd "عملاء المندوبين وأرصدتهم", "Sales rep customers and balances"
    LangAdd "لا توجد عمليات في الفترة", "There are no transactions in the period"
    LangAdd "مرتجع شراء (استرداد نقدي", "Purchase return (cash refund"
    LangAdd "مرتجع مبيعات (إشعار دائن", "Sales return (credit note"
    LangAdd "مسجلة مسبقًا لنفس المورد", "already recorded for the same supplier"
    LangAdd "نهاية الفترة قبل بدايتها", "The end of the period is before its start"
    LangAdd "هذا الشهر: صافي المبيعات", "This month: net sales"
    LangAdd "هل تريد الحفظ على أي حال", "Do you want to save anyway"
    LangAdd "هل تريد الخروج من النظام", "Do you want to exit the system"
    LangAdd "يجمع حساباته التابعة فقط", "Sums its sub-accounts only"
    LangAdd "أدخل تاريخ أعمار الديون", "Enter the aging date"
    LangAdd "أرصدة الخزينة والصناديق", "Treasury and cash box balances"
    LangAdd "أصلح هذا أولًا، ثم أقفل", "Fix this first, then close"
    LangAdd "أكبر من الحد المسموح لك", "more than the limit allowed to you"
    LangAdd "إجمالي الإيرادات الأخرى", "Total other revenue"
    LangAdd "إجمالي المصروفات الأخرى", "Total other expenses"
    LangAdd "إعدادات ملصقات الباركود", "Barcode label settings"
    LangAdd "إقفال فترة (شهر أو أكثر", "Close a period (a month or more"
    LangAdd "اختر الموظف صاحب السلفة", "Choose the employee who takes the advance"
    LangAdd "اختر تقريرًا من القائمة", "Choose a report from the list"
    LangAdd "استحقاق الفاتورة الآجلة", "Due date of a credit invoice"
    LangAdd "الأشهر تُسجَّل بالترتيب", "months are recorded in order"
    LangAdd "الاسم الإنجليزي أطول من", "The English name is longer than"
    LangAdd "التأمينات - حصة المنشأة", "Social insurance - employer share"
    LangAdd "التاريخ قبل تاريخ الشيك", "The date is before the cheque date"
    LangAdd "الخصومات أكبر من الراتب", "The deductions are more than the salary"
    LangAdd "الرصيد الدفتري (المفروض", "Book balance (expected"
    LangAdd "الشهر التالي للإهلاك هو", "The next month to depreciate is"
    LangAdd "المسافة بين الأعمدة (مم", "Space between columns (mm"
    LangAdd "المصروفات (بدون الضريبة", "Expenses (without VAT"
    LangAdd "المطابقة في هذه التسوية", "Matched in this reconciliation"
    LangAdd "المنتجات منخفضة المخزون", "Low-stock products"
    LangAdd "بيانات العملاء وأرصدتهم", "Customer data and balances"
    LangAdd "بيع أو استبعاد الأصل في", "Sale or disposal of the asset on"
    LangAdd "تاريخ الفاتورة غير صحيح", "The invoice date is not valid"
    LangAdd "تحصيل الشيكات وارتدادها", "Collection and bounce of cheques"
    LangAdd "تعذر ضبط تقرير الملصقات", "Could not set up the labels report"
    LangAdd "تعذر فحص سلامة البيانات", "Could not check the data integrity"
    LangAdd "تقرير الطباعة غير موجود", "The print report does not exist"
    LangAdd "تم التراجع عن التعديلات", "The changes were undone"
    LangAdd "تم تحصيل الشيك في البنك", "The cheque was collected in the bank"
    LangAdd "تم حفظ الأصل وقيد شرائه", "The asset and its purchase entry were saved"
    LangAdd "تُستبدل المبالغ الحالية", "The current amounts are replaced"
    LangAdd "حذف مسودة مسير العمولات", "Delete the draft of the commission run"
    LangAdd "حركة حساب ودفتر الأستاذ", "Account moves and the general ledger"
    LangAdd "دوران المخزون (12 شهرًا", "Stock turnover (12 months"
    LangAdd "رقمه، والرصيد من القيود", "its number, and the balance from the entries"
    LangAdd "شيكات واردة (من العملاء", "Received cheques (from customers"
    LangAdd "صورة الزر في شاشة اللمس", "Button picture on the touch screen"
    LangAdd "عمليات لم تظهر في الكشف", "Transactions not shown on the statement"
    LangAdd "في شاشة الإقرار الضريبي", "in the VAT return screen"
    LangAdd "في فترة مقفلة، لم يُنشأ", "in a closed period, not created"
    LangAdd "قبض نقدية (إيرادات أخرى", "Cash receipt (other revenue"
    LangAdd "قيمة وحدة واحدة بالريال", "Value of one unit in SAR"
    LangAdd "لا تملك صلاحية التقارير", "You do not have the permission for reports"
    LangAdd "لا تملك صلاحية الموازنة", "You do not have the permission for the budget"
    LangAdd "لا تملك صلاحية فتح شاشة", "You do not have the permission to open the screen"
    LangAdd "لا يُحصَّل قبل استحقاقه", "is not collected before its due date"
    LangAdd "مسير الرواتب والتأمينات", "Payroll and social insurance"
    LangAdd "موازنة السنة: الإيرادات", "Budget of the year: revenue"
    LangAdd "وسيصبح للعميل رصيد دائن", "and the customer will have a credit balance"
    LangAdd "أصل جديد: القسط الشهري", "New asset: monthly installment"
    LangAdd "أقل من إجمالي الفاتورة", "less than the invoice total"
    LangAdd "أكبر من الرصيد المستحق", "more than the balance due"
    LangAdd "أكبر من المستحق للمورد", "more than what is due to the supplier"
    LangAdd "إعادة طباعة آخر فاتورة", "Reprint the last invoice"
    LangAdd "إقفال كل المستندات حتى", "Close all documents up to"
    LangAdd "اختر الجهاز من القائمة", "Choose the computer from the list"
    LangAdd "اختر الحركة من القائمة", "Choose the move from the list"
    LangAdd "اختر الحساب، ثم الفترة", "Choose the account, then the period"
    LangAdd "اختر سطرًا من الموازنة", "Choose a budget line"
    LangAdd "اختر فاتورة شراء أولًا", "Choose a purchase invoice first"
    LangAdd "اختر فترة لا إقرار لها", "Choose a period without a return"
    LangAdd "اختر منتجًا من القائمة", "Choose a product from the list"
    LangAdd "استرداد نقدي من المورد", "Cash refund from the supplier"
    LangAdd "استعادة النسخة المحددة", "Restore the selected backup"
    LangAdd "اسم العملة بالإنجليزية", "Currency name in English"
    LangAdd "اسم المحل من الإعدادات", "Store name from the settings"
    LangAdd "اسم نوع المصروف الجديد", "Name of the new expense type"
    LangAdd "الباركود أو كود المنتج", "Barcode or product code"
    LangAdd "البنك (التحصيل / الصرف", "Bank (collection / payment"
    LangAdd "العملات وأسعار التحويل", "Currencies and exchange rates"
    LangAdd "المسافة بين الصفوف (مم", "Space between rows (mm"
    LangAdd "النقدية الفعلية بالعدّ", "Actual cash counted"
    LangAdd "بين كشف البنك والدفاتر", "between the bank statement and the books"
    LangAdd "تاريخ الحركة بعد اليوم", "The date of the move is after today"
    LangAdd "تاريخ الرصيد الافتتاحي", "Opening balance date"
    LangAdd "تاريخ السداد بعد اليوم", "The payment date is after today"
    LangAdd "تاريخ الشراء بعد اليوم", "The purchase date is after today"
    LangAdd "تسوية / مسحوبات المالك", "Settlement / owner drawings"
    LangAdd "تعذر إنشاء قيد التسوية", "The settlement entry could not be created"
    LangAdd "تعذر حفظ فاتورة الشراء", "Could not save the purchase invoice"
    LangAdd "تم ترحيل مسير العمولات", "The commission run was posted"
    LangAdd "تم حفظ مرتجع المشتريات", "The purchase return was saved"
    LangAdd "تمت إعادة إنشاء الأسطر", "The lines were rebuilt"
    LangAdd "حذف الشيك المحدد وقيده", "Delete the selected cheque and its entry"
    LangAdd "حساب فرعي (يقبل القيود", "Sub-account (takes entries"
    LangAdd "رقم الإقرار لدى الهيئة", "Return number at the Authority"
    LangAdd "صافي ربح الشهر (تقريبي", "Net profit of the month (approximate"
    LangAdd "صندوق من يُنشئ المصروف", "Box of the user who creates the expense"
    LangAdd "ضريبة العمولة / الرسوم", "VAT on the fee / charges"
    LangAdd "ضريبة مدخلات المشتريات", "Input VAT on purchases"
    LangAdd "ضريبة مدخلات المصروفات", "Input VAT on expenses"
    LangAdd "غير موجودة أو غير نشطة", "does not exist or is not active"
    LangAdd "فاتورة / مرتجع مشتريات", "Purchase invoice / return"
    LangAdd "قائمة الدخل والميزانية", "Income statement and balance sheet"
    LangAdd "قيود التسوية والافتتاح", "Adjusting and opening entries"
    LangAdd "كشف حساب ودفتر الأستاذ", "Account statement and general ledger"
End Sub

Private Sub D2_5()
    LangAdd "لا تملك صلاحية الشيكات", "You do not have the permission for cheques"
    LangAdd "محاولات الدخول الفاشلة", "Failed login attempts"
    LangAdd "ملف البيانات غير موجود", "The data file does not exist"
    LangAdd "من أضاف أو عدّل أو حذف", "Who added, edited or deleted"
    LangAdd "هذا الخيار للمبرمج فقط", "This option is for the developer only"
    LangAdd "هل تسمح بإتمام العملية", "Do you allow the transaction to be completed"
    LangAdd "وارد آخر (فوائد أو قرض", "Other incoming (interest or a loan"
    LangAdd "يمكنك تصفية صندوقك فقط", "You can close your own box only"
    LangAdd "أضفه من زر «منتج جديد", "Add it with the button New product"
    LangAdd "أفضل 10 منتجات مبيعًا", "Top 10 best-selling products"
    LangAdd "أقل من المبلغ المودَع", "less than the deposited amount"
    LangAdd "أو اختر المنتج بالاسم", "or choose the product by name"
    LangAdd "إجمالي تكلفة المبيعات", "Total cost of sales"
    LangAdd "إجمالي ضريبة المدخلات", "Total input VAT"
    LangAdd "اختر الأصل من القائمة", "Choose the asset from the list"
    LangAdd "اختر الربط من القائمة", "Choose the link from the list"
    LangAdd "اختر الشيك من القائمة", "Choose the cheque from the list"
    LangAdd "اختر جلسة الجرد أولًا", "Choose the count session first"
    LangAdd "اسم المحل بالإنجليزية", "Store name in English"
    LangAdd "الأسعار شاملة الضريبة", "Prices include VAT"
    LangAdd "الأصناف التي لم تُعدّ", "Items not counted"
    LangAdd "الإجمالي شامل الضريبة", "Total including VAT"
    LangAdd "الحذف وإلغاء الاعتماد", "Delete and cancel approval"
    LangAdd "الدفاتر بعد استبعادها", "the books after its disposal"
    LangAdd "الرصيد الحالي للصندوق", "Current balance of the box"
    LangAdd "السماح بالبيع بالسالب", "Allow selling below zero stock"
    LangAdd "الشيك ليس تحت التحصيل", "The cheque is not under collection"
    LangAdd "المبالغ لا تكون سالبة", "Amounts are never negative"
    LangAdd "المبلغ لا يكون سالبًا", "The amount is never negative"
    LangAdd "المنتجات غير المتحركة", "Slow-moving products"
    LangAdd "الموازنة مقابل الفعلي", "Budget vs actual"
    LangAdd "بداية الفترة الضريبية", "Start of the tax period"
    LangAdd "تاريخ الصرف بعد اليوم", "The payment date is after today"
    LangAdd "تاريخ الكشف بعد اليوم", "The statement date is after today"
    LangAdd "تحديث الكميات المسجلة", "Refresh the recorded quantities"
    LangAdd "تحصيلات مدى لم تُسوَّ", "Mada collections not settled"
    LangAdd "تكلفة البضاعة المباعة", "Cost of goods sold"
    LangAdd "تم تسجيل ارتداد الشيك", "The bounce of the cheque was recorded"
    LangAdd "تم تسجيل سداد الضريبة", "The VAT payment was recorded"
    LangAdd "تمت النسخة الاحتياطية", "Backup done"
    LangAdd "جلسة الجرد غير موجودة", "The count session does not exist"
    LangAdd "رصيد البنك في الدفاتر", "Bank balance in the books"
    LangAdd "شيكات صادرة (للموردين", "Issued cheques (to suppliers"
    LangAdd "صافي الضريبة المستحقة", "Net VAT due"
    LangAdd "ضريبة المخرجات للفترة", "Output VAT of the period"
    LangAdd "ضريبة المدخلات للفترة", "Input VAT of the period"
    LangAdd "طباعة ملصقات الباركود", "Print barcode labels"
    LangAdd "عاد الشيك تحت التحصيل", "The cheque is back under collection"
    LangAdd "عدد النسخ المحتفظ بها", "Number of backups kept"
    LangAdd "غير نشط ولا يمكن بيعه", "is not active and cannot be sold"
    LangAdd "قائمة أنواع المصروفات", "List of expense types"
    LangAdd "قيمة المخزون بالتكلفة", "Stock value at cost"
    LangAdd "لا تملك صلاحية البنوك", "You do not have the permission for banks"
    LangAdd "لا توجد تعديلات للحفظ", "There are no changes to save"
    LangAdd "لا مبيعات آجلة في آخر", "No credit sales in the last"
    LangAdd "مبلغ مستحق على العميل", "an amount due from the customer"
    LangAdd "مراكز التكلفة والفروع", "Cost centers and branches"
    LangAdd "مركز من يُنشئ المصروف", "Center of the user who creates the expense"
    LangAdd "مسير عمولات المندوبين", "Sales rep commission run"
    LangAdd "منتجات منخفضة المخزون", "Low-stock products"
    LangAdd "مندوب   صافي المبيعات", "sales reps   Net sales"
    LangAdd "نسبة السيولة (التداول", "Liquidity (current) ratio"
    LangAdd "نسبة العمولة بين 0% و", "The commission rate is between 0% and"
    LangAdd "يجب تغيير كلمة المرور", "The password must be changed"
    LangAdd "يوجد مسير عمولات لشهر", "A commission run for the month"
    LangAdd "أسطر مرتجع المشتريات", "Purchase return lines"
    LangAdd "أفضل المنتجات مبيعًا", "Best-selling products"
    LangAdd "إيداع نقدية في البنك", "Deposit cash in the bank"
    LangAdd "إيداع نقدية من صندوق", "Deposit cash from a box"
End Sub
