Attribute VB_Name = "modZatcaData"
'==============================================================================
' modZatcaData  -  GENERATED by tools/gen_zatca.py from tools/zatca_xml_reference.py. Do not edit.
'
' The fixed texts of the ZATCA phase 2 document (docs/46-ZATCA-Invoice-XML.md), spaces included: the
' signature block (UBL extensions) and the signed properties, as hashed and as written in the document.
' Placeholders: {INVOICE_HASH} {PROPS_DIGEST} {SIGNATURE} {CERTIFICATE} {SIGNED_PROPERTIES}
'               {SIGNING_TIME} {CERT_HASH} {CERT_ISSUER} {CERT_SERIAL}
'==============================================================================
Option Compare Database
Option Explicit

Public Const ZATCA_INITIAL_PIH As String = "NWZlY2ViNjZmZmM4NmYzOGQ5NTI3ODZjNmQ2OTZjNzljMmRiYzIzOWRkNGU5MWI0NjcyOWQ3M2EyN2ZiNTdlOQ=="
Public Const ZATCA_NAMESPACES As String = "xmlns=""urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"" xmlns:cac=""urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"" xmlns:cbc=""urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"" xmlns:ext=""urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"""
Public Const ZATCA_QR_PLACEHOLDER As String = "SET_QR_CODE_DATA"

Public Function ZatcaTemplate(ByVal Name As String) As String
    Select Case Name
        Case "UBL_EXTENSIONS": ZatcaTemplate = UblExtensions()
        Case "SIGNED_PROPERTIES_FOR_HASH": ZatcaTemplate = SignedPropertiesForHash()
        Case "SIGNED_PROPERTIES_FOR_XML": ZatcaTemplate = SignedPropertiesForXml()
    End Select
End Function

Private Function UblExtensions() As String
    Dim s As String
    s = s & "<ext:UBLExtensions>" & vbLf
    s = s & "    <ext:UBLExtension>" & vbLf
    s = s & "        <ext:ExtensionURI>urn:oasis:names:specification:ubl:dsig:enveloped:xades</ext:ExtensionURI>" & vbLf
    s = s & "        <ext:ExtensionContent>" & vbLf
    s = s & "            <sig:UBLDocumentSignatures xmlns:sig=""urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2"" xmlns:sac=""urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2"" xmlns:sbc=""urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2"">" & vbLf
    s = s & "                <sac:SignatureInformation>" & vbLf
    s = s & "                    <cbc:ID>urn:oasis:names:specification:ubl:signature:1</cbc:ID>" & vbLf
    s = s & "                    <sbc:ReferencedSignatureID>urn:oasis:names:specification:ubl:signature:Invoice</sbc:ReferencedSignatureID>" & vbLf
    s = s & "                    <ds:Signature xmlns:ds=""http://www.w3.org/2000/09/xmldsig#"" Id=""signature"">" & vbLf
    s = s & "                        <ds:SignedInfo>" & vbLf
    s = s & "                            <ds:CanonicalizationMethod Algorithm=""http://www.w3.org/2006/12/xml-c14n11""/>" & vbLf
    s = s & "                            <ds:SignatureMethod Algorithm=""http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256""/>" & vbLf
    s = s & "                            <ds:Reference Id=""invoiceSignedData"" URI="""">" & vbLf
    s = s & "                                <ds:Transforms>" & vbLf
    s = s & "                                    <ds:Transform Algorithm=""http://www.w3.org/TR/1999/REC-xpath-19991116"">" & vbLf
    s = s & "                                        <ds:XPath>not(//ancestor-or-self::ext:UBLExtensions)</ds:XPath>" & vbLf
    s = s & "                                    </ds:Transform>" & vbLf
    s = s & "                                    <ds:Transform Algorithm=""http://www.w3.org/TR/1999/REC-xpath-19991116"">" & vbLf
    s = s & "                                        <ds:XPath>not(//ancestor-or-self::cac:Signature)</ds:XPath>" & vbLf
    s = s & "                                    </ds:Transform>" & vbLf
    s = s & "                                    <ds:Transform Algorithm=""http://www.w3.org/TR/1999/REC-xpath-19991116"">" & vbLf
    s = s & "                                        <ds:XPath>not(//ancestor-or-self::cac:AdditionalDocumentReference[cbc:ID='QR'])</ds:XPath>" & vbLf
    s = s & "                                    </ds:Transform>" & vbLf
    s = s & "                                    <ds:Transform Algorithm=""http://www.w3.org/2006/12/xml-c14n11""/>" & vbLf
    s = s & "                                </ds:Transforms>" & vbLf
    s = s & "                                <ds:DigestMethod Algorithm=""http://www.w3.org/2001/04/xmlenc#sha256""/>" & vbLf
    s = s & "                                <ds:DigestValue>{INVOICE_HASH}</ds:DigestValue>" & vbLf
    s = s & "                            </ds:Reference>" & vbLf
    s = s & "                            <ds:Reference Type=""http://www.w3.org/2000/09/xmldsig#SignatureProperties"" URI=""#xadesSignedProperties"">" & vbLf
    s = s & "                                <ds:DigestMethod Algorithm=""http://www.w3.org/2001/04/xmlenc#sha256""/>" & vbLf
    s = s & "                                <ds:DigestValue>{PROPS_DIGEST}</ds:DigestValue>" & vbLf
    s = s & "                            </ds:Reference>" & vbLf
    s = s & "                        </ds:SignedInfo>" & vbLf
    s = s & "                        <ds:SignatureValue>{SIGNATURE}</ds:SignatureValue>" & vbLf
    s = s & "                        <ds:KeyInfo>" & vbLf
    s = s & "                            <ds:X509Data>" & vbLf
    s = s & "                                <ds:X509Certificate>{CERTIFICATE}</ds:X509Certificate>" & vbLf
    s = s & "                            </ds:X509Data>" & vbLf
    s = s & "                        </ds:KeyInfo>" & vbLf
    s = s & "                        <ds:Object>" & vbLf
    s = s & "                            <xades:QualifyingProperties xmlns:xades=""http://uri.etsi.org/01903/v1.3.2#"" Target=""signature"">" & vbLf
    s = s & "                                {SIGNED_PROPERTIES}" & vbLf
    s = s & "                            </xades:QualifyingProperties>" & vbLf
    s = s & "                        </ds:Object>" & vbLf
    s = s & "                    </ds:Signature>" & vbLf
    s = s & "                </sac:SignatureInformation>" & vbLf
    s = s & "            </sig:UBLDocumentSignatures>" & vbLf
    s = s & "        </ext:ExtensionContent>" & vbLf
    s = s & "    </ext:UBLExtension>" & vbLf
    s = s & "</ext:UBLExtensions>"
    UblExtensions = s
End Function

Private Function SignedPropertiesForHash() As String
    Dim s As String
    s = s & "<xades:SignedProperties xmlns:xades=""http://uri.etsi.org/01903/v1.3.2#"" Id=""xadesSignedProperties"">" & vbLf
    s = s & "                                    <xades:SignedSignatureProperties>" & vbLf
    s = s & "                                        <xades:SigningTime>{SIGNING_TIME}</xades:SigningTime>" & vbLf
    s = s & "                                        <xades:SigningCertificate>" & vbLf
    s = s & "                                            <xades:Cert>" & vbLf
    s = s & "                                                <xades:CertDigest>" & vbLf
    s = s & "                                                    <ds:DigestMethod xmlns:ds=""http://www.w3.org/2000/09/xmldsig#"" Algorithm=""http://www.w3.org/2001/04/xmlenc#sha256""/>" & vbLf
    s = s & "                                                    <ds:DigestValue xmlns:ds=""http://www.w3.org/2000/09/xmldsig#"">{CERT_HASH}</ds:DigestValue>" & vbLf
    s = s & "                                                </xades:CertDigest>" & vbLf
    s = s & "                                                <xades:IssuerSerial>" & vbLf
    s = s & "                                                    <ds:X509IssuerName xmlns:ds=""http://www.w3.org/2000/09/xmldsig#"">{CERT_ISSUER}</ds:X509IssuerName>" & vbLf
    s = s & "                                                    <ds:X509SerialNumber xmlns:ds=""http://www.w3.org/2000/09/xmldsig#"">{CERT_SERIAL}</ds:X509SerialNumber>" & vbLf
    s = s & "                                                </xades:IssuerSerial>" & vbLf
    s = s & "                                            </xades:Cert>" & vbLf
    s = s & "                                        </xades:SigningCertificate>" & vbLf
    s = s & "                                    </xades:SignedSignatureProperties>" & vbLf
    s = s & "                                </xades:SignedProperties>"
    SignedPropertiesForHash = s
End Function

Private Function SignedPropertiesForXml() As String
    Dim s As String
    s = s & "<xades:SignedProperties Id=""xadesSignedProperties"">" & vbLf
    s = s & "                                    <xades:SignedSignatureProperties>" & vbLf
    s = s & "                                        <xades:SigningTime>{SIGNING_TIME}</xades:SigningTime>" & vbLf
    s = s & "                                        <xades:SigningCertificate>" & vbLf
    s = s & "                                            <xades:Cert>" & vbLf
    s = s & "                                                <xades:CertDigest>" & vbLf
    s = s & "                                                    <ds:DigestMethod Algorithm=""http://www.w3.org/2001/04/xmlenc#sha256""/>" & vbLf
    s = s & "                                                    <ds:DigestValue>{CERT_HASH}</ds:DigestValue>" & vbLf
    s = s & "                                                </xades:CertDigest>" & vbLf
    s = s & "                                                <xades:IssuerSerial>" & vbLf
    s = s & "                                                    <ds:X509IssuerName>{CERT_ISSUER}</ds:X509IssuerName>" & vbLf
    s = s & "                                                    <ds:X509SerialNumber>{CERT_SERIAL}</ds:X509SerialNumber>" & vbLf
    s = s & "                                                </xades:IssuerSerial>" & vbLf
    s = s & "                                            </xades:Cert>" & vbLf
    s = s & "                                        </xades:SigningCertificate>" & vbLf
    s = s & "                                    </xades:SignedSignatureProperties>" & vbLf
    s = s & "                                </xades:SignedProperties>"
    SignedPropertiesForXml = s
End Function
