"""Generates modZatcaData: the fixed texts of the ZATCA phase 2 document (docs/46-ZATCA-Invoice-XML.md), from
tools/zatca_xml_reference.py, the single source of the exact spaces the ZATCA validator recomputes."""
import zatca_xml_reference as Z
from generate_common import vba_str

TEMPLATES = [("UBL_EXTENSIONS", Z.UBL_EXTENSIONS), ("SIGNED_PROPERTIES_FOR_HASH", Z.SIGNED_PROPERTIES_FOR_HASH),
             ("SIGNED_PROPERTIES_FOR_XML", Z.SIGNED_PROPERTIES_FOR_XML)]


def template_function(name: str, text: str) -> str:
    out = [f"Private Function {name.title().replace('_', '')}() As String", "    Dim s As String"]
    lines = text.split("\n")
    for i, ln in enumerate(lines):
        nl = " & vbLf" if i < len(lines) - 1 else ""
        out.append(f"    s = s & {vba_str(ln)}{nl}")
    out += [f"    {name.title().replace('_', '')} = s", "End Function"]
    return "\n".join(out)


def build_zatca_data_vba() -> str:
    head = f'''Attribute VB_Name = "modZatcaData"
'==============================================================================
' modZatcaData  -  GENERATED by tools/gen_zatca.py from tools/zatca_xml_reference.py. Do not edit.
'
' The fixed texts of the ZATCA phase 2 document (docs/46-ZATCA-Invoice-XML.md), spaces included: the
' signature block (UBL extensions) and the signed properties, as hashed and as written in the document.
' Placeholders: {{INVOICE_HASH}} {{PROPS_DIGEST}} {{SIGNATURE}} {{CERTIFICATE}} {{SIGNED_PROPERTIES}}
'               {{SIGNING_TIME}} {{CERT_HASH}} {{CERT_ISSUER}} {{CERT_SERIAL}}
'==============================================================================
Option Compare Database
Option Explicit

Public Const ZATCA_INITIAL_PIH As String = {vba_str(Z.INITIAL_PIH)}
Public Const ZATCA_NAMESPACES As String = {vba_str(Z.NAMESPACES)}
Public Const ZATCA_QR_PLACEHOLDER As String = {vba_str(Z.QR_PLACEHOLDER)}

Public Function ZatcaTemplate(ByVal Name As String) As String
    Select Case Name
'''
    cases = "".join(f'        Case "{n}": ZatcaTemplate = {n.title().replace("_", "")}()\n' for n, _ in TEMPLATES)
    body = head + cases + "    End Select\nEnd Function\n\n" + "\n\n".join(template_function(n, t) for n, t in TEMPLATES)
    return body + "\n"
