"""English names of the system rows that BuildSchema seeds (docs/39-English-Master-Data.md).

They fill the optional English name fields (Accounts.AccountNameEn, PaymentMethods.MethodNameEn,
JournalSourceTypes.TypeNameEn, TransactionTypes.TypeNameEn). An English front-end shows
Nz(English name, Arabic name), so a row the user added without an English name keeps its Arabic one.
BuildSchema fills only the English names that are still empty (a name the user changed is kept)."""

ACCOUNT_NAMES_EN = {
    1: "Assets",
    11: "Current assets",
    1100: "Cash in treasury and boxes",
    110001: "Main treasury",
    110002: "Cashier box",
    1190: "Cash not allocated to a box",
    1200: "Mada and wallets under settlement (bank and network)",
    1210: "Bank accounts",
    1250: "Cheques under collection",
    1300: "Accounts receivable",
    1310: "Notes receivable",
    1350: "Allowance for doubtful debts",
    1400: "Inventory",
    1500: "VAT - input",
    1600: "Employee advances",
    1610: "Cash floats",
    1650: "Prepaid expenses",
    1660: "Accrued revenue",
    1690: "Deposits with others",
    12: "Non-current assets",
    1710: "Furniture and fixtures",
    1720: "Computers, devices and POS systems",
    1730: "Vehicles",
    1740: "Decorations and store improvements",
    1790: "Accumulated depreciation of fixed assets",
    1800: "Software and licenses",
    2: "Liabilities",
    21: "Current liabilities",
    2100: "Accounts payable",
    2110: "Notes payable (issued cheques)",
    2200: "VAT - output",
    2250: "VAT - settlement and payment",
    2300: "Accrued expenses",
    2310: "Salaries and wages payable",
    2320: "Social insurance payable",
    2330: "Sales rep commissions payable",
    2400: "Customer advances",
    2500: "Short-term loans",
    2600: "Zakat payable",
    22: "Non-current liabilities",
    2700: "Long-term loans",
    2800: "End-of-service benefits provision",
    3: "Equity",
    31: "Capital and owner current account",
    3200: "Capital",
    3100: "Owner current account",
    3900: "Opening balances",
    32: "Retained earnings and results",
    3300: "Retained earnings",
    3400: "Net profit (loss) of the year",
    4: "Revenue",
    41: "Operating revenue",
    4100: "Sales",
    4110: "Sales returns",
    4120: "Discounts allowed",
    42: "Other revenue",
    4200: "Miscellaneous revenue",
    4300: "Cash overages",
    4400: "Discounts received",
    4500: "Gain on sale of fixed assets",
    5: "Expenses",
    51: "Cost of sales",
    5100: "Cost of goods sold",
    5200: "Stock differences and adjustments",
    52: "Operating and administrative expenses",
    5300: "Expenses by type",
    5500: "Salaries and wages",
    5510: "Allowances and incentives",
    5520: "Social insurance",
    5530: "Sales rep commissions",
    5600: "Depreciation of fixed assets",
    5610: "Bank and POS fees",
    5620: "Government fees and licenses",
    5630: "Advertising",
    53: "Other expenses",
    5400: "Cash shortages",
    5650: "Loss on sale and disposal of fixed assets",
    5700: "Bad debts",
    5800: "Zakat",
    5900: "Miscellaneous expenses",
}

PAYMENT_METHODS_EN = {1: "Cash", 2: "Mada / card", 3: "Bank transfer", 4: "E-wallet"}

SOURCE_TYPES_EN = {
    "SALE": "Sales invoice", "SALES_RETURN": "Sales return", "PURCHASE": "Purchase invoice",
    "PURCHASE_RETURN": "Purchase return", "CUSTOMER_PAYMENT": "Customer receipt",
    "SUPPLIER_PAYMENT": "Supplier payment", "EXPENSE": "Expense", "CASH_VOUCHER": "Cash voucher",
    "STOCK_MOVE": "Manual stock move", "STOCK_COUNT": "Stock count adjustment",
    "BOX_OPENING": "Box opening balance", "CUSTOMER_OPENING": "Customer opening balance",
    "SUPPLIER_OPENING": "Supplier opening balance", "MANUAL": "Manual entry", "YEAR_CLOSE": "Year closing entry",
    "VAT_RETURN": "VAT return settlement", "VAT_PAYMENT": "VAT payment", "BANK_OPENING": "Bank opening balance",
    "BANK_TX": "Bank transaction", "CHEQUE": "Received or issued cheque",
    "CHEQUE_STATUS": "Cheque collection or bounce", "ASSET": "Fixed asset purchase",
    "ASSET_DISPOSAL": "Fixed asset sale or disposal", "DEPRECIATION": "Monthly depreciation entry",
    "PAYROLL": "Payroll entry", "PAYROLL_PAYMENT": "Salary payment", "COMMISSION": "Sales rep commissions entry",
}

TRANSACTION_TYPES_EN = {
    "PURCHASE": "Purchase", "SALE": "Sale", "PURCHASE_RETURN": "Purchase return", "SALES_RETURN": "Sales return",
    "STOCK_IN": "Stock addition", "STOCK_OUT": "Stock deduction", "ADJUSTMENT": "Count adjustment",
    "OPENING": "Opening balance",
}

# table: (English field, Arabic field, key field, names by key)
ENGLISH_NAMES = {
    "Accounts": ("AccountNameEn", "AccountName", "AccountCode", ACCOUNT_NAMES_EN),
    "PaymentMethods": ("MethodNameEn", "MethodName", "PaymentMethodID", PAYMENT_METHODS_EN),
    "JournalSourceTypes": ("TypeNameEn", "TypeName", "SourceType", SOURCE_TYPES_EN),
    "TransactionTypes": ("TypeNameEn", "TypeName", "TypeCode", TRANSACTION_TYPES_EN),
}
