"""Phase 7 reference: the purchase/inventory scenario and its expected results,
computed with the pricing reference (tools/pricing.py).

The same numbers are asserted twice:
  * tests/test_purchases.py replays the scenario on the SQLite mirror of the
    back end and checks the saved queries (balances, stock, integrity);
  * modTestPurchases (generated by gen_test_purchases.py) replays it in Access
    through the real posting functions of modPurchases / modSales.

Scenario (the store is VAT registered, VAT 15%, prices typed without VAT):
  1. new supplier, new product A (selling price 115 incl. VAT, no stock)
  2. purchase 1: 100 x A @ 50, supplier charges VAT, credit, 1000 paid now
  3. cash sale of 10 x A                                  -> stock 90 (spec)
  4. purchase 2: 10 x A @ 60, cash, new selling price 120 -> stock 100
  5. purchase return: 10 units of purchase 1, deducted from the account
  6. payment voucher of 1000 to the supplier
  7. product B: opening balance 20 @ 10, damaged stock-out 2
  8. stocktake: A counted 88, B counted 18 -> one adjustment, then posted
"""

from decimal import Decimal as D

import pricing as P

VAT = D("0.15")

P1_QTY, P1_COST, P1_PAID = D(100), D(50), D(1000)
SALE_QTY, SALE_PRICE = D(10), D(115)
P2_QTY, P2_COST, P2_NEW_PRICE = D(10), D(60), D(120)
RETURN_QTY = D(10)
PAYMENT = D(1000)
B_OPENING_QTY, B_OPENING_COST, B_OUT_QTY = D(20), D(10), D(2)
COUNT_A, COUNT_B = D(88), D(18)


def expectations():
    e = {}
    p1 = P.calc([P.LineIn(P1_QTY, P1_COST, D(0), VAT)], D(0), False)
    line1 = p1.lines[0]
    e["P1_TOTAL"] = p1.total
    e["P1_TAX"] = p1.tax
    e["P1_REMAINING"] = p1.total - P1_PAID
    cost1 = P.purchase_unit_cost(line1.net, line1.total, P1_QTY, True)
    avg = P.weighted_average(0, 0, P1_QTY, cost1)
    stock = P1_QTY
    e["AVG_1"] = avg
    e["STOCK_1"] = stock

    stock -= SALE_QTY
    e["STOCK_AFTER_SALE"] = stock

    p2 = P.calc([P.LineIn(P2_QTY, P2_COST, D(0), VAT)], D(0), False)
    e["P2_TOTAL"] = p2.total
    cost2 = P.purchase_unit_cost(p2.lines[0].net, p2.lines[0].total, P2_QTY, True)
    avg = P.weighted_average(stock, avg, P2_QTY, cost2)
    stock += P2_QTY
    e["AVG_2"] = avg
    e["STOCK_2"] = stock

    _, ret_tax, ret_total = P.return_amounts(P1_QTY, line1.total, line1.tax, D(0), D(0), D(0), RETURN_QTY)
    e["RETURN_TOTAL"] = ret_total
    e["RETURN_TAX"] = ret_tax
    avg = P.weighted_average(stock, avg, -RETURN_QTY, cost1)
    stock -= RETURN_QTY
    e["AVG_3"] = avg
    e["STOCK_3"] = stock
    e["BALANCE_AFTER_RETURN"] = e["P1_REMAINING"] - ret_total
    e["BALANCE_FINAL"] = e["BALANCE_AFTER_RETURN"] - PAYMENT

    e["B_STOCK"] = B_OPENING_QTY - B_OUT_QTY
    e["B_AVG"] = B_OPENING_COST

    diff_a = COUNT_A - stock
    e["COUNT_DIFF_A"] = diff_a
    e["COUNT_VALUE"] = P.r2(diff_a * avg)
    e["COUNT_LINES"] = (1 if diff_a else 0) + (1 if COUNT_B != e["B_STOCK"] else 0)
    e["STOCK_FINAL_A"] = COUNT_A
    return e


def vba_number(d: D) -> str:
    """Decimal literal for VBA code (always with a dot, no exponent)."""
    return format(D(d).normalize(), "f")
